### ISSUE TITLE
Bug : affichage des filtres en vue mobile

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#1006]
Certains filtres sont caché en vue mobile à cause de l'encart "Tout effacer / nbr de résultat".

Exemple : 

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/9b2297d9-798d-4c2f-8d05-e8465cdca5c6)

Ici on devrait avoir quatre filtres d'accessibilité mais on en voit que deux même si je scroll tout en bas. Les deux manquants sont cachés par le bouton.

En vue PC j'ai bien les quatre filtres d'accessibilité : 

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/2919fecd-25ad-4bb6-a6eb-459d46c53191)

**Comment by dtrucs** [comment]
Fixé depuis la [3.20.0](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.20.0)
