### ISSUE TITLE
Remarque sur les évènements touristiques

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#1012]
Quelques retours obtenus sur l'affichage des évènements touristiques : 

1. Dans les filtres, la mention "Agenda" semble inutile et alourdi l'interface pour rien
2. Dans les tuiles de résultats, la date de l'évènement est cachée (voir tronquée) lorsque le titre de l'évènement est trop long ou qu'il y a trop d'étiquettes associées.

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/a32cfe1d-6f64-47fd-a4f4-e6d262d28e30)

**Comment by camillemonchicourt** [comment]
Premier point intégré dans la 3.17.0

**Comment by dtrucs** [comment]
Le second point a été intégré dans la [3.17.1](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.17.1)
