### ISSUE TITLE
Problème de CSS personnalisé et bandeau des activités absent en v3.17

### ISSUE THREAD

**Issue by noelmartinon** [GeotrekCE/Geotrek-rando-v3#1019]
Bonjour,

Je rencontre les problèmes indiqués dans le sujet en version 3.17 alors que ce n'était pas le cas en 3.16.1.

Contenu de 'customization/theme/style.css' : 
```
#header {
  background-color: #322b31;
}
```
Le debogueur du navigateur indique pourtant bien que les styles personnalisés s'appliquent : 

- 3.16.1 : 
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/24294841/d0d80dd0-9484-4005-9001-76936714121d)

-  3.17 : 
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/24294841/4975aa08-f7a8-4962-95cc-dbf12d5d89f5)

Copies d'écran où on voit le problème du CSS et celui du bandeau des activités :

- 3.16.1 : 
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/24294841/70769cf9-132b-467d-a47f-a779dd7b2280)

- 3.17 : 
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/24294841/9e5e2bb7-ad2b-419c-8c92-9b9d14919595)

**Comment by dtrucs** [comment]
Hello @noelmartinon 
Merci votre retour, je viens de mettre en place un bugfix pour la personnalisation du header.

Concernant la barre d'activité, sa personnalisation a évolué (cf https://github.com/GeotrekCE/Geotrek-rando-v3/issues/560).
Si vous aviez déjà une configuration sur la clé `activityBar` depuis votre `home.json`, par ex: 

```json
{
  "activityBar": {
    "shouldDisplay": true,
  }
}
```
Cela va surcharger la config par défaut https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/config/home.json et par conséquent, `links` ne sera plus présent dans la fusion des fichiers de configuration.

**Comment by noelmartinon** [comment]
Merci du retour rapide.

Dans le ```home.json```, ```ShouldDisplay``` est bien déclaré , mais pour un bon fonctionnement en 3.17 sans appliquer le bugfix, il me faut ajouter : 
```
 "links": [{
      "type": "trek",
      "grouped": false
    },
    {
      "type": "outdoorSite",
      "grouped": false
    },
    {
      "type": "touristicContent",
      "grouped": false
    },
    {
      "type": "touristicEvent",
      "grouped": false
    }]
  }
```

Pour appliquer le bugfix via ```docker-compose.yml```, j'ai ajouté le volume suivant : 
```- "${PWD}/Header.tsx:/app/src/components/Header/Header.tsx"```
mais il n'est pas pris en compte après redémarrage du docker. Pourtant, en éditant le fichier dans le docker avec ```vi```, c'est bien le fichier patché. Il y aurait une commande ```npm``` à appliquer dans le docker en attendant la prochaine version de geotrek-rando ?

**Comment by camillemonchicourt** [comment]
Si tu veux afficher la barre d'activité telle que fournie par défaut, le mieux est de ne pas renseigner du tout la propriété `activityBar` dans ta surcouche du fichier `home.json`, comme ça c'est le fonctionnement par défaut qui s'applique (https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/config/home.json#L10C3-L29).
Il est conseillé de ne mentionner dans sa surcouche de configuration que les éléments que l'on souhaite modifier par rapport à ce qui est proposé par défaut.

**Comment by noelmartinon** [comment]
Oui, normalement. En fait, j'avais seulement ```"activityBar": { "shouldDisplay": true }```, mais si je laisse uniquement ça et n'indique pas de paramètres dans ```links``` alors je n'ai plus de barre d'activité d'affichée.

**Comment by dtrucs** [comment]
Merci pour vos retours,
Je viens de mettre à jour le changelog de la release pour que cela porte moins à confusion avec les configurations existantes https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/changelog.md#3170-2024-01-12

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.17.1
