### ISSUE TITLE
Error in dictionaries/connector

### ISSUE THREAD

**Issue by geobrun** [GeotrekCE/Geotrek-rando-v3#1026]
Bonsoir tout le monde,

J'essaye de faire fonctionner un Geoterk-rando-v3 sur une virtualbox Ubuntu sur laquelle un Geotrek-admin est aussi installé dessus. Après avoir réalisé de nombreux tests, je suis incapable d'avoir un site public qui fonctionne, même dans sa version la plus simple. A priori, Docker génère bien le site car j'ai la page "Sorry, this is not working properly" (avec une erreur 500 dans la console de Firefox). Et si j'ajoute une flatpage, cela fonctionne. Par contre, tout ce qui a l'air de provenir de Geotrek-admin ne semble pas accessible.

Voici quelques informations sur mes derniers test :
- Geotrek-admin et Geotrek-rando sont accessibles respectivement aux adresses suivantes : `admin.localhost` et `rando.localhost`
- Les langages configurés pour Geotrek-admin sont `fr`, `en`, `de`, `nl` et `zh-hant` (j'en ai mis pas mal à des fins de test)
- Les langages configurés pour Geotrek-rando sont actuellement seulement `fr` et `en`
- A son installation, Geotrek-admin a été configuré pour pouvoir diffuser sur n'importe quel Geotrek-rando (avec le signe `*`)
- Je n'ai qu'un seul trek publié dans Geotrek-admin, rien d'autre (pas de POI, pas de signalétique, pas d’information touristique, etc.)
- L'API de Geotrek-admin répond bien à l'adresse `http://admin.localhost/api/v2` (et elle est bien indiquée dans le fichier `global.json`)
- Je n'ai pas réalisé de synchronisation côté Geotrek-admin, car si j'ai bien compris, cela ne concerne que l'ancienne version de Geotrek-rando
- Mes fichiers de configuration de Geotrek-rando (`global.json`, `header.json`, etc.) ne sont presque pas modifiés : je suppose qu'en indiquant seulement l'API de Geotrek-admin et les langues disponibles, cela doit être suffisant pour que le site fonctionne sans avoir personnalisé d'autres paramètres ?

```
[+] Running 1/0
 ✔ Container geotrek-rando-v3-installer-203-nodeserver-1  Created                                                                                0.0s 
Attaching to nodeserver-1
nodeserver-1  | yarn run v1.22.19
nodeserver-1  | $ node ./src/services/rewriteBuildedPages.mjs
nodeserver-1  | $ NODE_ENV=production node ./src/server.js
nodeserver-1  | warn  - Invalid next.config.js options detected: 
nodeserver-1  |   - The root value has an unexpected property, sentry, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, modularizeImports, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, skipMiddlewareUrlNormalize, skipTrailingSlashRedirect, staticPageGenerationTimeout, swcMinify, trailingSlash, transpilePackages, typescript, useFileSystemPublicRoutes, webpack).
nodeserver-1  | 
nodeserver-1  | See more info here: https://nextjs.org/docs/messages/invalid-next-config
nodeserver-1  | > Ready on http://localhost:3000
nodeserver-1  | Error in dictionaries/connector TypeError: Cannot read properties of undefined (reading 'data')
nodeserver-1  |     at /app/src/.next/server/chunks/742.js:618:20
nodeserver-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
nodeserver-1  |     at async getThemes (/app/src/.next/server/chunks/742.js:639:23)
nodeserver-1  |     at async Promise.all (index 0)
nodeserver-1  |     at async getCommonDictionaries (/app/src/.next/server/chunks/742.js:400:68)
nodeserver-1  |     at async getServerSideProps (/app/src/.next/server/pages/index.js:1189:36)
nodeserver-1  |     at async Object.renderToHTML (/app/node_modules/next/dist/server/render.js:507:20)
nodeserver-1  |     at async doRender (/app/node_modules/next/dist/server/base-server.js:720:34)
nodeserver-1  |     at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/app/node_modules/next/dist/server/base-server.js:837:28)
nodeserver-1  |     at async /app/node_modules/next/dist/server/response-cache/index.js:83:36
nodeserver-1  | TypeError: Cannot read properties of undefined (reading 'data')
nodeserver-1  |     at /app/src/.next/server/chunks/742.js:618:20
nodeserver-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
nodeserver-1  |     at async getThemes (/app/src/.next/server/chunks/742.js:639:23)
nodeserver-1  |     at async Promise.all (index 0)
nodeserver-1  |     at async getCommonDictionaries (/app/src/.next/server/chunks/742.js:400:68)
nodeserver-1  |     at async getServerSideProps (/app/src/.next/server/pages/index.js:1189:36)
nodeserver-1  |     at async Object.renderToHTML (/app/node_modules/next/dist/server/render.js:507:20)
nodeserver-1  |     at async doRender (/app/node_modules/next/dist/server/base-server.js:720:34)
nodeserver-1  |     at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/app/node_modules/next/dist/server/base-server.js:837:28)
nodeserver-1  |     at async /app/node_modules/next/dist/server/response-cache/index.js:83:36
nodeserver-1  | Error in informationDesk/connector TypeError: Cannot read properties of undefined (reading 'data')
nodeserver-1  |     at /app/src/.next/server/chunks/742.js:347:24
nodeserver-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
nodeserver-1  |     at async getInformationDesks (/app/src/.next/server/chunks/742.js:362:37)
nodeserver-1  |     at async Promise.all (index 3)
```

J'avoue que je sèche complètement là ! Le message d'erreur pourrait laisser penser qu'un truc de base (un dictionnaire ?) n'arrive pas à se charger. A moins qu'il ne s'agisse d'un problème de droit d'accès dans les répertoires de Geotrek-admin ? A mon avis, c'est sûrement un truc tout bête que j'ai du loupé dans la doc... Si quelqu'un a une idée, je suis preneur !

**Comment by camillemonchicourt** [comment]
Salut.
Je ne connais pas bien Virtualbox, mais je sais que ça pose parfois des problèmes et ça apporte peut-être des spécificités.
En tout cas il faut que le Geotrek-rando accède à l'API du Geotrek-admin. 
Donc dans ton cas, sur http://admin.localhost/api/v2.
Pas besoin de synchronisation qui était en effet pour la V2 de Geotrek-rando.
Oui normalement il suffit de renseigner l'URL de l'API de Geotrek-admin dans la configuration de Geotrek-rando.

Il faudrait plus de détails. Tu as installé Geotrek-rando avec docker j'imagine ?
Qu'indiquent les logs avec `docker-compose logs -t` ?

Tu as peut-être d'autres infos/erreurs aussi dans la console du navigateur quand tu essaies d'ouvrir une page de Geotrek-rando ?
Si tu regardes dans les requêtes RESEAU du navigateur, vois-tu des éléments récupérés sur l'API http://admin.localhost/api/v2 ?

**Comment by dtrucs** [comment]
Bonjour,
Si je remonte le fil des erreurs, Geotrek Rando ne parvient pas à récupérer les "thèmes" (http://admin.localhost/api/v2/theme/).
Les thèmes sont le premier dictionnaire appelé des "commondictioniaries" et c'est la première interaction API lorsqu'on appelle une page.
À mon avis le problème est que Geotrek Rando n'a pas accès à l'API v2. Checkez les responses status de l'API, les control origins, etc.

**Comment by geobrun** [comment]
Quelques précisions tout d'abord : 
- Je n'essaie pas d'accéder au serveur Geotrek en dehors de la Virtualbox, uniquement à l'intérieur de celle-ci. J'imagine du coup que, étant donné qu'il s'agit d'un simple Ubuntu, celui-ci devrait se comporter normalement tant qu'on reste dans la Virtualbox ?
- Le site Geotrek-rando fonctionne bien avec l'instance de test des Ecrins (donc je suppose qu'il n'y a pas de problème de ce côté et que le souci se trouve bien côté Geotrek-admin)
- J'ai installé Geotrek-rando avec Docker et le log que j'ai fourni provient d'une commande similaire à celle que tu m'as indiquée Camille

Du coup, j'ai regardé du côté de l'API de Geotrek-admin : a priori, les routes fonctionnent bien. La route renvoyant vers les thèmes répond bien : j'ai bien la liste des thèmes issue de toutes les randos publiées (c'est-à-dire un seul thème dans mon test). Si je mets à jour ce thème (traduction dans une langue), cela se retrouve bien côté API.

Je me suis posé la question sur le protocole utilisé : est-ce qu'il ne faudrait pas tout simplement que l'URL de l'API soit obligatoirement configurée en HTTPS pour que Geotrek-rando la "comprenne" ? J'ai tenté des tests ce soir, je suis bien arrivé à passer mon `admin.localhost` en HTTPS via openssl mais on dirait que cela fait ensuite planter Django (connexion refusée à la BDD)... Peut-être que j'arrive en limite d'utilisation sur un localhost là. Du coup, est-ce que vous savez si le HTTPS est obligatoire pour l'API ?

Sinon, il faudra que je restaure ma VM (car mon installation commence à souffrir) pour regarder les requêtes réseau comme vous m'avez tous les deux indiqués !

**Comment by geobrun** [comment]
Je ferme le ticket car il n'a plus lieu d'être. Le problème devait bien provenir de l'installation de l’environnement GeoTrek dans VirtualBox, car après avoir réinstallé toute la solution sur un serveur avec nom de domaine, tout fonctionne correctement. Il ne me reste plus qu'à ajouter du contenu et à réaliser les traductions en mandarin (je n'en suis qu'à un tiers, ça prend pas mal de temps car il y a quand même beaucoup d'entrées dans le fichier de langue !). J'espère pouvoir vous communiquer une première version aboutie dans le courant de l'automne. Encore merci pour votre aide ! :)

**Comment by dtrucs** [comment]
Attention Geotrek Rando ne gère pas le mandarin
Plus d'infos ici https://github.com/GeotrekCE/Geotrek-rando-v3/issues/1011

**Comment by geobrun** [comment]
Merci @dtrucs, je m'en étais rendu compte ! Mon idée, c'est de réaliser le traduction et de fournir ensuite le fichier à la communauté pour l'intégrer à GeoTrek-rando comme nouvelle langue.
