### ISSUE TITLE
Bug page accueil version mobile

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#1027]
Depuis un iphone 11, lorsque je clique sur _Sélectionner une activité_, la liste déroulante passe sous le logo de l'idée rando de la page d'accueil :

![bug_logo2](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/78603108/bc3d2701-ed39-4f8b-ae28-a2f857b757af)

**Comment by dtrucs** [comment]
En parcourant les tickets je réalise que ce bug d'affichage n'est plus d'actualité sur les dernières versions.
Est-ce tu confirmes de ton côté @AudreyRemy auquel cas tu peux le fermer ?

**Comment by AudreyRemy** [comment]
Je confirme merci beaucoup @dtrucs
