### ISSUE TITLE
Pouvoir filtrer sur les réseaux de randonnées

### ISSUE THREAD

**Issue by bruhnild** [GeotrekCE/Geotrek-rando-v3#1043]
Le fichier de customisation `filtrer.json` ne permet pas encore de paramétrer cette option.

**Comment by dtrucs** [comment]
Besoin de https://github.com/GeotrekCE/Geotrek-rando-v3/issues/1043 pour développer cette fonctionnalité

**Comment by dtrucs** [comment]
Fonctionnalité présente depuis [3.21.0](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.21.0).
NB: Nécessite Geotrek Admin [2.108.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.108.0) ou +.
