### ISSUE TITLE
Adaptation affichage arborescence menus selon quantité d'éléments menu

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-rando-v3#1049]
En vue de l'intégration du nouveau HEADER permettant son enrichissement (voir Wireframe ci-dessous)

![Image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/1926041/cbed7b1c-c66b-45a5-a95d-f7802a32a31b)

On distingue trois colonnes qui définissent **trois types** de contenu (vocabulaire technique à définir)
1. Liens **sans** medias associées
2. Liens **avec** médias associées
3. Liens permanents qui n'ont pas de lien de hierarchie avec ce qui est visuellement leur parent direct et sont présents sur tous les sous-menus (option à cocher depuis le back office)

NB: Seuls les liens de la 3ème colonne sont représentés avec des pictogrammes associées, en réalité tous les liens peuvent en avoir.

# Problématique : quelles adaptations de l'affichage en colonne selon :

## L'absence d'un (ou 2) type(s) de contenu

En l'absence de types de contenus, 2 stratégies peuvent être adoptes :
- Soit réduire le nombre de colonne
- Soit basculer un type de contenu sur 2 colonnes: Par exemple s'il n'y a pas de liens  "1. Liens **sans** medias associées", il pourrait être pertinent de diviser "2. Liens **avec** médias associées" en 2 colonnes

Comme le second point implique des algorithmes et de la documentation pouvant vite devenir empirique, la reflexion nous pousse à choisir l'option 1 et apporter un certains nombres de classe CSS sur les éléments afin de pouvoir créer les colonnes, ou bien mettre tout en ligne s'il n'y a qu'un seul type de contenu depuis la CSS personnalisée de la custo. Des exemples seront proposés en tickets.

⚠ Comme tout ne conviendra pour tous les usages, il convient que le rédacteur fasse en sorte de garder une cohérence dans l'équilibre des types de contenu.

**Comment by camillemonchicourt** [comment]
Si on met de côté le 3° type de contenu discutable (liens permanents), on peut aussi imaginer que les liens avec médias passent sur 2 colonnes selon leur nombre et le nombre de liens sans médias associés.

**Comment by dtrucs** [comment]
C'est là que j'estime que ça peut devenir empirique. 
À partir de combien de liens peut-on définir que tel type se dédouble en 2 colonnes ? Avec quelle différence du nombre de lien entre les 2 types restants ? Sur quels critères on décide d'agir de diviser un type et pas l'autre ?

Et après avoir défini ces spécificités et un algorithme en conséquence il va falloir documenter toutes ces conditions particulières. D'autres cas d'usage vont très certainement émerger car pour une raison ou une autre celles définies ne conviendront pas.

Par conséquent, au lieu de s'enfermer dans des critères empiriques, je propose de définir des styles uniquement pour le style des types et ensuite laisser libre cours à la personnalisation CSS pour dédoubler des colonnes lorsque c'est nécessaire.

**Comment by camillemonchicourt** [comment]
On a gardé pour le moment que 2 colonnes, une avec les liens texte, une avec les liens avec image. 
Leur style est customisable si besoin, comme détaillé sur https://github.com/GeotrekCE/Geotrek-rando-v3/issues/1079.

**Comment by camillemonchicourt** [comment]
Intégré dans la version 3.19 (nécessitant Geotrek-admin 2.104+) basée sur le nouveau système d'éléments de menu, complétant les pages statiques.
Documenté côté Geotrek-admin sur https://geotrek.readthedocs.io/en/latest/usage/static-pages.html
Style customisable niveau Geotrek-rando détaillé sur https://github.com/GeotrekCE/Geotrek-rando-v3/issues/1079
