### ISSUE TITLE
Widget meteo affiché malgré désactivation

### ISSUE THREAD

**Issue by noelmartinon** [GeotrekCE/Geotrek-rando-v3#1054]
Malgré le paramètre `"enableMeteoWidget": false,` dans `customization/config/global.json`, le widget meteo reste actif sur les pages _détails_. C'est constaté au moins en version rando 3.16.1, 3.17.1, 3.18.0.

Le css suivant permet de palier ce problème :
```
#details_forecastWidget_ref {
  display: none;
}
```

**Comment by camillemonchicourt** [comment]
Oui c'est normal.
Ce n'est pas un bug mais un breaking change.
On évite d'en faire, mais celui-ci est assumé et annoncé dans la 3.16.0 : https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.16.0

En effet, nous avions fait un développement spécifique pour le widget Meteo France et il nous a semblé plus pertinent de faire un développement bien plus global et générique permettant d'intégrer tout type de widget (météo, qualité de l'air, transports en commun...).
Et cela nous a obligé à supprimer ce paramètre spécifique.

Pour que le widget Météo France continue à fonctionner par défaut, on l'a fourni par défaut dans les widgets des pages détails : https://github.com/GeotrekCE/Geotrek-rando-v3-installer/blob/main/customization/html/details/forecastWidget.html

Pour ne pas afficher ce widget, il te suffit de supprimer ce fichier `forecastWidget.html` de ton dossier de customisation.

**Comment by noelmartinon** [comment]
En fait, j'avais tenté de désactiver le widget en renommant le fichier `forecastWidget.html_`, ce qui n'avait rien changé. 

Après plusieurs tests, il s'avère que si le nom du fichier commence par `forecastWidget.html` et est suivi de n'importe quel suffixe, ex `forecastWidget.html_DISABLED`, alors il est toujours pris en compte ! Il n'est par contre pas pris en compte si on met un préfixe à son nom, où si on le supprime, effectivement.

Merci Camille pour ce rapide retour.
