### ISSUE TITLE
Les # ne sont pas correctement interprétés dans les URL des itinéraires

### ISSUE THREAD

**Issue by bruhnild** [GeotrekCE/Geotrek-rando-v3#1077]
Lors d'une génération d'un page détail (trek/contenu touristique/etc), l'url de la page est composée de la façon suivante 
`<id_de_la_page>-<slugify_du_titre` or le symbole `#` des titres de fiches détails  n'est pas retiré lors de la génération et cela provoque une ancre non désirable (ou même une erreur s'il s'agit du premier caractère) :

Par exemple sur les Vosges du Nord

- /trek/799-#Tresor-des-Vosges-du-Nord-:-Sentier-des-trois-rochers
- /trek/1447-#Tresor-des-Vosges-du-Nord-:-Circuit-des-4-chateaux

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/26433045/18faa735-86ee-4711-8da8-d3c84340594f)

Slugify n'est pas utilisé dans Rando V3.

**Comment by dtrucs** [comment]
Corrigé depuis la version [3.23.2](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.23.2)
