### ISSUE TITLE
script pour le suivi de fréquentation matomo

### ISSUE THREAD

**Issue by vprunet** [GeotrekCE/Geotrek-rando-v3#1110]
Bonjour,

Je viens de  configurer mon instance de geotrek rando pour qu'elle dialogue avec mon serveur matomo, en suivant la procédure documentée ici :
https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization-scripts-GDPR.md

J'ai simplement repris le script proposé par matomo, qui détecte les visiteurs uniques, mais pas les routages réalisés dans le client (ce n'est pas une surprise, c'était très bien expliqué dans la doc geotrek ainsi que dans la doc matomo https://developer.matomo.org/guides/spa-tracking?mtm_campaign=Matomo_App&mtm_source=Matomo_App_OnPremise&mtm_medium=App.CoreAdminHome.trackingCodeGenerator).

Je n'ai pas trouvé dans les échanges geotrek d'exemple de script matomo prêt à l'emploi. Est-ce que l'un d'entre vous a déjà fait cette intégration et pourrait partager son script en exemple? 

Merci d'avance

**Comment by babastienne** [comment]
Bonjour,

Voici le code que nous intégrons : 

```html
<!-- Matomo -->
<script>
  var pageChange = setInterval(function() {
   if (window.next && window.next.router) {
      window.next.router.events.on('routeChangeStart', function(url) {
        if (window && window._paq) {
          _paq.push(['setCustomUrl', url])
          _paq.push(['setDocumentTitle', document.title])
          _paq.push(['trackPageView'])
        }
      });
      clearInterval(pageChange)
    }
  }, 100)
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="<URL>";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '<CODE_DE_SUIVI>']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src='<URL>'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

Pour Matomo pas besoin de gérer l'aspect Banière de cookies car c'est exempté.

**Comment by vprunet** [comment]
Super, merci.

**Comment by camillemonchicourt** [comment]
Voir aussi : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/588
Et plus largement sur le sujet Cookies / GA / Matomo : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/459

Merci pour le partage de code Matomo.
