### ISSUE TITLE
Bug PWA boutons manquants sur page carte d'une rando

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#1114]
Bonjour,

Sur certains téléphones, des fonctionnalités n'apparaissent pas sur toutes les randos :

Ici avec un Redmi Note 10 S, version MIUI Global 14.0.10, version android 13 TP1A.220624.014, version chrome 123.0.6312.120 :

![Bug nature64](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/78603108/5b52508a-e211-4bc1-a25f-f1a1109668b3)

Les éléments manquants entourés en rouge :

![Nature64](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/78603108/99b42847-a370-4908-972c-473799a5eaa4)

Avez-vous déjà rencontré ce problème ?
Merci.

**Comment by dtrucs** [comment]
Bonjour,
Cette fiche rando se trouve avec un scroll horizontal en raison d'un lien trop "long" dans "Informations touristiques complémentaires" de description qui "force" la largeur de la mise en page.

Il conviendrait de faire un fix sur le produit pour éviter de casser cette mise en page en raison de contenu utilisateur.
En attendant vous pouvez ajouter ce sélecteur dans `customization/theme/style.css`

```css
#details_description_ref a:not([class]) {
    overflow-wrap: break-word;
}
```

**Comment by AudreyRemy** [comment]
Merci @dtrucs je vais essayer ça

**Comment by camillemonchicourt** [comment]
Intégra dans la 3.20.0.
