### ISSUE TITLE
Evènements manquants et doublons

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#1141]
Bonjour,
Nous avons 5 événements en date du 29/05/24. Ils sont tous saisis dans Geotrek-admin.
Dans Geotrek-rando 5 évènements remontent mais un manque et un est en double (même url pour le doublon qui n'est bien saisi qu’une fois dans Geotrek-admin)

Geotrek-rando : 
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/78603108/1d87a4fd-bbf8-4586-8932-e04fb8d80be9)

Geotrek-admin : 
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/78603108/49b466c2-b561-4d28-ae9b-125b10412a62)

J'ai redémarré Geotrek-admin et Geotrek-rando mais ça n'a rien changé.

**Comment by camillemonchicourt** [comment]
Je ne reproduis pas le soucis sur votre GTR, que ce soit en filtrant par date (https://nature64.fr/search?event=7&beginDate=2024-05-29&endDate=2024-05-29) ou sans filtrer. 

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/4418840/ecf3ba20-da34-457b-9522-e0d31ca4eeb7)

L'API de GTA qui alimente votre GTR renvoie bien les 5 bons événements : https://geotrek-admin.le64.fr/api/v2/touristicevent/?fields=id%2Cname%2Cbegin_date%2Cend_date&dates_before=2024-05-29&dates_after=2024-05-29

**Comment by AudreyRemy** [comment]
C'est un mystère merci Camille d'avoir regardé
