### ISSUE TITLE
Hitbox des menus trop bas

### ISSUE THREAD

**Issue by noelmartinon** [GeotrekCE/Geotrek-rando-v3#1146]
Bonjour,

Je viens de remarquer que les menus s'ouvrent bien que le pointeur de souris soit assez bas. C'est gênant à l'usage, car les menus d'entêtes se déploient par exemple en voulant imprimer  une rando (export pdf).
Je mets une capture vidéo : 
[Capture vidéo du 2024-05-28 09-47-50.webm](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/24294841/c5a3f102-2dd6-490c-8f77-1551598b867f)
Constaté avec Firefox et Chrome (Pas de Edge ou autres sous la main)

**Comment by camillemonchicourt** [comment]
Corrigé dans la 3.20.2.
