### ISSUE TITLE
Vidéo sur la page d'accueil s'ouvre en plein écran avec iphone

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#1178]
Bonjour
nous avons une vidéo sur notre page d'accueil intégrée via welcomeBanner et videoUrl dans notre fichier home.json.
Sur la version PWA, lorsqu'on clique sur la vidéo elle s'ouvre et passe en plein écran. 
Il arrive de cliquer involontairement sur la vidéo. 
Serait-il possible d'empêcher cette ouverture ?
Iphone 11, version 17.5.1, PWA "téléchargée" et via Safari 

https://github.com/GeotrekCE/Geotrek-rando-v3/assets/78603108/ae7e14a5-5a2b-44f4-9b77-6c45d43b1b93

**Comment by dtrucs** [comment]
Corrigé depuis [3.21.0](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.21.0).
