### ISSUE TITLE
Erreur de chargement pour un nom d'itinéraire avec ":" ou ","

### ISSUE THREAD

**Issue by eprouteau** [GeotrekCE/Geotrek-rando-v3#1205]
Bonjour,

Pour information, je me suis rendu compte que j'avais une erreur de chargement sur geotrek rando dès lors qu'un nom d'itinéraire contient : ou '.

Exemple : https://randordogne.viree-outdoor.com/trek/3020-Test-deux-points-:

URL portail : https://randordogne.viree-outdoor.com/

J'ai résolu le problème en les supprimant lors de mon import massif

Bonne journée,

**Comment by dtrucs** [comment]
Complémentaire de https://github.com/GeotrekCE/Geotrek-rando-v3/issues/1077

**Comment by camillemonchicourt** [comment]
OK, certainement à ajouter à la fonction à la fin du fichier https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/components/pages/search/utils.ts
