### ISSUE TITLE
Migration to React 18.3.* and higher  

### ISSUE THREAD

**Issue by dtrucs** [GeotrekCE/Geotrek-rando-v3#1219]
Currently, Geotrek-Rando applications run on React 18.2.0.

Soon, there will be a major new version of React (19) and a migration should be necessary.
In the meantime, the React team has released version 18.3.1, which is the same code as 18.2.0, but with added warnings. These warnings will become errors in the future major version.

Fortunately, in testing version 18.3.1 we don't have so many warnings.

It should be necessary to update (or change) the `react-burger-menu` package (not updated for 2 years) allowing to create side menus for mobile viewports.

For the moment, I can't see anything else, but I'll keep this ticket up to date.

**Comment by babastienne** [comment]
Thanks @dtrucs for your ticket and for keeping this soft up to date. :pray:
