### ISSUE TITLE
Problème de validation des emails de signalement

### ISSUE THREAD

**Issue by Chatewgne** [GeotrekCE/Geotrek-rando-v3#1257]
Si on entre une adresse mail invalide dans le formulaire de signalement, la validation n'est pas réalisée dans le front contrairement aux autres champs du formulaire

Le back renvoie une erreur appropriée mais celle-ci n'est pas remontée dans l'interface ce qui cause un message NetworkError et l'attention de l'utilisateurice n'est pas redirigée vers la source du problème

![image](https://github.com/user-attachments/assets/e9044d16-cd69-458d-b038-3297194b56b1)

Il faudrait une validation en front comme pour les autres champs, ou alors afficher le message d'erreur du back

![image](https://github.com/user-attachments/assets/706c34c2-dfe3-4a0e-b085-e51e20709251)

**Comment by babastienne** [comment]
Merci @Chatewgne pour cette analyse. :pray:

**Comment by Chatewgne** [comment]
Je retire ce que j'ai dit : ça marche, sauf si on a une erreur de CORS

![image](https://github.com/user-attachments/assets/36da076b-1eb0-42ef-93f7-7bd1e0be251d)

je cherche comment résoudre l'erreur de CORS

**Comment by AudreyRemy** [comment]
Merci pour ce travail @Chatewgne
