### ISSUE TITLE
Problème d'urls non-https

### ISSUE THREAD

**Issue by seegwen** [GeotrekCE/Geotrek-rando-v3#1330]
Bonjour,

J'ai un petit souci, je suis certain que c'est une erreur toute bête de ma part mais je ne parviens pas à la cerner:

J'ai GTA et GTR installés sur la même machine dans des conteneurs docker.
GTA est derrière un proxy nginx. GTR ne l'est plus (il l'était avant mais je me suis rendu compte que je n'en avais pas pas besoin) car...
Mon serveur a en tête un proxy/LB traefik.

Donc j'ai `traefik <-> nginx <-> gta` et `traefik <-> GTR`.

Tout fonctionne très bien sauf les urls des pictogrammes qui sont générés en http et non en https. Les navigateurs sécurisés me disent: "mixed content"/pas-moyen. Et les navigateurs malins essaient quand même en https, au cas-où... et ils ont raison. N'empêche que GTR écris les urls des pictos en http et cela me semble un problème.

Sur la page d'accueil de GTR, les pictos ne s'affichent pas:
https://rando.itineraireschalaisiens.fr
<img width="1257" alt="Capture d’écran 2024-12-18 à 16 10 57" src="https://github.com/user-attachments/assets/19eeae27-23ba-4f92-8f16-02d7e2841ff7" />

Ma config nginx coté GTA (partielle pour pas flooder):
````
[...]
    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_redirect off;

[...]
````

Les configs de GTR:
**home.json**
````
{
  "welcomeBanner": false,
  "activityBar": {
    "shouldDisplay": true,
    "links": [
      { "type": "trek", "grouped": false, "iconUrl": "https://geotrek.itineraireschalaisiens.fr/media/upload/practice-foot.svg" },
      { "type": "outdoorSite", "grouped": false, "iconUrl": "https://geotrek.itineraireschalaisiens.fr/media/upload/gravel-bike_MilYOuB.svg" }
    ]
  },
  "suggestions": {
    "default": [
      {
        "titleTranslationId": "home.territoryTreks",
        "iconUrl": "/icons/practice-pedestrian.svg",
        "ids": ["2", "582", "586", "501", "771", "596"],
        "type": "trek"
      },
      {
        "titleTranslationId": "home.events",
        "iconUrl": "/icons/category-events.svg",
        "ids": ["1", "5"],
        "type": "events"
      },
      {
        "titleTranslationId": "home.outdoor",
        "iconUrl": "/icons/practice-outdoor.svg",
        "ids": ["65", "12", "79"],
        "type": "outdoor"
      },
      {
        "titleTranslationId": "home.services",
        "iconUrl": "/icons/category-services.svg",
        "ids": ["1", "6", "476"],
        "type": "service"
      },
      {
        "titleTranslationId": "home.itinerantTreks",
        "iconUrl": "/icons/practice-pedestrian.svg",
        "ids": ["501", "771", "604"]
      }
    ]
  }
}
````
**global.json**
````
{
  "apiUrl": "https://geotrek.itineraireschalaisiens.fr/api/v2",
  "baseUrl": "https://rando.itineraireschalaisiens.fr/",
  "applicationName": "ITAC",
  "enableOutdoor": false,
  "enableServerCache": true,
  "enableTouristicEvents": false,
  "displayObjectsRelatedToItinerantTreks": {
    "POIs": true,
    "touristicContents": false,
    "sensitiveAreas": false,
    "infrastructures": false,
    "signages": false,
    "service": false
  }
}
````

Dans les sources de GTR je vois ça:
````
<script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"dehydratedState":{"mutations":[],"queries":[{"state":{"data":{"initialFiltersState":[{"id":"practices","options":[{"value":"4","label":"Pédestre","pictogramUrl":"http://geotrek.itineraireschalaisiens.fr/media/upload/practice-foot.svg"},{"value":"5","label":"Vélo Gravel","pictogramUrl":"http://geotrek.itineraireschalaisiens.fr/media/upload/gravel-bike_MilYOuB.svg"}]
[...]
````
On voit que les pictogramUrl ont des url en http et pas https. Le pb passe par là de toute évidence mais je n'ai pas réussi à remonter plus et voir comment est généré ce __NEXT_DATA__ et quel drapeau de config et/ou header ou autre j'aurais pu manquer.

J'aurais bien besoin d'un peu d'aide je suis à court d'idées.

**Comment by babastienne** [comment]
A priori la config de Geotrek-Rando est superflue et le problème vient plutôt de Geotrek-Admin ou de son nginx car quand je vais faire un test sur l'API les pictos sont bien renvoyés en http au lieu d'https : https://geotrek.itineraireschalaisiens.fr/api/v2/trek_practice/

Si on fix ce problème alors ça fonctionnera normalement dans GTR.

J'ai déjà vu ce problème il y a quelques mois mais je ne me souviens plus de l'origine ... :grimacing: 

Est-ce que vous avez bien activé la configuration correspondante dans le custom.py pour avoir du SSL : https://geotrek.readthedocs.io/en/2.111.0/install/configuration.html#activate-ssl-https ?

**Comment by seegwen** [comment]
Oui la config:

````
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
````

est déjà en place.

**Comment by babastienne** [comment]
Ok. Peux-tu transmettre le contenu de ton fichier `custom.py` et  ta conf nginx de GTA complète ?

**Comment by seegwen** [comment]
Oui, bien sur. Merci de m'aider.
[custom.py.txt](https://github.com/user-attachments/files/18195620/custom.py.txt)
[nginx.conf.txt](https://github.com/user-attachments/files/18195622/nginx.conf.txt)

**Comment by babastienne** [comment]
Dans ton custom.py peux-tu essayer de rajouter la ligne `USE_X_FORWARDED_HOST = True` puis faire ta procédure de mise à jour et voir si le problème persiste ?

**Comment by seegwen** [comment]
Merci. Non cela n'a rien changé.

**Comment by babastienne** [comment]
Ok. Dans ce cas c'est clairement un problème lié à la configuration réseau, spécifique entre traefik et nginx. Sur ce point je n'ai pas de compétences.

Ce que je sais c'est que généralement on gère les certificats SSL directement depuis nginx. Là vu la configuration ça ne semble pas être le cas.

Récapitulatif du problème : 
- GTA, lorsqu'il envoi des liens via l'API, envoi les liens au format HTTP alors qu'il devrait le faire au format HTTPS.
- Pour cela, GTA a besoin de savoir que la requête "d'origine" est elle-même en HTTPS. Sauf que vu la configuration réseau actuelle, GTA a l'impression d'être uniquement en HTTP.
- Pour permettre à GTA de savoir quel est le protocole utilisé il faut configurer le serveur web avec l'ajout du header `X-Forwarded-Proto` 
- On voit que ce header est bien présent et correctement configuré dans la configuration nginx actuelle. Donc si nginx reçoit une requête en HTTPS normalement il devrait la transférer "telle quelle" vers GTA
- Donc je pense que le problème vient du lien entre traefik et nginx : je suppose que traefik ne forward pas le protocole utilisé vers NGINX qui traite donc des requêtes HTTP et transfert cette information à GTA.

Le problème est donc plutôt réseau/système qu'applicatif, je ne peux pas aider. Je recommande d'aller chercher de l'aide auprès de la communauté Traefik (il y a déjà quelques sujets [ici](https://community.traefik.io/t/traefik-and-x-forwarded-proto/19240) ou [là](https://community.traefik.io/t/how-to-configure-x-forwarded-for-and-x-forwarded-proto-in-v2/7720) et sûrement ailleurs).

Si tu as la garantie que le protocole HTTPS est bien transféré jusqu'à GTA et que le problème persiste alors ça signifierai que c'est un problème applicatif et dans ce cas n'hésite pas à revenir vers nous.

**Comment by babastienne** [comment]
Je clôture ce ticket car hors scope de Geotrek. N'hésite pas à le rouvrir si tu as des éléments complémentaires permettant de penser que le problème est lié à l'applicatif.

**Comment by seegwen** [comment]
Entendu. J'ai déjà pas mal creusé et lu des topics en ligne. Et je sèche toujours. Je suis persuadé que je suis passé à coté d'un tout petit détail.

En tout cas merci pour ton aide et le temps que tu m'as donné @babastienne. 🙏
