### ISSUE TITLE
Remplacer oldGetSpacing par getSpacing

### ISSUE THREAD

**Issue by Loiklak** [GeotrekCE/Geotrek-rando-v3#16]
`oldGetSpacing` est deprecated et utilisait des multiples de 5 pour nos spacings

Il faut le remplacer par `getSpacing` qui utilise maintenant des multiples de 4

**Comment by dtrucs** [comment]
There is no `oldGetSpacing` variable since https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.13.6
