### ISSUE TITLE
Error 502 : bad gateway -GEotrek Rando V3

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando-v3#264]
Bonjour,

J'ai suivi la procédure d'installation, Tout à l'air ok, sauf lorsque je veux me connecter à la page internet, j'ai une error 502. 
Ma conf nginx : 

```
server {
   location / {
        proxy_pass http://localhost:9001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
   }
    #listen 80;
    #listen [::]:80;
    listen 8001;
    server_name xxx.xxx.xxx.xxx;
}

```
J'ai pris des ports différents car sur ce serveur de test le port 80 est déjà utilisé pour le Geotrek-admin.

Voici le résultat de /var/log/nginx/error.log

```
2021/03/03 14:20:08 [error] 32613#32613: *42971 connect() failed (111: Connection refused) while connecting to upstream, client: xx.xxx.xxx.xx, server: xxx.xxx.xxx, request: "GET / HTTP/1.1", upstream: "http://[::1]:9001/", host: "xxxx.xxx.xxx:8001"
2021/03/03 14:20:08 [error] 32613#32613: *42971 connect() failed (111: Connection refused) while connecting to upstream, client: xx.xxx.xxx.xxx, server: xxx.xxx.xxx., request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9001/", host: "xxx.xxx.xxx:8001"
```

Cela vient sûrement de ma conf Nginx, si j'ai bien compris, on setup un port dans le proxy-pass qui va faire passerelle avec le port 80 du container, et plus bas je mets en place un port pour me connecter au site.

**Comment by camillemonchicourt** [comment]
Justement il faut bien indiquer le port que tu veux utiliser sous la forme monport:80 dans la commande docker run.
Regarde si ton image tourne quand tu fais docker ps et dis nous ce que ça renvoie ?

**Comment by camillemonchicourt** [comment]
Et dans la conf il faut bien laisser le port 80, mais ton docker tournera sur le port que tu as indiqué et ton Geotrek-admin tournera bien sur le port 80.

**Comment by mviadere-openig** [comment]
J'ai remis le port comme tu me l'as demandé :

```
server {
   location / {
        proxy_pass http://localhost:9001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
   }
    listen 80;
    listen [::]:80;
    #listen 8080;
    server_name 91.206.199.197;
}
```
Ma commande  pour run : `docker run -d -p 9001:80 geotrek-rando`
 me retourne ceci : `5b1c0564ba1dfb29fa744b2fb6591b5b1df686a087dabe8bd5705f6f7262c9d2`

Docker ps me retourne ceci : 

```
CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS         PORTS                  NAMES
22db018bb64c   geotrek-rando   "docker-entrypoint.s…"   6 seconds ago   Up 3 seconds   0.0.0.0:9001->80/tcp   beautiful_mclean
```
Je précise que si je laisse le port 80 dans la conf nginx, quand je fais ensuite `sudo nginx -t` pour vérifier il me renvoie ceci :

```
nginx: [warn] conflicting server name "91.206.199.197" on 0.0.0.0:80, ignored
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```
et je n'ai plus accès au Geotrek-admin, c'est pour cette raison que j'avais changé le port au niveau du serveur. De plus si je fais comme lorsque je fais docker ps je n'ai aucun container qui tourne.

**Comment by camillemonchicourt** [comment]
Mais tu as accès à Geotrek-rando de cette façon ??

**Comment by mviadere-openig** [comment]
Non j'ai un 502 bad gateway

**Comment by camillemonchicourt** [comment]
OK je maîtrise pas bien Docker ni les conf NGINX, mais ton soucis semble venir de la conf NGINX, ton container semble bien tourner.

Voici mon cas qui fonctionne : 

- Sur mon serveur j'avais déjà un Geotrek-admin : 5.135.42.177
- J'ai installé Docker et un container Geotrek-rando v3 avec un sous-domaine pointant sur ce serveur : https://gtr3.ecrins-parcnational.fr/
- Ma commande de build : ``docker run -d -p 82:80 geotrek-rando``
- Ma conf NGINX (incluant la partie HTTPS générée automatiquement parCertbot) : 
```
server {
   location / {
        proxy_pass http://localhost:82;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
   }
    server_name gtr3.ecrins-parcnational.fr;

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/gtr3.ecrins-parcnational.fr/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/gtr3.ecrins-parcnational.fr/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = gtr3.ecrins-parcnational.fr) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name gtr3.ecrins-parcnational.fr;
    return 404; # managed by Certbot
```

**Comment by camillemonchicourt** [comment]
Salut, je viens de mettre en place un autre Geotrek-rando V3 sur notre serveur qui accueille déjà Geotrek-admin de DEMO (https://geotrekdemo.ecrins-parcnational.fr/) et idem ça fonctionne bien : https://gtr3demo.ecrins-parcnational.fr

Donc ça doit bien être un problème dans ta configuration NGINX.

**Comment by mviadere-openig** [comment]
Bonjour, 

on a trouvé d'où venait le problème. 

Je n'avais modifié que le fichier config/apiCalls.json puis essayé de lancer le container. Il n'arrêtait pas de redémarrer.

Après que mon hébergeur ai fait plusieurs tests, on a trouvé le problème, il faut une config minimale dans la customisation pour que ça fonctionne  : 

- modifier le fichier config/apiCalls.json
- Et rajouter 2 lignes dans  config/header.json =>
"primaryItemsNumber": 3,
    "shouldDisplayFavorite": true

**Comment by camillemonchicourt** [comment]
OK dans les nouvelles versions ce fichier a été remplacé par un fichier nommé ``global.json`` pour un nom plus adapté.
Je ne vois pas bien pourquoi il fallait modifier ce fichier, et pourquoi il faut un minimum d'infos dans le fichier header.json, mais on pourrait creuser cela car c'est pas souhaitable.
