### ISSUE TITLE
(35 base + ? leaflet)Offline support for large amount of searches

### ISSUE THREAD

**Issue by sraikimaxime** [GeotrekCE/Geotrek-rando-v3#287]
## Problem

The offline behavior of the web application is handled by the progressive web app engine "service worker" cache. We provided limits to the service worker concerning the number of pages it had to store in cache (see cache.js file).

We observed that making a search operation was triggering several requests and therefore occupying a significant space on the cache (can sometimes reach up to 3MB), the natural limit imposed by apple for pwa cache is 50MB meaning we should have an acceptable behavior for the canonical use we anticipated.

Stil, this behavior is not scalable and if future developers start adding requests during other operations we could see the offline behavior starting to get flaky (randomly working).

## Proposed solutions
Solutions that could secure this behavior would be:
- Reduce the number of peripheral calls made during the search
- Use the local storage to store resources that specifically need to be accessed offline

**Comment by camillemonchicourt** [comment]
See caching documentation for more details: https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/knowledge/caching.md

The offline strategy is actually a first basic step. 
When browsing some pages, contents are kept in local cache with a certain limit, to be available offline.

But the user don't know which contents are available offline or not.
It is actually limited to 32 objects (pages).
The offline maps are actually limited to 256 entries which can be reached fast with map tiles.
Another actual problem is that the search is based on several API calls which will not work anymore when offline.

In a second version, it would deserve to go further.
I would rather add a clear action to download some objects manually.
And when being offline, I would desactivate the search and just list objects that are available offline.

**Comment by camillemonchicourt** [comment]
On part donc sur le fait d'avoir un contenu OFFLINE en mobile beaucoup plus explicite, se rapprochant de ce qui est fait sur Geotrek-mobile.

Quand on est sur la fiche d'un contenu, on peut le télécharger pour en disposer en offline : 

![image](https://user-images.githubusercontent.com/4418840/132949928-6b7eab10-534a-4df6-8037-24991bbdcf88.png)

On peut ensuite accéder à la liste de ses contenus téléchargés, consultables sans réseau : 

![image](https://user-images.githubusercontent.com/4418840/132949952-a1a4aa6a-8b06-42ab-9573-8ff9d53f4e00.png)

On ne peut pas lancer une recherche OFFLINE car sans réseau on n'accède pas l'API de Geotrek-admin.

Si je n'ai pas de réseau (ou si je n'en ai pas), je ne peux pas non plus accéder à "Mes favoris" ?

![image](https://user-images.githubusercontent.com/4418840/132949998-e859c30c-b7dd-4993-96ae-18df905dbb70.png)

**Comment by camillemonchicourt** [comment]
On avait prévu dans la 3.4.0 de pouvoir utiliser des tuiles différentes pour la version OFFLINE, en pouvant spécifier un paramètre de tuiles dédié aux tuiles offline (``mapClassicLayerUrlOffline``)
Mais actuellement le plugin utilisé ``leaflet-offline`` ne peut pas changer dynamiquement de fond de carte utilisé, il prend celui affiché au moment où l'utilisateur demande de télécharger les tuiles en offline.
Il a donc fallu supprimer ce paramètre dans la 3.5.0 car il ne fonctionnait pas : https://github.com/GeotrekCE/Geotrek-rando-v3/commit/7b1d2e8572c0a3cb92bd085c88bb1d602330828d

D'autres petites corrections ont été réalisés dans la version 3.5.0 à venir, ainsi que l'extension du fonctionnement OFFLINE aux sites et parcours Outdoor.

**Comment by camillemonchicourt** [comment]
En complément les galeries photo ont été désactivés dans la 3.5.0 quand on n'a pas de réseau internet, car les photos des galeries ne sont pas préchargées, et donc ne s'affichaient pas quand on n'a pas de réseau.
Seul la première galerie s'affiche et les boutons des slideshows sont masqués.

Améliorations envisagées du mode OFFLINE : 
- Creuser la possibilité d'avoir un fond différent pour les fonds offline (nécessiterait certainement une PR sur Leaflet-offline
- Afficher espace utilisé / disponible sur la page listant les contenus hors-ligne
- Ajouter un bouton pour supprimer TOUS les contenus offline
- Pré-charger les pages statiques

**Comment by AudreyRemy** [comment]
Bonjour,
Que ce soit avec les applications Mozilla ou Chrome j'ai bien réussi à ajouter un contenu hors ligne mais lorsque je suis hors ligne et que je tente d'ouvrir la fiche via le menu hors ligne, j'obtiens une page "Aucune connexion internet". Y a-t-il un paramétrage à faire ?
Merci et bonne journée.

**Comment by camillemonchicourt** [comment]
OK, toujours intéressant de voir des nouveaux Geotrek-rando-v3.
Tu pourrais déjà le mettre à jour en lançant simplement la commande ``docker-compose pull && docker-compose down && docker-compose up -d`` depuis le dossier de ton Geotrek-rando-v3, car il y a eu différentes évolutions et corrections depuis la version que tu as.

Sinon j'ai testé le offline sur ton serveur de test et ça fonctionne bien.
J'ai juste un soucis au premier chargement de la page "Contenus hors-ligne", qu'il faut rafraichir, à creuser. Mais ce n'est pas le soucis que tu as remonté il me semble.

**Comment by camillemonchicourt** [comment]
On peut automatiser les mises à jour, mais je trouve ça un peu risqué.
Il vaut mieux le faire en connaissance de cause selon moi en sachant en quelle version on est actuellement, et toutes les nouveautés développées avant de faire une mise à jour.
Pour cela, voir https://github.com/GeotrekCE/Geotrek-rando-v3/releases.
Sinon vous pouvez avoir des nouvelles fonctionnalités qui apparaissent sans que vous sachiez quand ni comment.
Il est aussi possible qu'une nouvelle fonctionnalité ajoutée dans une nouvelle version, nécessite de la paramétrer pour l'adapter à votre contexte, donc je conseille plutôt de faire les mises à jour manuellement, en regardant bien avant toutes les nouveautés des versions entre sa version installée et la dernière version.

Il est par contre possible de s'abonner à un Github pour être notifié des tickets, pull requests et nouvelles versions. Et il est possible d'indiquer d'être notifié seulement en cas de nouvelle version (release). En haut à droite dans WATCHING.

Concernant le fait de ne pas indexer dans les moteurs de recherche, il y a mieux, il y a un paramètre dédié à cela : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/config/global.json#L19
En le passant à ``false`` les moteurs de recherche ne pourront pas indexer le site.
Il faut penser à bien le repenser à ``true`` quand on passe le site en production ! :-)

**Comment by camillemonchicourt** [comment]
Le fait de pouvoir définir un fond différent pour la version Offline est de retour avec cette PR : https://github.com/GeotrekCE/Geotrek-rando-v3/pull/719 et le paramètre optionnel ``mapOfflineLayer``.
