### ISSUE TITLE
Retour à la rando parent

### ISSUE THREAD

**Issue by kisitocendrier** [GeotrekCE/Geotrek-rando-v3#304]
Pas de bouton retour pour revenir à la rando parent dans une randonnée par étapes après avoir cliqué sur une étape.

**Comment by camillemonchicourt** [comment]
Oui exact, bien vu.
On est en train de faire 2 semaines de développements complémentaires et il est notamment prévu d'ajouter cette fonctionnalité : "Sur une fiche fille itinérance, afficher le nom (cliquable) de la fiche mère"

**Comment by camillemonchicourt** [comment]
Fait dans https://github.com/GeotrekCE/Geotrek-rando-v3/pull/308

**Comment by camillemonchicourt** [comment]
A voir sur https://geotrek-rando-v3-pi.vercel.app/trek/604-Le-Super-Chemin?parentId=501
