### ISSUE TITLE
error Command failed with signal "SIGKILL".

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando-v3#360]
Depuis hier et aujourd'hui, quand je tente de build avec la v0.0.17 ou la v3.0.0, j'ai cette erreur. 

J'ai tenté en faisant des modifications dans mon dossier config/ et/ou medias/, ça ne change rien au problème. 

Idem après avoir fait du nettoyage comme le recommande la doc ici : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/installation.md#manage-docker-images-storage-on-disk

J'ai finis par recommencer dans un autre dossier et je retombe sur la même erreur. 

Commande faite pour reproduire l'erreur : 

```
mkdir Geotrek-rando-test 

cd Geotrek-rando-test

git init .

git pull https://github.com/GeotrekCE/Geotrek-rando-v3-installer.git

#Copie des contenus exemples des fichiers du dossier config/

docker build -t geotrek-rando --build-arg VERSION=latest .


qui donne comme résultat : 
`error Command failed with signal "SIGKILL".`
```

**Comment by camillemonchicourt** [comment]
J'ai eu des problèmes similaires.
Parfois c'était les ressources de mon serveur qui saturaient lors du build et ça passait en relançant le build. 

Ton build fonctionnait bien sur ce ressource précédemment ?

Tu n'as pas de soucis de place sur le serveur ou de ressources qui saturent ?

**Comment by mviadere-openig** [comment]
ok, alors j'ai check ma ram, espace disque, aucun problème de ce côté. La dernière fois que j'avais eu cette erreur j'ai fait sudo apt-get update && sudo apt-get upgrade et ça a fonctionné. 

Tout fonctionnaient très bien jusqu'à hier. Je viens de redémarrer le serveur...et ça fonctionne.

**Comment by sraikimaxime** [comment]
Hello,

Nous avons observé ces problèmes de notre côté sur des machines avec peu de RAM, il est possible de limiter la RAM qui va être utilisée par docker lors du build en passant l'option "-m 2g" (pour memory 2 Giga) comme ceci

"docker build -t geotrek-rando -m 2g --build-arg VERSION={VERSION} ."

J'ai l'impression que mettre moins de 2g ne permet pas au serveur node de builder l'app. Donc 2g me semble une bonne option (je viens de tester sur un serveur avec 4g de RAM et tout s'est bien passé).

**Comment by camillemonchicourt** [comment]
Excellent @sraikimaxime, merci.
Ça fonctionne et mon serveur de DEMO qui était coincé avec ce problème est de nouveau sur pied : https://gtr3demo.ecrins-parcnational.fr/
Je vais voir pour ajouter cette option dans la doc.
