### ISSUE TITLE
Amélioration - Performances

### ISSUE THREAD

**Issue by sraikimaxime** [GeotrekCE/Geotrek-rando-v3#362]
Je créé cette issue pour noter qu'après analyse du site dans Pagespeed insights (version hébergée sur le web de spotlight), nous avons des optimisation de performance à faire.
- Il apparait que les call à l'api (sur la page de détails en tous cas) ne sont pas excessivement long (de l'ordre de 600ms)
- Le rendering ne semble également pas en cause (de l'ordre de 200ms)
- Certaines images sont très large et peuvent bloquer le réseau pendant 500ms chacunes
- On observe un TTFB très long de l'ordre de 3s ou 4s que je n'ai pas encore complètement expliqué
- Il est également possible que le téléchargement et l'installation du service worker soit en cause

**Comment by camillemonchicourt** [comment]
Après les précisions récentes de Google sur les signaux web essentiels (https://web.dev/vitals/), nous avons testé des pages de fiches randos de la nouvelle version de Geotrek-rando dans l'outil PageSpeed Insights et celles-ci obtiennent des notes très faibles, inférieures à 20 sur 100 : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgtr3.ecrins-parcnational.fr%2Ftrek%2F903280-Le-circuit-des-lacs 

Quelques premières investigations ont été réalisées et il a été fait en sorte de ne pas charger par défaut toutes les images des carrousels pour limiter la taille des pages : https://github.com/GeotrekCE/Geotrek-rando-v3/pull/356

**Comment by camillemonchicourt** [comment]
PageSpeed - Analyse comparative sur la version 3.0.3 : 

- GTR3 test (home) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgtr3.ecrins-parcnational.fr&tab=mobile
Mobile : 49 / Desktop : 90
- RGC (Home) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frando.parc-grands-causses.fr
Mobile : 50 / Desktop : 75
- GTR3 test (Search) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgtr3.ecrins-parcnational.fr%2Fsearch
Mobile : 16 / Desktop : 39
- RGC (Search) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frando.parc-grands-causses.fr%2Fsearch
Mobile : 15 / Desktop : 19
- GTR3 test (fiche rando) - https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgtr3.ecrins-parcnational.fr%2Ftrek%2F903280-Le-circuit-des-lacs&tab=mobile
Mobile : 26 / Desktop : 66
- RGC (fiche rando) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frando.parc-grands-causses.fr%2Ftrek%2F20-Le-dolmen-de-Tiergues
Mobile : 19 / Ordinateur : 45
- RGC (fiche rando avec moins de contenus touristiques liés) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frando.parc-grands-causses.fr%2Ftrek%2F1430-Au-bord-du-cours-d%27eau
Mobile : 28 / Desktop : 57
- GTR3 (fiche service) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgtr3.ecrins-parcnational.fr%2Fservice%2F2224-Miel-de-haute-montagne
Mobile : 44 / 75
- RGC (ficher service) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frando.parc-grands-causses.fr%2Fservice%2F47017-G%25C3%25AEte-%25C3%25A0-la-ferme
Mobile : 28 / Desktop : 73

**Comment by Sylchauf** [comment]
Les performances ont été optimisées : 
- Configuration du cache react-query pour éviter une double requête lors d'un chargement initial en SSR
- Suppression de dépendances non utilisées
- Configuration du paquet react-burger-menu pour alléger le bundle JS
- Mise en place de PurgeCSS pour alléger le bundle CSS

Piste d'optimisation supplémentaire : 
- Remplacement du paquet react-select
- Mise en place d'un CDN pour les images
- Tuning du fichier leaflet-src.js (pour charger la version minifiée à la place)
- Étudier le composant du profil altimétrique qui charge la lib d3 juste pour un graphique

**Comment by camillemonchicourt** [comment]
En passant sur la 3.0.4-beta1, on a des améliorations intéressantes, en Desktop notamment, mais peu ou pas sur les fiches randos : 

- GTR3 test (Home) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgtr3.ecrins-parcnational.fr&tab=mobile
Mobile : 58 / Desktop : 96
- RGC (Home) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frando.parc-grands-causses.fr
Mobile : 54 / Desktop : 85
- GTR3 test (Search) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgtr3.ecrins-parcnational.fr%2Fsearch
Mobile : 23 / Desktop : 61
- RGC (Search) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frando.parc-grands-causses.fr%2Fsearch
Mobile : 18 / Desktop : 31
- GTR3 test (fiche rando) - https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgtr3.ecrins-parcnational.fr%2Ftrek%2F903280-Le-circuit-des-lacs&tab=mobile
Mobile : 26 / Desktop : 73
- RGC (fiche rando) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frando.parc-grands-causses.fr%2Ftrek%2F20-Le-dolmen-de-Tiergues
Mobile : 17 / Ordinateur : 48
- RGC (fiche rando avec moins de contenus touristiques liés) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frando.parc-grands-causses.fr%2Ftrek%2F1430-Au-bord-du-cours-d%27eau
Mobile : 25 / Desktop : 66
- GTR3 (fiche service) : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgtr3.ecrins-parcnational.fr%2Fservice%2F2224-Miel-de-haute-montagne
Mobile : 43 / 81
