### ISSUE TITLE
Problème de retour à la page recherche depuis fiche randonnée

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-rando-v3#364]
Lorsque l'on suit les étapes suivantes, le retour à la page recherche via le bouton retour du navigateur n'est pas opérationnel. 

- Sur la page d'accueil sélectionner une pratique
- Sur la page de recherche déselectionner la pratique
- Cliquer sur une randonnée pour aller sur la fiche détail
- Cliquer sur le bouton back sur navigateur

Le comportement est le même avec un contenu touristique

**Comment by camillemonchicourt** [comment]
J'ai souvent ce soucis, mais pas tout le temps et on n'a pas réussi à le reproduire de manière fiable.
Là j'arrive parfois à le reproduire, même en aillant une pratique sélectionnée, donc j'arrive pas à dire dans quels cas cela se produit ou non.

**Comment by amandine-sahl** [comment]
Il faut toujours repartir de la page d'accueil. 
J'ai réussi à le reproduire sur notre et votre instance de test et le site des grands causses
