### ISSUE TITLE
Carte - Pouvoir filtrer selon zone affichée

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#383]
Le contenu de la liste de résultat prend en compte les filtres, mais aussi la zone de la carte affichée.
Voir AirBnB, ou https://rando.ecrins-parcnational.fr

Avec une case à cocher pour activer ou non ce fonctionnement.
Et un paramètre pour définir si elle est cocher ou non par défaut ?

**Comment by camillemonchicourt** [comment]
En appelant la route /trek qui renvoie les randos d'une recherche, en format geojson, on a une BBOX de la zone de résultat.
Mais c'est surtout le filtre ``in_bbox`` de la route /trek qui nous sera utile pour cette fonctionnalité.
Quand on zoome ou se déplace dans la carte, il faut récupérer la BBOX affichée dans Leaflet, et renvoyer une requête à l'API pour filtrer les routes /trek et /touristiccontent avec le filtre ``in_bbox``.

**Comment by Sylchauf** [comment]
Il manque la possibilité d'activé ou non cette fonctionnalité

**Comment by camillemonchicourt** [comment]
OK, je dirai qu'on peut mettre un paramètre pour activer ou non cette fonctionnalité au niveau de l'instance.

Et peut-être un paramètre pour définir si cette fonctionnalité est activée par défaut ou non.

Sur Airbnb, c'est présenté comme ça : 

![Capture d’écran de 2021-06-25 09-02-08](https://user-images.githubusercontent.com/4418840/123384320-8c42db80-d594-11eb-88e9-7ae9d22d1a3e.png)

Là j'afficherai le bouton en bas de la carte, centré, pas en mobile.
Et pour le texte "Filtrer avec la carte" ou "Recherche quand je déplace la carte" (comme sur Airbnb)

**Comment by camillemonchicourt** [comment]
Ou sinon on a évoqué l'idée de plutôt afficher la case à cocher activant ou non fonctionnalité avec les autres filtres, pour les regrouper et ne pas surcharger la carte.

**Comment by camillemonchicourt** [comment]
Il faut au moins ajouter un paramètre ou non cette fonctionnalité.
Si en plus on ajoute la possibilité à l'utilisateur de l'activer ou non lui-même, on retiendra le fait d'avoir une case à cocher sur la carte, en bas, centrée, avec le label "Filtrer avec la carte".

**Comment by camillemonchicourt** [comment]
OK fonctionnel avec la version 2.61.1 de Geotrek-admin, déployée sur https://gtr3.ecrins-parcnational.fr/search?practices=4

**Comment by camillemonchicourt** [comment]
Fonctionnalité intégrée dans la version 3.1.0, activable ou non avec un paramètre dédié.
Reste à ajouter la possibilité à l'utilisateur de l'activer ou non lui-même, directement avec une case à cocher sur la carte.
