### ISSUE TITLE
Sur le carrousel de randos filles, je vois toujours la rando courante initialisée au milieu du carousel

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#394]
Objectif : quand on arrive sur une page de rando fille d'itinérance, je dois avoir la rando d'avant et la rando d'après accessibles dans le carrousel

**Comment by dtrucs** [comment]
Ça me parait ok.
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/1926041/79baf824-b09c-45ea-98fc-bab9e3f6e2ec)

En revanche je ne sais pas depuis quelle release, je te laisse fermer le ticket @camillemonchicourt
