### ISSUE TITLE
Fiche rando / Ajouter formulaire Signalement

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#407]
FR : Signalement
EN : Report

Sur la page détails, je vois un bouton "Signaler un problème" qui ouvre un formulaire, sous forme de modale.
Pour y accéder, on ajoute un bouton à côté des actions de téléchargement, avec le tooltip "Signaler un problème".

Ajouter un nouveau paramètre ``enable_reports`` (true/false) pour activer ou non l'accès à ce formulaire de signalement.

Ouvre un formulaire permettant de renseigner le problème, le localiser, éventuellement ajouter 1 à 3 photos et de l'envoyer à l'API de Geotrek-admin en post.

Nécessite les typologies de problèmes, à ajouter à l'API Geotrek-admin, avec des routes ``report_activity``, ``report_magnitude``, ``report_category`` et ``report_status`` (tant qu'à y être)

---------------------------

Voir exemple sur https://rando.ecrins-parcnational.fr/trail/atelier-boucle-trail-technique/

![Capture d’écran de 2021-06-03 15-05-37](https://user-images.githubusercontent.com/4418840/120649596-3a1f0680-c47d-11eb-8e5a-4745a93580c2.png)

Le formulaire est posté sur une route POST de Geotrek-admin, donc il faut ajouter un paramètre avec l'URL du Geotrek-admin sur lequel poster le contenu du formulaire (et les éventuelles photos associées)

--------------------------

Pour les développements, on découpe avec une première version intégrant uniquement le formulaire et la localisation. Puis une seconde version, intégrant aussi l'ajout de photos à un signalement.

**Comment by camillemonchicourt** [comment]
Spécification de l'API post dans le document joint (page 5 et 6) : 
[APIv2-spec-ajouts-23-06-21.pdf](https://github.com/GeotrekCE/Geotrek-rando-v3/files/6708305/APIv2-spec-ajouts-23-06-21.pdf)

**Comment by Sylchauf** [comment]
L'API ne fournit pas les headers nécessaire pour effectuer un post cross domain (CORS) sur cette route

![image](https://user-images.githubusercontent.com/5569487/123749603-e7870d80-d8b5-11eb-8578-fecfef20b20d.png)

**Comment by camillemonchicourt** [comment]
Bizarre, car on le fait avec Geotrek-rando v2 : https://rando.ecrins-parcnational.fr/a-pied/autour-des-vigneaux-et-de-grand-parcher/
C'est peut-être sur le serveur de démo que je n'ai pas activé ou autorisé quelque chose ?
Tu peux aussi tenter en te branchant sur notre API de prod : https://geotrek-admin.ecrins-parcnational.fr/api/v2

**Comment by camillemonchicourt** [comment]
Une première version du formulaire de signalement a été mise en place et fonctionne : 

![image](https://user-images.githubusercontent.com/4418840/124291887-5635c680-db55-11eb-980e-3dbada13452f.png)

- Elle est activable ou non avec un paramètre dédié
- Elle utilise le paramètre de l'API pour identifier l'API sur laquelle poster
- Elle n'affiche pas encore de carte pour localiser le problème mais récupère les coordonnées du point de départ comme localisation

Évolutions à apporter : 
- Améliorer design du formulaire
- Améliorer les liste de valeur pour qu'elles se ferment quand une valeur est sélectionnée
- Pouvoir localiser le problème sur la carte (centrée sur la rando et affichant le tracé de celle-ci), permettant d'utiliser la position GPS de l'utilisateur
- Ajouter le texte RGPD en bas du formulaire
- Ajouter la possibilité d'associer des photos au signalement

**Comment by camillemonchicourt** [comment]
Sujet, plutôt lié à Geotrek-admin et sa conf NGINX il me semble et donc plutôt à remonter sur le dépôt GTA.
En lien avec les nombreux tickets sur le sujet comme https://github.com/GeotrekCE/Geotrek-admin/issues/2670 ?
