### ISSUE TITLE
Étapes - Centrage des chiffres sur les markers de la carte si > 9

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#412]
Si j'ai plus de 9 étapes sur une itinérance, le chiffre sur les marqueurs n'est pas centré.

![image](https://user-images.githubusercontent.com/4418840/117623030-9428f680-b173-11eb-98d7-718d63ae9a9c.png)

**Comment by dtrucs** [comment]
Fixé depuis la [v3.13.6](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.13.6)
