### ISSUE TITLE
Ajouter les filtres par étiquettes

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#418]
Si une étiquette est indiquée comme filtrable (``"filter": true``), l'ajouter dynamiquement dans les filtres des randonnées et des sites Outdoor.
Voir la route https://geotrekdemo.ecrins-parcnational.fr/api/v2/label/
Et https://github.com/GeotrekCE/Geotrek-admin/issues/2362#issuecomment-713109905

- On affiche autant de filtres dynamiques qu'il y a d'étiquettes filtrables
- Le filtre a pour label le nom de l'étiquette et pour valeur oui/non (sous forme de liste déroulante ?) ou plutôt utiliser uniquement le picto comme dans Geotrek-rando v2 ?
![image](https://user-images.githubusercontent.com/4418840/134371704-b8f65d92-3c33-4470-b361-92dc7d21806b.png)

**Comment by Chatewgne** [comment]
Actuellement, il semble que l'ajout d'une **nouvelle** étiquette sur un itinéraire cause une erreur 500 temporaire sur Rando v3 lorsqu'on se rend sur la page détail de cet itinéraire :

```
nodeserver_1  | TypeError: Cannot read properties of undefined (reading 'id')
nodeserver_1  |     at /app/src/.next/server/chunks/3677.js:707:83
nodeserver_1  |     at Array.map (<anonymous>)
nodeserver_1  |     at /app/src/.next/server/chunks/3677.js:706:80
nodeserver_1  |     at Object.Ja [as useMemo] (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:27:240)
nodeserver_1  |     at exports.useMemo (/app/node_modules/react/cjs/react.production.min.js:23:113)
nodeserver_1  |     at DetailsUIWithoutContext (/app/src/.next/server/chunks/3677.js:534:39)
nodeserver_1  |     at d (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
nodeserver_1  |     at bb (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
nodeserver_1  |     at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
nodeserver_1  |     at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
```

Cela semble lié au cache car si je down/up l'application, le problème disparaît

**Comment by camillemonchicourt** [comment]
Je n'ai pas le soucis sur Rando Écrins (https://rando.ecrins-parcnational.fr/trek/980102-Le-lac-de-Vallonpierre).

Mais on vient de voir un soucis important avec le cache Node.js sur plusieurs instances (PNC et PNV), évoqué ici : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/460

Pour le confirmer on a sorti une version de test (https://github.com/GeotrekCE/Geotrek-rando-v3/pkgs/container/geotrek-rando-v3%2Fgeotrek-rando-staging/11118734?tag=v3.5.3-beta1), permettant de désactiver le cache intégrant cette PR : https://github.com/GeotrekCE/Geotrek-rando-v3/pull/529)

Pas encore de solution pour le cache, car on n'a pas encore identifié où se situait le soucis, potentiellement un problème lié au fait que node-wretch a un soucis identifié quand une route renvoie un résultat supérieur à 1 Mo.

**Comment by Chatewgne** [comment]
D'accord !

Je trouve ça pratique d'avoir une option pour choisir de désactiver le cache

(Il faudrait rajouter le settings dans la documentation, si il est gardé dans une release "normale" https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/knowledge/caching.md#nodejs-application-cache)

**Comment by camillemonchicourt** [comment]
Oui oui on gardera le paramètre dans la prochaine release et on le documentera. Là c'est un test pour identifier le soucis du cache Node.js.
Bon, sans le cache ça rame, donc pas souhaitable en prod, mais utile pour des tests.
On a commencé à réfléchir et faire quelques tests de mettre du cache au niveau de l'API pour certaines routes particulièrement longues comme celle des "thèmes", mais à creuser plus tard.

Là le plus urgent est de voir pourquoi le cache Node.js bugge dans certains cas.
2 solutions sont envisagées : remplacer le cache géré par node-wretch par un cache NGINX ou Redis.

**Comment by camillemonchicourt** [comment]
Dans la version actuelle, on ne peut pas interroger l'API pour connaitre les objets qui ne sont pas associés à une étiquette. Donc on garde un filtre simple comme ceux existant (Pas de filtre sur l'étiquette | Objets ayant l'étiquette associée).

Un développement est en cours au niveau de l'API pour permettre ce 3° état (Objets non associés à une étiquette) avec l'ajout d'un filtre ``only_filters`` sur les routes /trek et /outdoor_site.

Pour le moment les filtres par étiquette ne s'appuient pas sur le fichier de configuration des filtres (https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/config/filter.json).
A voir pour harmoniser.

Concernant les filtres à afficher au niveau de la recherche, il ne faut afficher que ceux qui sont utilisables en temps que filtre (``"filter": true`` dans la route ``label``). 
Pour faciliter la récupération des étiquettes utilisables en filtre, un paramètre de filtre ``only_filters`` est en cours d'ajout : https://github.com/GeotrekCE/Geotrek-admin/pull/3002.

Les étiquettes à afficher dans les filtres doivent être filtrées par portail (si renseigné dans la conf) comme les autres filtres.
Le récupération des filtres utilisables en tant que filtre, doit être mise en cache par Geotrek-rando-v3 car leur récupération au niveau de l'API peut être un peu lourde (car elle vérifie si ils sont utilisés par différentes catégories d'objets, comme les thèmes).
Cependant les étiquettes à utiliser en tant que filtre peuvent être moins nombreuses que les étiquettes à afficher dans les fiches détails (si une étiquette est associée à un objet mais n'est pas utilisable en tant que filtre, donc avec la propriété ``"filter": false``).

**Comment by camillemonchicourt** [comment]
Fait dans la version 3.8.0 : 
![Capture d’écran de 2022-04-08 19-18-16](https://user-images.githubusercontent.com/4418840/162491425-cffa4a11-8849-4fb3-a856-4e71dc7507a4.png)

Mais uniquement sur les randonnées et pas les sites Outdoor pour le moment, car le fait que le filtre ait le même nom dans l'API posait un soucis. 
Quand on activant une étiquette dans les filtres des randonnées, cela l'activait aussi dans les filtres des sites Outdoor.
A creuser.

A voir aussi pour pouvoir activer ou désactiver une étiquette, pour pouvoir filtrer sur les contenus qui n'ont pas l'étiquette associée, grâce au nouveau filtre sur l'API ``labels_exclude``. 
Actuellement, on ne peut peut filtrer que les objets auxquels sont associés une étiquette mais pas l'inverse.
Ainsi si on une étiquette "Dans le cœur du parc", on peut lister les randos dans le coeur du parc, mais pas celles qui ne sont pas dans le coeur du parc, alors que c'est bien plus utile. :-)

**Comment by camillemonchicourt** [comment]
La possibilité d'exclure une étiquette dans les filtres des randos a été intégré dans la 3.9.0.

Reste à voir : Appliquer les filtres par étiquettes sur les sites Outdoor.
