### ISSUE TITLE
ShouldDisplayFavorite : false in header.json not working

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando-v3#420]
Release : latest 

Sur ce site : https://rando-pnra.openig.org/ J'ai bien paramétré dans le header.json la variable "shouldDisplayFavorite": false, 

mais j'ai quand même ceci qui apparaît : 
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/45095227/120448375-ce10a580-c38b-11eb-9339-15e47d1607a0.png">

J'étais sûr que c'était ici qu'on faisait le paramétrage, je suppose que je me suis trompé ?

**Comment by camillemonchicourt** [comment]
Le paramètre ``shouldDisplayFavorite`` c'est autre chose. C'est pour définir si on affiche ou pas le bouton "Favoris" dans le Header, sachant que celui-ci n'est pas encore fonctionnel (https://github.com/GeotrekCE/Geotrek-rando-v3/issues/388).

Le bloc que tu indiques est un exemple de customisation du bloc HTML de la Home, que tu peux mettre, adapter ou supprimer dans ta customisation de la Home. Voir exemple dans https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/customization/html/homeTop.html

**Comment by mviadere-openig** [comment]
Ok, merci pour la précision.
