### ISSUE TITLE
3.0 - Problème de référencement

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#422]
Après analyse de comment se passe le référencement du premier portail Geotrek-rando-v3 déployé en production : https://rando.parc-grands-causses.fr/ 

Pour cela, je regarde comment Google indexe le site : https://www.google.com/search?q=site%3Ahttps%3A%2F%2Frando.parc-grands-causses.fr&oq=site%3Ahttps%3A%2F%2Frando.parc-grands-causses.fr&aqs=chrome..69i57j69i59j69i58.8259j0j9&client=ubuntu&sourceid=chrome&ie=UTF-8

De nombreuses pages sont indexées avec une URL qui contient que leur ID, sans leur nom.
Exemple : https://rando.parc-grands-causses.fr/service/13590- 
Ces URL fonctionnent mais ne sont pas bonnes. Cela va créer du contenu dupliqué, ces pages n'ont pas de "title".
Pour cette même page, la bonne URL à laquelle on accède en naviguant dans le portail est https://rando.parc-grands-causses.fr/service/14253-Carpe-Diem 

J'ai aussi noté que certaines pages sont indexées avec leur nom en anglais, mais renvoient vers la version française du contenu, avec une URL mélangeant version française de leur structure mais titre en anglais : https://www.google.com/search?q=site%3Ahttps%3A%2F%2Frando.parc-grands-causses.fr%2Ftrek%2F20-&oq=site%3Ahttps%3A%2F%2Frando.parc-grands-causses.fr%2Ftrek%2F20-&aqs=chrome..69i57j69i59j69i58.1386j0j9&client=ubuntu&sourceid=chrome&ie=UTF-8

PS : Je n'arrive pas à charger le sitemap.xml de ce portail Geotrek-rando-v3, il doit être trop lourd à charger ? https://rando.parc-grands-causses.fr/sitemap.xml

**Comment by mviadere-openig** [comment]
Merci pour ces informations Camille, si il  y a quelque chose que je puisse faire de mon côté, n'hésites pas à me le préciser.

**Comment by camillemonchicourt** [comment]
Le problème semble venir du fait que le PNRGC a de nombreux contenus touristiques qui sont disponibles en français correctement, mais ils sont aussi publiés en anglais, mais sans NOM. Parfois dans description ni résumé.
Voir https://siglr-geotrek-pnrgca.ataraxie.fr/api/v2/touristiccontent/?language=en&page=1&page_size=10

C'est le fait qu'ils n'aient pas de nom en anglais qui pose soucis, fait planter la génération dynamique du sitemap, et créé des URL avec seulement l'ID vu qu'elles n'ont pas de titres.

Le problème vient donc du contenu et de l'API et non pas de Geotrek-rando.
Cependant, pour éviter que le sitemap plante dans ce genre de cas, le cas où un objet n'a pas de nom a été géré.

**Comment by mviadere-openig** [comment]
Merci pour l'information  @camillemonchicourt. 

Du coup le mieux à faire pour le moment c'est de désactiver la version anglaise du site, ou bien supprimer dans le parser.py la remontée des contenus en anglais (chose que je ne suis pas sûr de faire correctement) ?

**Comment by camillemonchicourt** [comment]
Si vous avez des contenus qui sont vraiment en anglais et complets, ça serait dommage de désactiver la version anglaise.
Le mieux serait de corriger votre parser, ou de dépublier les contenus touristiques en anglais incomplets.
On peut aussi imaginer travailler sur l'API pour qu'elles ne renvoient pas des contenus publiés si ils n'ont pas au moins un titre/nom dans la langue demandée.

**Comment by camillemonchicourt** [comment]
OK, les évolutions apportées dans la version 3.0.4 ont permis de faire fonctionner le Sitemap, malgré les contenus touristiques renvoyés dans titre.
Il est donc de nouveau accessible : https://rando.parc-grands-causses.fr/sitemap.xml
Il a été déclaré dans la Google Search Console, après avoir créé une propriété et l'avoir renseigné dans le paramètre ``googleSiteVerificationToken`` du fichier ``config/global.json``.

On va voir comment ça réagit dans les prochains jours.

A noter, en regardant le sitemap, on voit que les URL ont été simplifiées et les accents et apostrophes remplacés.
Mais il reste des caractères spéciaux dans les URL.
Quelques exemples : 
- https://rando.parc-grands-causses.fr/en/service/47091-Bed-and-Breakfast-%C2%AB-La-Maison-de-Marie-%C2%BB
- https://rando.parc-grands-causses.fr/trek/25-La-Quille,-montagne-des-Anglais-N%C2%B03-VTT

Et il semblerait que les accents ont été remplacés uniquement dans les URL des treks et services. Mais pas des pages statiques (/information). Exemple : https://gtr3.ecrins-parcnational.fr/information/18-Acc%C3%A8s-&-Transports

**Comment by camillemonchicourt** [comment]
J'ai identifié un soucis.
Cette page renvoie maintenant une 404 : https://rando.parc-grands-causses.fr/service/13405-Les-G%C3%AEtes-d'Yvette---La-Maison-de-Peyreleau--Appt-4/5-pers.-(Informations-2021-non-communiqu%C3%A9es)
Alors qu'elle remonte dans la recherche : https://rando.parc-grands-causses.fr/search?text=yvette (4° résultat)

Idem pour https://rando.parc-grands-causses.fr/service/14055-Crazy-e-Bike---Location-de-VTT-/-VTC-%C3%A9lectriques
Qui remonte aussi dans la recherche : https://rando.parc-grands-causses.fr/search?text=crazy

**Comment by camillemonchicourt** [comment]
Les problèmes des URL du PNRGC qui arrivaient à des 404 étaient dues au fait que les noms de ces services (contenus touristiques) ont un ``/`` dans leur nom, ce qui pose des soucis d'URL.
Cela a été contourné en supprimant les ``/`` dans les URL.
Idéalement ils pourraient être échappés au niveau de Geotrek-admin et de son API.
