### ISSUE TITLE
Agrandissement des images / Améliorations de leur affichage

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#454]
Depuis la version 3.1.0 il est possible d'agrandir les images des pages Recherche et Détail (https://github.com/GeotrekCE/Geotrek-rando-v3/issues/403).
Les images sont affichées en plein écran, en mode couverture : 

![image](https://user-images.githubusercontent.com/4418840/126133068-54ee73e2-71aa-4f56-9714-0a04e154b1fe.png)

Le résultat est joli et épuré. Cependant selon leur taille d'origine et le format de l'écran, elles peuvent donc être rognées.

Il est donc proposé d'ajouter un paramètre permettant d'afficher les images en cover (comme actuellement) donc prenant tout l'écran mais étant rognées, ou sans être rognées mais avec des bandes noires en haut, en bas ou à gauche à droite selon le format de l'image.

A voir aussi si il faut revoir la méthode d'agrandissement car le "Plein écran" n'est pas autorisé sur iOS (https://github.com/GeotrekCE/Geotrek-rando-v3/issues/444).

Enfin il serait utile de pouvoir définir une taille minimum au niveau de Geotrek-admin, pour avoir des images de meilleure qualité/dimension, mais aussi de redimensionner celles qui sont chargées en haute définition et donc trop lourdes par rapport à leur usage.

**Comment by dtrucs** [comment]
L'agrandissement n'est plus rognée depuis la version [3.13.0](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.13.0).

Il reste à définir une alternative pour les appareil IOS

**Comment by camillemonchicourt** [comment]
Oui avec un arrière-plan noir, c'est mieux ça : 

![image](https://user-images.githubusercontent.com/4418840/221544872-6977accf-6ffc-4825-b4d9-f8e7ae40e4cb.png)

Sur mobile, ça ne coupe plus non plus : 

![image](https://user-images.githubusercontent.com/4418840/221545148-6003e9fa-28c8-4ca3-801d-0232083b59f1.png)

Reste à voir sur iOS qui bloque le passage en plein écran, autre sujet.
