### ISSUE TITLE
(1) Fiche Contenu Touristique - Pblme d'affichage de la tooltip

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-rando-v3#455]
Sur la fiche d'un Contenu Touristique, au survol et au clique sur l'icône du Contenu Touristique sur la carte -> problème d’affichage de la tooltip qui ne se charge pas.

Message d'erreur de la console du navigateur : No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by camillemonchicourt** [comment]
OK je viens de reproduire sur https://rando.ecrins-parcnational.fr/service/2395-A-la-decouverte-des-plantes-comestibles

Ce n'est pas un problème de CORS mais le fait qu'il appelle pas la route de l'API avec le bon identifiant de l'objet.
Il appelle l'objet 0 au lieu du 2395 : 

```
XHR GET https://geotrek-admin.ecrins-parcnational.fr/api/v2/touristiccontent/0/?language=fr&fields=id,name,cities,attachments
CORS Missing Allow Origin

Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://geotrek-admin.ecrins-parcnational.fr/api/v2/touristiccontent/0/?language=fr&fields=id%2Cname%2Ccities%2Cattachments. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.
```

En effet cette route ne renvoie logiquement rien, car le CT 0 n'existe pas : https://geotrek-admin.ecrins-parcnational.fr/api/v2/touristiccontent/0/?language=fr&fields=id,name,cities,attachments
En passant le bon identifiant dans la route cela fonctionne : https://geotrek-admin.ecrins-parcnational.fr/api/v2/touristiccontent/2395/?language=fr&fields=id,name,cities,attachments

Dans tous les cas, afficher une tooltip sur le point de l'objet dans sa fiche détail n'est pas forcément très utile ni pertinent. 
On ne le fait pas dans les fiches des randos.
