### ISSUE TITLE
Fiches détail - Déplacer l'ancre "Présentation"

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#457]
Mettre l'ancre de Présentation sur image, et pas le titre, pour être directement positionné sur "Présentation" à l'ouverture de la page.

**Comment by Sylchauf** [comment]
Le système de scroll est complexe et la modification de ce comportement entraîne des erreurs de calculs (hauteur des images dynamique) sur le système de scroll et de positionnement. La mise en place de cette modification est coûteuse en temps

**Comment by dtrucs** [comment]
La refacto des pages détails semble avoir corrigé ce problème
