### ISSUE TITLE
Cookies / Ajout d'un message d'acceptation/refus

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#459]
Mettre en place un module d'acceptation/refus des cookies, en conformité aux directives de la CNIL qui rend cela obligatoire depuis le 31/03/2021 : https://www.cnil.fr/fr/nouvelles-regles-cookies-et-autres-traceurs-bilan-accompagnement-cnil-actions-a-venir

Voir si on utilise OREJIME : https://orejime.empreintedigitale.fr/, qui répond aux "contraintes" d'accessibilités pour les personnes en situation de handicap.

Permettre à l'utilisateur du portail de choisir de refuser ou d'accepter les cookies Google analytics, avec la possibilité de revenir sur ces choix pour être conforme au regard de la CNIL (point 16 : https://www.cnil.fr/fr/questions-reponses-lignes-directrices-modificatives-et-recommandation-cookies-traceurs).

**Comment by babastienne** [comment]
Nous avons été relancés aujourd'hui par un territoire qui souhaiterai que Geotrek-Rando respecte le cadre légal d'acceptation ou de refus des cookies à partir du moment où Geotrek en utilise (dans la cadre de GA ou du widget Météo il me semble).

A-t-on des informations supplémentaires sur la possibilité d'ajouter cette feature dans le backlog ?

**Comment by camillemonchicourt** [comment]
Oui ce serait intéressant.
- Ajouter la possibilité de mettre en place un message d'acceptation des cookies (activable ou non avec un paramètre)
- Si l'utilisateur coche non, alors ne pas utiliser les cookies
- Vérifier ce qui utilise les cookies actuellement
- Pas certain que la v4 de GA utilisée dans GTR3 soit incompatible avec la législation en vigueur sur le sujet et nécessite une acceptation des utilisateurs 
- Intégrer la possibilité d'utiliser Matomo à la place de GA, qui ne nécessite pas d'acceptation de l'utilisateur à ma connaissance et est plus conforme avec la législation européenne

Rien de prévu concrètement sur le sujet actuellement.

**Comment by babastienne** [comment]
Merci pour ton retour @camillemonchicourt. 
Concernant l'intégration de Matomo dans GTR3, nous allons effectuer le développement car le besoin se fait ressentir de plus en plus auprès de différents acteurs de la communauté.

Pour le reste, à ma connaissance les cookies sont utilisés aujourd'hui uniquement pour le widget Météo et GA. Je pense qu'il n'y a que GA qui nécessite un bandeau d'acceptation de cookies pour le moment. A voir à l'avenir si GA continue d'être très utilisé ou non peut-être ...

**Comment by camillemonchicourt** [comment]
OK oui pour Matomo, ça serait une bonne chose.

Pour le widget météo, c'est dommage qu'un petit truc comme ça utilise des cookies et je vois pas pourquoi.

Pour GA, OK, je pensais que la V4 ne nécessitait pas d'acceptation utilisateurs mais je n'ai pas creusé le sujet.

Merci.

**Comment by Lilya-NS** [comment]
Inclure une conditions d'activation du consentement par défaut si :
- il y a un Google Analytics ID 
- l'activation de la demande de consentement est "true"

**Comment by dtrucs** [comment]
Fonctionnalité intégrée depuis la release [v3.15.4](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.15.4).

L'implémentation des scripts tiers changent. Si vous souhaitez être en conformité avec le RGPD, veuillez suivre la [documentation](https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization-scripts-GDPR.md#GDPR) à ce propos.

Le plus gros changement vient avec l'intégration de Google Analytics qui était renseigné avec la clé `googleAnalyticsId` dans `customization/config/global.json`.
Si vous faites la mise à jour de cette version **sans rien modifier dans votre configuration**, Google Analytics ne se chargera plus du tout. 
Il convient de **définir l'url de votre page de politique de confidentialité** via la clé `privacyPolicyLink` dans `customization/config/global.json`, ce qui permettra de débloquer la fenêtre de consentement présentant tous les scripts ayant des défauts de conformités.

Si vous n'êtes pas situés dans un pays UE et que vous souhaitez utiliser Google Analytics sans passer par un recueil de consentement, il convient alors de définir `googleAnalyticsId` à `null` dans `customization/config/global.json` et de déclarer des balises `<script>` sans les attributs `type`, `data-name` et `data-type` dans le fichier `scriptsHeader.html` de `customization/config/html/`.

**Comment by camillemonchicourt** [comment]
Fait dans la 3.15.4.
- Si vous utilisez Google Analytics, l'outil sera activé automatiquement, mais ne sera pas fonctionnel (et donc ne comptera plus vos visiteurs) tant que vous n'aurez pas renseigné le nouveau paramètre `privacyPolicyLink` avec une URL renvoyant vers une page de mentions légales ou autre. Par ailleurs, une fois activé, les utilisateurs refusant la collecte d'informations ne seront plus comptabilisés dans vos suivi des visites de Google Analytics
- Si vous utilisez Matomo (ou autres solutions respectant les directives de la CNIL et bénéficiant ainsi d'une exemption) pas besoin de mettre en place l'outil de consentement des cookies et vos statistiques de suivi des visites ne sera pas affecté par une acceptation ou refus de ceux-ci - https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/cookies-solutions-pour-les-outils-de-mesure-daudience
