### ISSUE TITLE
Override CSS - Prise en compte partielle du fichier

### ISSUE THREAD

**Issue by jcanto05000** [GeotrekCE/Geotrek-rando-v3#464]
Quand on travail sur les fichiers homeBottom.html et homeTop.html, le fichier style.css n'est que partiellement pris en compte.

Sur l'exemple : http://geotrekv3.lenaturographe.fr
Nous avons le fichier webpack://_N_E/../customization/theme/style.css :
![image](https://user-images.githubusercontent.com/12727510/134020020-0ad0e928-b8e1-47a6-b1b4-57d014630d43.png)

Nous avons ici la ligne #bottom{ background: #333; } qui est bien en compte.
Cependant, la ligne .row-flex .col-md-7 { background: red; } n'est pas reconnu/utilisé par le navigateur.

On se retrouve dans l'obligation d'ajouter une balise style dans les fichiers HTML pour pouvoir correctement personnaliser nos blocs.

**Comment by Sylchauf** [comment]
Bonjour,

Pouvez vous fournir un dépot github reproductible avec une image spécifiant la zone que vous souhaitez surcharger svp ?

Le selecteur `.row-flex .col-md-7` me parait trop générique pour cibler une zone précise

**Comment by camillemonchicourt** [comment]
C'est pas plutôt ``.flex-row`` qu'il faut utiliser ? 
Voir https://v2.tailwindcss.com/docs/flex-direction

**Comment by jcanto05000** [comment]
Salut ! 

Je viens de bosser sur le projet.
J'ai donc mis à jour la version de Geotrek-rando-v3-installer en 2.0.1.

Sans changer mon html ni mon css, cela fonctionne maintenant. 
Le problème semble donc être résolu avec les dernières versions de Geotrek.
