### ISSUE TITLE
3.2.0 - Des pages statiques ne s'affichent plus

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#479]
En production : https://rando.ecrins-parcnational.fr/information/6-A-savoir
Sur le démo : https://gtr3demo.ecrins-parcnational.fr/information/3-Biodiv-Ecrins
Et https://gtr3demo.ecrins-parcnational.fr/en/information/4-Ecrins-national-Park

**Comment by Sylchauf** [comment]
Le système de cache actuel utilise les .clone() de node-fetch qui est limité à des réponses API de 16Kb maximum

https://github.com/node-fetch/node-fetch/blob/3b99832e2331908631a70dd07fccdda8e850ec94/docs/v2-LIMITS.md

Il faut remplacer ou désactiver le système de cache
