### ISSUE TITLE
Page home autonome et geotrek-rando dans sous repertoire

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-rando-v3#492]
Dans la v2 de Geotrek-rando nous avions réussi à rendre disponible la carte principale dans un sous répertoire de notre site web : https://www.destination-parc-monts-ardeche.fr/decouvrir/
Cela nous laissait la possibilité d'avoir une page home autonome en HTML.
Je n'ai pas réussi à reproduire cela avec la V3.
Est-ce envisageable techniquement ?

**Comment by camillemonchicourt** [comment]
Oui dans la V2 la home était une page HTML affichée en modale par dessus le reste du portail.
Dans la v3, la homepage est une vraie page dédiée du portail avec une structure définie, customisable avec des paramètres et des zones de HTML libres.
C'est plus puissant, plus simple à déployer et customiser, mieux référencer, et permet de mieux interagir avec le reste du portail et de son contenu.

Par contre ajouter une autre page HTML et créer un sous-dossier, je ne sais pas trop si c'est possible et je ne vois pas bien quel serait l'intérêt.
Je conseille fortement d'utiliser plutôt la Homepage actuelle.
Mais il est certainement possible de mettre tout le portail sur un sous-dossier en le spécifiant dans la conf NGINX et de créer une autre page HTML pour la Home accessible à la racine. Et d'utiliser la paramètre existant permettant de désactiver la Homepage de Geotrek-rando v3.

**Comment by pnrma** [comment]
Merci pour la réponse. L'intérêt pour nous serait d'utiliser un CMS type wordpress pour toute la partie "éditoriale" et conserver la partie carte et fiches randos dans Geotrek.
Je préciserai ici la méthode si je parviens à le faire avec Geotrek-rando V3.

**Comment by camillemonchicourt** [comment]
Plus besoin d'utiliser un CMS externe depuis la version 3.19 de Geotrek-rando et 2.104 Geotrek-admin, car on peut désormais aller bien plus loin au niveau du menu et des pages statiques de Geotrek-rando !

Voir : https://groups.google.com/u/1/g/geotrek-fr/c/wtZT6Uu-bd8

Resterait à voir pour faciliter la gestion et enrichir la Home.
