### ISSUE TITLE
Comment changer le titre de la page d'accueil de Geotrek ?

### ISSUE THREAD

**Issue by blaisegeo** [GeotrekCE/Geotrek-rando-v3#513]
Bonjour;
Est-ce bien indiqué dans la doc et je serais passé à côté, j'ai pourtant bien cherché, mais pas trouvé comment changer titre de la page d'accueil de Geotrek.
Par défaut, ce titre est: "Geotrek-Rando". Il est affiché en haut à gauche de la page d'accueil, juste à côté du logo. C''est aussi le nom de l'onglet lorsqu'on a plusieurs onglets ouverts dans un navigateur internet.
Dans la doc de "customization", il y a une clé appelée "applicationName" dans le fichier config/global.json. Elle est définie comme "application name appearing on PWA". J'ai beau essayer de la changer puis de relancer docker, l'application affiche toujours "Geotrek-rando" en haut à gauche de la page d'accueil.
Merci d'avance si vous pouvez m'indiquer comment changer ce titre.

**Comment by camillemonchicourt** [comment]
Oui c'est dans les surcouches de traduction.
Indiqué ici dans la documentation : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization.md#translations

Voir https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/translations/fr.json#L11

``applicationName`` est utilisé pour la PWA et peut-être pour le <title> des métadonnées, mais là j'ai un doute si c'est le paramètre ou la clé de traduction qui est utilisé.

**Comment by blaisegeo** [comment]
Merci beaucoup Camille, désolé pour le bruit, je ferme l'issue.
