### ISSUE TITLE
[Footer] Pouvoir insérer des liens FlatPages dans la configuration des liens du footer 

### ISSUE THREAD

**Issue by dtrucs** [GeotrekCE/Geotrek-rando-v3#516]
Une fonctionnalité qui pourrait être intéressante serait de pouvoir mettre des liens flatpages directement dans la config `footer.json`.

Rien ne l'empêche de le faire actuellement cependant cela pose des problématiques avec l'internationalisation.

Imaginons que dans mon `links` de  `footer.json` j'ai l'entrée suivante :

```json
{
   "label": "footer.prettyPage",
   "url": "https://example.com/information/1-ma-belle-page"
}
```

Je vais bien pouvoir gérer ma traduction grace à ma clé.
Si je navigue depuis le site en FR, et que je clique sur le lien j'arrive bien dans "ma belle page"
Si je navigue depuis le site en EN, en cliquant dessus je ne vais pas atterir vers la page traduite `https://example.com/en/information/1-my-pretty-page` mais obtenir une 404.

J'ai trouvé une solution semi satisfaisante en omettant le slug derrière l'ID de la page ⬇️ 

```json
{
   "label": "footer.prettyPage",
   "url": "https://example.com/information/1"
}
```
Si je navigue depuis le site en FR, et que je clique sur le lien je suis redirigé vers "https://example.com/information/1-ma-belle-page"
Si je navigue depuis le site en EN, et que je clique sur le lien je suis redirigé vers "https://example.com/en/information/1-my-pretty-page"

Ça marche mais ça reste un peu de la bidouille, et ce n'est pas intuitif.
Que pensez-vous de pouvoir configurer le JSON en proposant un ID en plus du choix label/url et l'application ira chercher les label/url de ces id ?   
Comme par exemple :

```json
{
   "links": [
       {
           "label": "footer.geotrek",
           "url": "https://geotrek.fr/"
       }, 
       {
           "id": 1,
       },
       {
           "label": "footer.example",
           "url": "https://example.fr/"
       }
   ]
}
```
J'ai mis `id` mais cela peut être `pageID` ou une autre structure.
Si nous sommes d'accord sur la structure du JSON, je peux proposer une PR

**Comment by camillemonchicourt** [comment]
Oui intéressant. Si ça renvoie que vers des pages statiques d'information, alors en effet c'est bien de préciser, je dirai "informationID".

**Comment by camillemonchicourt** [comment]
Merci, intégré dans la 3.5.1.
