### ISSUE TITLE
La liste des pratiques de randonnées de la page d'accueil ne sont pas ordonnables

### ISSUE THREAD

**Issue by dtrucs** [GeotrekCE/Geotrek-rando-v3#539]
Si on définit les `order` des pratiques depuis le backoffice `/admin/trekking/practice/` , il ne sont pas pris en considération depuis la page d'accueil.

**Comment by camillemonchicourt** [comment]
Oui bien vu, ça serait bien de prendre en compte l'ordre.

**Comment by camillemonchicourt** [comment]
Fixé dans la 3.5.4
