### ISSUE TITLE
Problème affichage pas à pas si gras/italique V3

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-rando-v3#540]
Dans les descriptions, on indique le nom des panneaux en gras et le balisage en italique. Dans la V3, dès que l'on met en forme avec les puces pour la numérotation sur la carte, il y a systématiquement un problème de mise en page si le texte contient du gras ou de l'italique (même en faisant un nettoyage html avec l'outil): 
![image](https://user-images.githubusercontent.com/19687397/146954107-a4c7262c-9815-4044-8342-5e440030fad9.png)

**Comment by camillemonchicourt** [comment]
Je transfère ici cette issue car elle avait été mis dans la dépôt de Geotrek-rando v1 et v2 (https://github.com/GeotrekCE/Geotrek-rando).
Je me disais bien que je l'avais vue passée, mais ne la trouvait plus.

La voici dans le bon dépôt et voici le PR qui corrige ce soucis : https://github.com/GeotrekCE/Geotrek-rando-v3/pull/537

**Comment by camillemonchicourt** [comment]
Fixé dans la 3.5.4
