### ISSUE TITLE
Distinguer la page d'accueil

### ISSUE THREAD

**Issue by MNourrisson** [GeotrekCE/Geotrek-rando-v3#543]
Bonjour,

Je suis en train d'essayer de transposer la mise en page que j'avais réalisée sur la v2 sur cette nouvelle version. Et je n'ai pas trouvé de classe CSS permettant de distinguer la page d'accueil des autres. Et la zone de code personnalisée arrive trop bas par rapport à l'élément que je souhaite cibler. 
Je n'ai rien lu là dessus dans la doc.

Existe t-il un moyen de repérer la home ? Est-t 'il possible de rajouter une classe via un des fichiers de custom ?
Merci.

**Comment by camillemonchicourt** [comment]
Pour faciliter la surcouche CSS des différentes pages, on a fait en sorte d'ajouter des ID aux différents blocs de la page d'accueil, de la page recherche, des pages détails.
Voir par exemple cette évolution : https://github.com/GeotrekCE/Geotrek-rando-v3/commit/d96663ce36c71a5d901b63717c55696e932fdd00#diff-821ba70c966167ffcdf14fb9e761cb1ac7d8e7b2647649672e92402f1585d0ce

Ainsi on peut isole le header, la bannière, les blocs de suggestion, le footer.

Actuellement tu ne peut utiliser que le fichier CSS de surcouche pour styler les différents objets.

Est-ce que cela répond à ton besoin ?

**Comment by MNourrisson** [comment]
Bonjour,
merci de ton retour. Oui c'est exactement ce que je cherchais. Je n'avais pas vu que cela avait été ajouté dans la dernière release.

**Comment by camillemonchicourt** [comment]
Mais ça vaudrait néanmoins le coup d'avoir un ID encore plus global sur toute la home, toute la page recherche, toutes les pages détails.

**Comment by MNourrisson** [comment]
Bonjour,
je viens de mettre à jour sur la dernière version et effectivement un id au niveau de la balise body serait plus pratique.

**Comment by camillemonchicourt** [comment]
Oui j'imagine que c'est à faire dans ce fichier : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/develop/frontend/src/components/pages/home/Home.tsx
Mais je ne sais pas où ni comment.
Toute contribution est bienvenue.

**Comment by camillemonchicourt** [comment]
Fait avec https://github.com/GeotrekCE/Geotrek-rando-v3/pull/695, en ajoutant des id pour pouvoir customiser le CSS :
- Pour la home : ajout d'un id "home_container"
- Pour la page Recherche : "search_container"
- Pour la page Détails : "details_container"

**Comment by camillemonchicourt** [comment]
Fait dans la 3.9.0, en ajoutant aussi un ID sur les pages statiques.
