### ISSUE TITLE
Problème de déclaration Font Personnalisé

### ISSUE THREAD

**Issue by CharlesUk** [GeotrekCE/Geotrek-rando-v3#548]
Bonjour,
Je rencontre un problème pour utiliser des polices personnalisé sur Geotrek.
Je veux utiliser une police de Google Font. 
J'ai essayer de la charger à distance via le fichier de CSS ou en uploadant le fichier sur le serveur dans un répertoire spécifique.
Cela ne fonctionne pas, je met une capture d'écran en pièce-jointe de la déclaration de la font dans le fichier CSS lié à la page.
Je ne vois pas d'où peut provenir le problème.
![Capture d’écran 2022-01-24 à 10 27 56](https://user-images.githubusercontent.com/52503238/150759043-aa305c6f-7572-47ab-9330-4ceb783bf594.png)
Merci d'avance
Charles

**Comment by JeanLenormand** [comment]
Bonjour Charles, 

pour surcoucher le css il faut utiliser le fichier /customization/theme/style.css ou alors créer des balise "style" dans les fichiers html.

Le css de GTRv3 a été réalisé avec le framework https://tailwindcss.com/
Mais il semblerait que seulement certains styles aient été importés (cf. https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/tailwind.config.js) car certaines class ne sont pas prises en compte.

Donc sauf erreur de ma part, difficile de charger des styles qui ne sont pas dans ce fichier de conf., comme des familles de police ... 

J'espère que cela pourra t'aider et si quelqu'un a plus d'infos sur l'intégration des classes de Tailwind je suis preneur !

Un autre ticket avait été ouvert sur ce sujet :
https://github.com/GeotrekCE/Geotrek-rando-v3/issues/464

**Comment by CharlesUk** [comment]
Bonjour Jean,
J'ai bien utiliser le fichier style.css que j'ai relié à ma page via le fichier homeTop.html.
Je ne connais pas du tout ce framework mais ne principe cela ne devrait pas gêner l'utilisation du service de Google font ?

**Comment by JeanLenormand** [comment]
Pas sur car je n'ai pas l'impression que les fonts Google aient été importées.

Dans le <head> du html, je ne vois pas de trace d'import des fonts google de type : 
link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine"
Ni dans le fichier de config de Tailwind...

Si on peut avoir plus d'infos sur le sujet, je suis aussi preneur !

**Comment by camillemonchicourt** [comment]
Bonsoir,
dans ce genre de cas, n'hésitez pas à partager la customisation que vous avez fait pour mieux comprendre le contexte et ce qui a été testé exactement.

Je viens de faire quelques tests et cela fonctionne.
Voici les éléments pour importer une police de Google-font : 

- Il semble recommandé d'importer les polices dans le HTML avec la balise ``<link>`` dans le ``<head>`` de la page mais on n'a pas accès à celui-ci
- Il faut donc tout faire dans le fichier de surcouche CSS (``customization/theme/style.css``) avec la méthode ``@import``

Le code fournit par Google font inclut des "quotes" et en effet elles posent le problème que vous avez indiqué car elles semblent échappés par Geotrek-rando-v3.

Exemple si j'ajoute dans mon fichier ``style.css`` : 

```CSS
@import url('https://fonts.googleapis.com/css2?family=Neonderthaw&display=swap');

#header_title{
   font-family: 'Neonderthaw', cursive;
}
```

on voit des soucis d'interprétation des "quotes" qui sont échappés : 

![Capture d’écran de 2022-01-24 23-51-30](https://user-images.githubusercontent.com/4418840/150878289-a252cfac-72a5-4331-90cc-e51e73970fc8.png)

En testant sans les guillemets, cela fonctionne : 

```CSS
@import url(https://fonts.googleapis.com/css2?family=Neonderthaw&display=swap);

#header_title{
   font-family: Neonderthaw, cursive;
}
```

![image](https://user-images.githubusercontent.com/4418840/150878539-5cdc9c42-2ee6-49d4-87d8-f91b9c5ddc94.png)

---------------------------------

Et cela fonctionne bien aussi de télécharger une police et de la charger sur le serveur : 

![image](https://user-images.githubusercontent.com/4418840/150880590-d9dc83a9-5abf-497a-9216-4c93b0eb77c2.png)

Là aussi il faut enlever les "quotes" dans la syntaxe, et j'ai du enlever le paramètre ``format`` qui est conseillé (https://developer.mozilla.org/fr/docs/Web/CSS/@font-face) mais ne semblait pas passer sans "quotes" (à creuser quand même).

Pour cela j'ai chargé le fichier de police dans le dossier ``customization/medias/fonts`` car le dossier ``medias`` est exposé et accessible en http, puis dans mon fichier ``customization/theme/style.css`` :

```CSS
@font-face {
 font-family: RubikBeastly;
 src: url(/medias/fonts/RubikBeastly-Regular.ttf);
}
#banner {
  font-family: RubikBeastly, serif;
}
```

**Comment by camillemonchicourt** [comment]
Concernant cette autre question évoquée dans ce ticket : 

> Le css de GTRv3 a été réalisé avec le framework https://tailwindcss.com/
> Mais il semblerait que seulement certains styles aient été importés (cf. https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/tailwind.config.js) car certaines class ne sont pas prises en compte.

En fait pour le développement de l'application, toutes les classes Tailwind sont disponibles, mais quand on build une image, il va y avoir une purge de toutes les classes Tailwind non utilisées afin d'alléger le CSS. Cela est fait avec PurgeCSS (https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/package.json#L35).

C'est pour ça que pour la surcouche du CSS, il n'est pas possible d'utiliser des classes ou propriétés de Tailwind qui ne sont pas utilisées dans la version par défaut de Geotrek-rando-v3.

**Comment by camillemonchicourt** [comment]
Cette PR fait en sorte de purger le CSS avec les classes et éléments de Tailwind utilisés dans le code de Geotrek-rando, mais aussi ceux éventuellement ajoutés dans la surcouche de la customisation : https://github.com/GeotrekCE/Geotrek-rando-v3/pull/735.
Il sera ainsi possible d'utiliser d'autres éléments de Tailwind dans la surcouche HTML/CSS.
