### ISSUE TITLE
Section HTML dans le footer

### ISSUE THREAD

**Issue by CharlesUk** [GeotrekCE/Geotrek-rando-v3#549]
Bonjour,
J'aimerais savoir s'il est possible de customiser le footer de Geotrek avec une section HTML.
Je souhaite ajouter les logos de partenaires avec des liens qui dirigent vers leurs sites webs mais je ne vois pas comment je peux faire cela avec la documentation.
Merci d'avance
Charles

**Comment by camillemonchicourt** [comment]
Bonsoir,

Ce n'est pas prévu actuellement. 
On ne peut que configurer le contenu du footer avec les éléments prédéfinis et décrits dans la documentation : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization.md

Du coup, pour afficher les financeurs, on les a mis dans le bloc HTML customisable ``homeBottom.html`` : https://rando.ecrins-parcnational.fr

Mais ça serait intéressant de pouvoir aller plus loin dans la customisation du footer.
Toute contribution est bienvenue.

**Comment by dtrucs** [comment]
Encarts disponible depuis la version 3.8.1, voir la documentation à ce sujet https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization.md#html--scripts
