### ISSUE TITLE
Altimetric profile display is too large when small elevation

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#552]
After getting some user feedbacks it appears that when there is treks with small elevation in Geotrek, the display of the altimetric profile in Rando seems misleading.

For example in the capture below, it can give the user the impression that there is a big elevation on the trek while there is in reality only 20 meters of difference between min and max altitude.

![image](https://user-images.githubusercontent.com/16348048/152025168-1c226b38-6f2d-4dcd-81f7-078f60a557e5.png)

In my opinion when there is small elevation the altimetric profile should be either not displayed or flatten. It could be a configuration parameter that would tell Geotrek Rando that when the elevation is under x meters, the Y axe should display at least 100 meters.

**Comment by camillemonchicourt** [comment]
Yes true.
It could be flatten, and/or set a parameter of minimum elevation to display altimetric profiles

**Comment by camillemonchicourt** [comment]
Yes would be an interesting feature.
Maybe let's try to find a shorter setting name. 🤔

**Comment by camillemonchicourt** [comment]
Fait dans la 3.8.0 avec l'ajout d'un paramètre ``minAltitudeDifferenceToDisplayElevationProfile``, à 0 par défaut.
