### ISSUE TITLE
Problème d'accès à la page CONTENUS HORS LIGNE

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#553]
Sur ma production quand j'accède à la page "Contenus hors-ligne" par le menu BURGER, celle-ci est en erreur "Sorry this page is not working properly".
Si je rafraîchis ou accède à la page directement, elle fonctionne bien : https://rando.ecrins-parcnational.fr/offline

J'ai ces erreurs dans la console du navigateur, rien dans les logs Node.js : 

_app.tsx:31 GET https://rando.ecrins-parcnational.fr/api/translations/it 404 (Not Found)
_app.tsx:31 GET https://rando.ecrins-parcnational.fr/api/translations/en 404 (Not Found)
_app.tsx:31 GET https://rando.ecrins-parcnational.fr/api/translations/fr 404 (Not Found)
_app.tsx:69 SyntaxError: Unexpected token < in JSON at position 0

Un soucis avec les traductions de ce que je comprends.

**Comment by camillemonchicourt** [comment]
Pas reproduit sur d'autres instances comme https://rando.parc-grands-causses.fr/offline
Je comprends vraiment pas pourquoi il cherche les fichiers de traduction sur la mauvaise URL https://rando.ecrins-parcnational.fr/api/translations/fr quand on accède à la page CONTENUS HORS LIGNE par le burger sur notre serveur de production...

**Comment by Lilya-NS** [comment]
Hello, Julien vient de vérifier sur votre serveur si le code était bien à jour et il semblerait que non ? Est-ce que vous pouvez y jeter un oeil ?

**Comment by JordaneNS** [comment]
@camillemonchicourt la bonne PR à merger/tester est celle-ci [(https://github.com/GeotrekCE/Geotrek-rando-v3/pull/721)](https://github.com/GeotrekCE/Geotrek-rando-v3/pull/721). C'est celle que nous avons actuellement sur notre serveur de démo et qui règle le bug que nous avions aussi de notre côté.

**Comment by camillemonchicourt** [comment]
Oui c'est bien cette PR qui est dans ``develop`` et je viens de déployer ``develop`` en production : https://rando.ecrins-parcnational.fr

**Comment by camillemonchicourt** [comment]
Voici des éléments d'échange avec @dtrucs : 

> Ce fichier est le point d'entrée de l'app : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/pages/_app.tsx#L60
> La problématique est la méthode que je surligne. Chaque fois qu'on charge/hydrate la page, ça appelle cette méthode, ce qui n'est pas optimisé.
> Ligne 66 de ce fichier, il va charge les locales. Il va lire les 2 dossiers de config, les agrège, et sortir un json des langues qu'il fourni dans l'app. Pour de la donnée statique c'est un peu dommage.
> Donc en mode offline, je pense qu'il y a un soucis car il cherche les locales.

**Comment by JordaneNS** [comment]
@camillemonchicourt  @dtrucs Oui j'ai essayé aussi cette piste en ajoutant une condition qui fait que les locales ne sont pas chargées si on est sur la page offline. Le souci de cette méthode, c'est qu'on se retrouve avec un header sur la page offline dont les traductions ne sont plus chargées (donc home.title ...etc). Il faut qu'on trouve une solution pour contourner ce souci ou alors il faudrait uniquement pour la page offline enlever le header avec les traductions mais bon ce n'est pas le plus optimisé.

**Comment by camillemonchicourt** [comment]
En travaillant sur un autre sujet, @dtrucs a identifié des soucis sur le sujet, et proposé une PR qui devrait réglé le soucis : https://github.com/GeotrekCE/Geotrek-rando-v3/pull/727

**Comment by camillemonchicourt** [comment]
Corrigé dans la 3.10.1
