### ISSUE TITLE
Les picto des Thèmes saisis dans le Geotrek Admin ne sont pas remontés dans les filtres de recherche Geotrek Rando

### ISSUE THREAD

**Issue by dtrucs** [GeotrekCE/Geotrek-rando-v3#556]
Bonjour,
Sûrement un oubli, mais dans les filtres de recherche les pictos sont bien remontés sauf pour la section des thèmes.

NB: Quels que soit les filtres seuls les picto en format SVG sont restitués

**Comment by camillemonchicourt** [comment]
Intégré dans la 3.7.0
