### ISSUE TITLE
Pouvoir grouper les types par catégorie sur la HOME (événements touristiques et autres)

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-rando-v3#560]
L'ensemble des types d'animations sont présentés sur la page d'accueil qu'ils aient ou non des contenus associés.

![image](https://user-images.githubusercontent.com/3088650/152882475-9fb7f681-3b00-4782-b34b-1644604a0c7d.png)

Ce serait mieux si on ne pouvait afficher uniquement les types avec des contenus associés voir n'afficher qu'une catéogorie (animation)

**Comment by camillemonchicourt** [comment]
Oui bien vu, c'est à faire au niveau de Geotrek-admin et de son API où on ne devrait ne renvoyer que les types qui ont au moins un contenu associé, comme on le fait sur les autres routes, mais ça a été zappé certainement sur cette route...

**Comment by camillemonchicourt** [comment]
Par contre n'afficher qu'une seule catégorie (animation) ça créerait un fonctionnement différent des 3 autres catégories de contenu et nécessiterait de renvoyer vers la page de recherche avec tous les types d'événements sélectionné qui est aussi un comportement non prévu car on ne connait les types utilisés par chaque Geotrek-rando

**Comment by babastienne** [comment]
La demande d'avoir un unique point d'entrée "Evenement" qui ensuite redirigerait vers toutes les catégories d'évènement m'a été faite également aujourd'hui par un territoire.

On pourrait imaginer une paramètre de custo qui détermine si on affiche au choix :
- chaque catégorie d'évènement sur la page d'accueil
- un seul icone (à configurer dans la custo v3) "Evenement" sur la page d'accueil puis quand on clique dessus ça affiche toutes les catégories pré-cochées. En théorie ça doit être faisable étant donné qu'on propose les catégories d'évènements touristiques comme des "filtres", il suffirait de pré-cocher tous les filtres.

**Comment by amandine-sahl** [comment]
Je pense qu'il faut différencier les deux problématiques suivantes :
 * Filtrer les catégories ayant des éléments associés
 * Regrouper toutes les animations sous une seule catégorie "Animations"

Concernant la seconde problématique est-ce que ce n'est pas à mettre en parallèle du comportement induit par `SPLIT_TREKS_CATEGORIES_BY_PRACTICE` pour les itinéraires? A voir si c'est possible de rajouter un paramètre permettant ou non d'afficher les types d'animations. Personnelement je suis favorable à ce regroupement pour limiter le nombre de catégories et faciliter la compréhension.

**Comment by camillemonchicourt** [comment]
En retestant la route des types d'évènements touristiques est bien filtrée en fonction des contenus : 
- https://geotrekdemo.ecrins-parcnational.fr/api/v2/touristicevent_type/
- https://geotrekdemo.ecrins-parcnational.fr/api/v2/touristicevent_type/?portals=2

Donc le problème initial remonté dans ce ticket n'est pas reproduit.

**Comment by camillemonchicourt** [comment]
En fait le soucis remonté est un peu différent. 
La route ``/touristicevent_type/`` est bien filtrée pour ne renvoyer que les types d'événement qui ont un au moins un contenu associé publié.

Par contre, ce fonctionnement est comme sur les autres routes. Il regarde tous les événements publiés, sans interroger aussi la date.

Du coup si on a des événements terminés mais publiés, alors ils n'apparaissent plus dans Geotrek-rando mais leurs types sont bien remontés et affichés.
On peut ainsi avoir des types d'événements qui remontent mais sans aucun contenu renvoyé, si les événements de ce type sont tous terminés.

Mais c'est donc un autre sujet et pas un bug et à voir si il faut en plus filtrer les contenus par rapport à la date du jour quand on construit la liste des types d’événements.

**Comment by camillemonchicourt** [comment]
Il est donc proposé de pouvoir grouper les types de contenus par catégorie.
Exemple : 
![Capture d’écran de 2022-06-02 11-57-26](https://user-images.githubusercontent.com/4418840/171606102-5c12aafb-6b1a-4649-ab60-491d53ce0557.png)

D'utiliser leur couleur disponible depuis la 3.7.0, en revoyant un peu celles proposées par défaut comme indiqué dans https://github.com/GeotrekCE/Geotrek-rando-v3/issues/673

Et d'attribuer à chaque catégorie un picto global repris dans le bloc de filtres : 
![Capture d’écran de 2022-06-02 12-02-03](https://user-images.githubusercontent.com/4418840/171606539-f9cc9e52-77f5-430f-b3b7-09858318a6ab.png)

**Comment by dtrucs** [comment]
Proposition de config à ajouter dans `home.json`:
Ci-dessous est la configuration par défaut qui serait l'équivalente de l'affichage de GTR3 avant cette fonctionnalité (rétrocompatibilité)

```js
  "activityBar": {
    "shouldDisplay": true,
    "numberOfItemsBeforeTruncation": 8,
    "trek:" {
        "group": false,
        "display": true,
        "order": 1
     },
    "outdoor:" {
        "group": false,
        "display": false,
        "order": 2
     },
    "service:" {
        "group": false,
        "display": true,
        "order": 3
     },
    "event:" {
        "group": false,
        "display": true,
        "order": 4
     }
  }
```

- `shouldDisplay` : existe déjà et permet d'afficher ou non cette encart
- `numberOfItemsBeforeTruncation` permet d'afficher un nombre d'éléments avant le bouton "... Voir plus". + d'infos dans le ticket relatif https://github.com/GeotrekCE/Geotrek-rando-v3/issues/568
- `trek` ; `outdoor`; `service` ; `event` contiennent exactement les mêmes clés qui sont les suivantes :
  - `group`: Si cette propriété est cochée, toutes les catégories sont réunies en un lien et au clique celui amène vers la recherche avec tous les filtres relatifs activés ; si non cochée, toutes les catégories sont affichées
  - `display`: permet de granulariser l'affichage des éléments dans cette barre d'activité
  - `order` permet de déplacer leur ordre d'affichage

Je pense que cela couvre la fonctionnalité, 
Des éléments à ajouter/modifier ?

**Comment by camillemonchicourt** [comment]
Oui, OK pour moi, c'est bien raccord avec nos échanges sur le sujet.

**Comment by AudreyRemy** [comment]
Bonjour,
nous travaillons sur le module Outdoor et nous serions intéressés par cette possibilité de pouvoir regrouper par catégorie ou même mixer les catégories comme l'a fait le département du Pas-de-Calais https://www.escapade62.fr/ 
Ce développement est-il toujours d'actualité ou devons-nous modifier le fichier homeTop.html ?

**Comment by camillemonchicourt** [comment]
Pour pouvoir grouper toutes les pratiques dans sa catégorie sur la Home (Randos, Outdoor, Service et/ou Evenements), il faudrait financer et réaliser le développement détaillé ci-dessus par @dtrucs.

----------------

Pour regrouper Rando et Outdoor dans un seul onglet, comme sur Escapade62, un développement a été fait et est disponible depuis la version 3.8.3 : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/656

**Comment by dtrucs** [comment]
Une nouvelle configuration (développement en cours https://github.com/GeotrekCE/Geotrek-rando-v3/pull/1009) permet d'avoir plus de personnalisation à propos de la barre d'activité de la page d'accueil.

## Affichage par défaut

Voici l'ajout de configuration et celle proposée par défaut (qui permet un affichage avec une rétrocompatibilité de l'existant) :

```diff
  "activityBar": {
    "shouldDisplay": true,
+   "numberOfItemsBeforeTruncation": 8,
+   "links": [{
+      "type": "trek",
+      "grouped": false
+   },
+   {
+     "type": "outdoorSite",
+     "grouped": false
+   },
+   {
+     "type": "touristicContent",
+     "grouped": false
+   },
+   {
+     "type": "touristicEvent",
+     "grouped": false
+   }]
  },
```
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/1926041/56d605f3-7b18-415e-ab07-8a68eadd06fd)

Je ne m'attarde pas sur `numberOfItemsBeforeTruncation` qui est la réponse à ce ticket https://github.com/GeotrekCE/Geotrek-rando-v3/issues/568.

## Ne pas afficher certaines catégories et changer leur ordre

Si on souhaite inverser l'ordre des types de contenu et/ou ne pas en afficher, il convient de jouer avec les éléments du tableau. Ci-dessous j'affiche les catégories uniquement et (dans cet ordre) de contenu touristiques et outdoor

```json
"links": [
  {
    "type": "touristicContent",
    "grouped": false
  },
  {
    "type": "outdoorSite",
    "grouped": false
  }
]
```

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/1926041/c3fae1e4-c45c-4336-8624-d275e9fa489a)

## Mêler catégories groupées et non groupées

Il est possible de grouper les catégories sous un même button en définissant `grouped: true`.
En cliquant sur le boutton d'une catégorie groupée, il mènera vers la page de recherche avec tous les filtres de la catégorie activés.
Avec le même exemple :
```json
"links": [
  {
    "type": "touristicContent",
    "grouped": false
  },
  {
    "type": "outdoorSite",
    "grouped": true
  }
]
```
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/1926041/06dee848-3f27-4add-a71f-a79f4dbf6600)

## Personnaliser les catégories groupées

Voici l'exemple avec les 4 types de contenus regroupés 
```json
"links": [
  {
    "type": "trek",
    "grouped": true
  },
  {
    "type": "outdoorSite",
    "grouped": true
  },
  {
    "type": "touristicContent",
    "grouped": true
  },
  {
    "type": "touristicEvent",
    "grouped": true
  }
]
```
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/1926041/f1667a88-0e47-4e76-a123-abb9727ff766)

Pour les catégories groupés il est possible de définir un autre pictogramme via l'ajout de la propriété `iconUrl`
```json
{
  "type": "trek",
  "grouped": true
  "iconUrl": "/medias/icons/pedestrians.svg"
},
```
 
Il est également possible de redéfinir les intitulés via les fichiers de traductions. Par ex dans `fr.json`
```json
{
  "home": {
    "activityBar": {
      "practices": "Treks",
      "outdoorPractices": "Activités",
      "touristicContent": "Contenus touristiques",
      "touristicEvent": "Évènements touristiques"
    }
  }
}
```

## Autre changement 
Si vous avez définie des [couleurs pour chaque type de catégorie](https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization.md#colors), elle apparaitront au survol et focus des liens de la barre d'activité.

**Comment by camillemonchicourt** [comment]
Intégré dans la 3.17.0
