### ISSUE TITLE
Encodage sélecteur CSS

### ISSUE THREAD

**Issue by MNourrisson** [GeotrekCE/Geotrek-rando-v3#561]
Bonjour,

y-a t-il un moyen d'éviter l'encodage du signe ">" que j'ai utilisé dans mon custom CSS ?
Ma ligne CSS `main .loadedContent > div.sc-hTZgZg  > div.cbapfU > div:nth-child(3) .mb-4 + .grid.gap-4{display:none;}` est transformée en 
![image](https://user-images.githubusercontent.com/34370970/152969455-bc861802-da99-421a-8a37-257b0d32bb54.png)

Merci

**Comment by camillemonchicourt** [comment]
Je pense que le soucis est assez similaire à celui évoqué ici où les " étaient échappés : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/548
A creuser comment faire en sorte que cela ne soit pas le cas.

**Comment by dtrucs** [comment]
Fixé depuis [3.10.1](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.10.1)
