### ISSUE TITLE
Filtrer par date les évènements tourisitiques

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#567]
Ajouter parmi les filtres proposés dans l'interface dédiée aux évènements la possibilité de filtrer par date de début / date de fin.

Cela permettrai à l'utilisateur de ne pas avoir à parcourir toute la liste pour trouver les activités qui sont proposées pendant son séjour.

**Comment by camillemonchicourt** [comment]
Oui exact.
L'intégration des événements a été faite à minima pour une première version, mais on avait identifié cette évolution des filtres : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/389#issuecomment-969368945

C'est d'ailleurs prévu et designé : 

![Capture d’écran de 2022-02-15 11-51-40](https://user-images.githubusercontent.com/4418840/154047526-bed015e5-ce55-4bde-9a87-ffac1bffb75d.png)

**Comment by camillemonchicourt** [comment]
Fait dans la 3.10.1.

![image](https://user-images.githubusercontent.com/99249234/171830711-1945586e-aac4-4e20-a057-9fc6e12de52e.png)

![image](https://user-images.githubusercontent.com/99249234/171830769-7a8dfa75-0e05-4ee4-9de4-a686ffb4fb59.png)
