### ISSUE TITLE
Pouvoir paramétrer le nombre d'éléments affichés sur la page d'accueil

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#568]
Aujourd'hui on peut paramétrer le nombre de pages à afficher en haut de la page Rando, le reste va automatiquement dans une catégorie "En savoir plus". (voir capture ci-dessous)

![image](https://user-images.githubusercontent.com/16348048/153447209-429e5f49-eae7-441e-895b-45e27e090654.png)

De la même manière, il serait souhaitable de pouvoir paramétrer le nombre d'entrées dans le menu sur la page d'accueil. Au delà de ce nombre les catégories suivantes iraient comme c'est le cas aujourd'hui dans une section "Voir plus". Aujourd'hui ce nombre semble être 8 mais ne me parait pas être un paramètre de customisation.

![image](https://user-images.githubusercontent.com/16348048/153447457-139b97e1-1bc7-4bce-82e8-fea46e892028.png)

**Comment by camillemonchicourt** [comment]
En effet, on avait fait en sorte d'en afficher le nombre qui rentre bien sur les différentes tailles d'écran.
Mais on pourrait peut-être affiner cela pour en afficher plus sur les grands écrans.

Ou alors en faire un paramètre, mais si c'est optimisé et qu'on en met le maximum qui rentre dans les différentes tailles d'écran, ce paramètre n'est peut-être pas utile ?

**Comment by babastienne** [comment]
Selon moi proposer un paramètre permet de laisser plus de modularité à l'utilisateur, j'aurai tendance à privilégier cette option

**Comment by camillemonchicourt** [comment]
Oui oui entre temps j'ai regardé à nouveau et en effet, il y a énormément de place non utilisé sur Desktop en limitant à 8 objets, c'est dommage.
Je pense qu'on devrait déjà élargir largement par défaut pour en proposer plus que 8 et ainsi éviter d'avoir à cliquer sur VOIR PLUS quand on a 9, 10, 11 ou 12 catégories de contenu.
Et en même temps, pourquoi pas en faire un paramètre en effet.

**Comment by camillemonchicourt** [comment]
Intégré dans la 3.17.0
