### ISSUE TITLE
problème ajout de langue

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando-v3#571]
version gtk-rando : latest

La langue italienne (it) s'implémente sans problème, mais quand je veux implémenter d'autres langues (espagnol, catalan, allemand) en paramétrant le header.json et le translations/es.json (et les autres json), l'application ne fonctionne plus. Je suspecte le manque d'images pour les drapeaux des différentes langues sur la page d'accueil.

Je précise que j'ai bien suivi la doc et que j'ai paramétré au minimum requis les fichiers .json.

**Comment by dtrucs** [comment]
Bonjour,
Concernant les drapeaux, il s'agit d'une URL contenant un paramètre de la langue pour récupérer le bon drapeau. Donc si la langue est "de", il va chercher cette image https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.3/flags/4x3/de.svg 

Cependant il y a 2 limitations avec cette méthode :
- Si une régionalisation est définit avec la langue (par exemple `"supportedLanguages": ["de-de"],`), l'URL va se construire bêtement avec `de-de` et le drapeau ne sera pas trouvé. C'est facilement corrigeable.
- L'app interagit avec des langues or il s'agit de `country code` et ce n'est pas toujours iso (par ex comme dans le code on peut voir GB !== EN https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/components/InlineMenu/InlineMenu.tsx#L91)

Si l'app ne fonctionne plus, il peut avoir un problème avec les langues du navigateurs ne correspondant pas exactement avec celles de `supportedLanguages` => https://github.com/GeotrekCE/Geotrek-rando-v3/issues/527

**Comment by camillemonchicourt** [comment]
Je pense qu'il n'est pas possible d'utiliser une langue dont on n'a pas un fichier de base existant dans https://github.com/GeotrekCE/Geotrek-rando-v3/tree/main/frontend/src/translations

Donc n'hésite pas à contribuer les fichiers de langue dans ce dossier sous forme de PR et ça devrait être bon en incluant ça dans la prochaine version.

Sinon il faudrait des logs pour savoir ce qui coince ?

**Comment by mviadere-openig** [comment]
Bonjour et merci pour vos réponses. 
@camillemonchicourt  je ne sais pas où récupérer les logs pour Geotrek-Rando-V3. 

Je suis en lien actuellement avec l'Office de Tourisme qui souhaite implémenter ces langues, ils vont travailler sur la traduction es, de et ca. je ferai une PR quand ils m'auront fait les traductions.

**Comment by camillemonchicourt** [comment]
OK pour les traductions, à suivre donc.

Pour les logs, c'est indiqué dans la doc https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/installation.md

> If you want to have logs directly in terminal you can just run ``docker-compose up``. ``ctrl+c`` will exit the command and stop the container. That's why ``docker-compose up -d`` is used in production to run the service in the background.
> 
> You can also access Node.js server logs with ``docker-compose logs -t``.

**Comment by mviadere-openig** [comment]
Merci pour l'info !

**Comment by mviadere-openig** [comment]
Bonjour, les traductions ont été faites et proposées en PR, je clos donc l'issue.

**Comment by camillemonchicourt** [comment]
Il vaut mieux tester avant et aussi que ça soit disponible dans une release avant de fermer un ticket, mais ça ne devrait pas tarder.

**Comment by mviadere-openig** [comment]
Ok, c'est noté pour les prochaines PR :)
