### ISSUE TITLE
Dénivelé négatif

### ISSUE THREAD

**Issue by MNourrisson** [GeotrekCE/Geotrek-rando-v3#574]
Bonjour,

j'ai un tracé avec un dénivelé négatif et cela ne semble pas être géré par l'application car la valeur est remplacée par 0 alors que dans l'admin le calcul de la pente semble correct.

Sur la v3
![image](https://user-images.githubusercontent.com/34370970/154097870-29f3a9d3-eb57-460f-ba15-97910ce4365d.png)

Dans l'admin
![image](https://user-images.githubusercontent.com/34370970/154098470-b894cdf1-a206-4634-8887-fbca0eabaeaf.png)

**Comment by MNourrisson** [comment]
Oui, c'est que cela affiche dénivelé également négatif.

**Comment by camillemonchicourt** [comment]
OK on le l'affichait pas non plus dans la v2 car il est souvent égal au dénivelé positif, mais ça vaudrait le coup de l'afficher en effet, surtout pour des cas comme celui-ci.

**Comment by camillemonchicourt** [comment]
Fait dans la 3.8.0 : 

![Capture d’écran de 2022-04-08 19-27-43](https://user-images.githubusercontent.com/4418840/162492000-fd8bacee-9afc-4238-b056-2ad46d6ba6b9.png)
