### ISSUE TITLE
Customisation titre et icônes

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#576]
Bonjour,
Nous avons modifié le titre qui se situe au-dessus des photos ou de la vidéo sur la page home, via le fichier fr.json. Est-ce bien correct ou devons-nous faire cette modification dans un autre fichier ?
Pouvez-vous me dire s’il existe un dépôt avec des icônes libres de droit à intégrer dans Geotrek (exemple : icône pour la course d’orientation) ?
Merci d’avance pour votre retour.
Bonne fin de journée.
Bien cordialement.

**Comment by camillemonchicourt** [comment]
Oui c'est ça en effet.
Il faut aussi renseigner ``applicationName`` dans la configuration comme indiqué dans la doc de customisation (https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization.md), c'est elle qui s'affiche quand on a installé le portail sur mobile en tant que PWA, au moment du lancement de celle-ci.

**Comment by AudreyRemy** [comment]
Merci encore Camille.
