### ISSUE TITLE
Name-server

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#577]
Bonjour, 

Nous avons installé Geotrek Rando V3 via Docker grâce à l’installer 2.0.1. 

Nous suivons les conseils sur GitHub et avons téléchargé Geotrek-rando-v3-3.6.0.zip mais continuons à modifier les fichiers dans le dossier Geotrek-rando-v3-installer-2.0.1. Comment pouvons-nous nous assurer que nous utilisons bien la dernière version de Rando V3 comme préconisé sur la communauté ?

Nous souhaiterions remplacer l’adresse IP :8080 par notre nom de domaine mais n’arrivons pas à suivre la procédure https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/installation.md
Un paragraphe mentionne NGINX mais nous pensions qu’avec Docker la procédure était différente. À ce jour nous n’avons besoin que d’un seul Geotrek Rando mais par la suite, nous en utiliserons plusieurs.
Nous avons également essayé de mentionner notre nom de domaine dans le fichier de customization global.json avec baseUrl: mais sans succès.

Merci d’avance pour votre aide.
Bonne fin de journée.
Bien cordialement.

**Comment by camillemonchicourt** [comment]
Il n'y a pas à télécharger Geotrek-rando-v3-3.6.0.zip. Ces fichiers ne sont pas utilisés pour déployer Geotrek-rando-v3, seulement utiles pour le développement.

Le dépôt "https://github.com/GeotrekCE/Geotrek-rando-v3" contient le code source, mais Geotrek est déployé en tant qu'image Docker que l'on publie à chaque nouvelle version ici : https://github.com/GeotrekCE/Geotrek-rando-v3/pkgs/container/geotrek-rando-v3%2Fgeotrek-rando

Seul l'installeur "Geotrek-rando-v3-installer" est utile pour installer Geotrek-rando-v3 sous forme d'image Docker.

Par défaut quand on installe Geotrek-rando-v3, cela prend la version ``latest``, la plus récente (https://github.com/GeotrekCE/Geotrek-rando-v3-installer/blob/main/docker-compose.yml#L4).
Cette version est indiqué dans l'espace de stockage des images Docker : https://github.com/GeotrekCE/Geotrek-rando-v3/pkgs/container/geotrek-rando-v3%2Fgeotrek-rando
A chaque fois que vous lancez une mise à jour de Geotrek-rando, cela installera la version la plus récente (``latest``) de Geotrek-rando

Si vous souhaitez utiliser une version particulière et non pas la plus récente, il faut indiquer le numéro de version spécifique à la place de ``latest`` dans le fichier ``.env`` à la racine de votre dossier contenant l'installeur : https://github.com/GeotrekCE/Geotrek-rando-v3-installer/blob/main/.env.example#L1

-------------------------

Même si on utilise Docker pour déployer Geotrek-rando-v3, il faut bien un serveur web (NGINX conseillé et documenté mais vous pouvez en utiliser un autre), pour pouvoir gérer le nom de domaine, le HTTPS, etc...

Pas de soucis pour avoir plusieurs Geotrek-rando-v3 sur un même serveur, c'est prévu pour. Il suffit que chaque installation soit associée à un port différent grâce au fichier ``.env``. C'est documenté.

**Comment by AudreyRemy** [comment]
Merci Camille.
