### ISSUE TITLE
Catégories des filtres en version mobile

### ISSUE THREAD

**Issue by MNourrisson** [GeotrekCE/Geotrek-rando-v3#586]
Bonjour,

J'ai des filtres différents selon si je suis en vue desktop ou en vue mobile (apparition des filtres Outdoor et évènements).

Voici ma vue desktop : 
![image](https://user-images.githubusercontent.com/34370970/156586528-279a7be0-7e62-4ac4-a270-4bcae9b542eb.png)

Voici ma vue mobile : 
![image](https://user-images.githubusercontent.com/34370970/156586464-520ff08d-53ec-40dd-9d1d-462bf0286ec2.png)

J'ai modifié les paramètres dans filter.json, ainsi que ceux dans global.json.

Faut-il paramétrer à d'autres endroits ?

Version de Géotrek v3 : 3.6.0

Merci

**Comment by camillemonchicourt** [comment]
Oooch en effet, joli casserole.
En fait les blocs "Randonnées", "Outdoor", "Services" et "Evenements" ne s'affichent que si il y a au moins un contenu dans chaque catégorie.
Mais on dirait qu'en version mobile, cette vérification ne soit pas effectuée.
C'est un oubli, je vais voir si on peut le rectifier rapidement.

**Comment by camillemonchicourt** [comment]
Je viens d'approfondir les tests et même en passant à ``false`` les paramètres dans le fichier ``global.json``, les catégories Outdoor et Evenements s'affichant quand même dans les filtres en version mobile :-/

```json
  "enableOutdoor": false,
  "enableTouristicEvents": true,
```

C'est un soucis récurrent que les filtres en version Desktop et en version Mobile sont développés indépendamment, du coup quand on fait des évolutions sur les filtres en version Desktop, on oublie souvent de les faire aussi sur les filtres en version mobile...

**Comment by camillemonchicourt** [comment]
Avec la PR https://github.com/GeotrekCE/Geotrek-rando-v3/pull/587 : 
- Les catégories de contenus sont aussi vérifiées si elles ont au moins un contenu pour être affichées dans les filtres
- Si les filtres ``enableOutdoor`` et ``enableTouristicEvents`` sont à ``false`` ces catégories ne sont pas affichées dans les filtres Desktop ni Mobile, même si elles sont des contenus

**Comment by camillemonchicourt** [comment]
Exact, problème similaire où un fonctionnement Desktop (https://github.com/GeotrekCE/Geotrek-rando-v3/commit/63c15777d4d080571c3d573521d21bb46da39a29) n'a pas été reporté en mobile.
Le test de longueur du nombre de langue doit certainement être reporté sur la version mobile sur https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/components/Header/BurgerMenu/BurgerMenu.tsx#L53 ou https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/components/Header/BurgerMenuSection/BurgerMenuSection.tsx#L68

Ça mérite un ticket dédié car c'est un autre sujet que l'on verra quand on peut traiter.

**Comment by MNourrisson** [comment]
Bonjour,
J'ai remarque un autre problème.

Je souhaite désactiver l'affichage de la rubrique "themes" dans le menu des filtres. 
J'ai modifié le fichier filter.json
`{
    "id": "themes",
    "type": "MULTIPLE",
    "display": false
  }`

L'élément de la rubrique ne s'affiche plus, mais la rubrique si.
![image](https://user-images.githubusercontent.com/34370970/157484550-e5f5ccd3-8ba0-4af2-b395-3f69cf124bdb.png)
J'ai fait un test avec la rubrique "services" et c'est pareil.
Cela se produit également sur la version mobile.

**Comment by camillemonchicourt** [comment]
OK, comme pour l'autre sujet.
Il faut vraiment privilégier un ticket par sujet, donc je bascule cette remontée dans un ticket dédié.

**Comment by camillemonchicourt** [comment]
J'ai basculé le 3° sujet dans un ticket dédié.

**Comment by camillemonchicourt** [comment]
Fait dans la version 3.7.0.
