### ISSUE TITLE
Sections HTML/Scripts

### ISSUE THREAD

**Issue by dtrucs** [GeotrekCE/Geotrek-rando-v3#588]
À l'instar des templates de customisation `homeTop.html` et `homeBottom.html`, il serait pertinent de pouvoir ajouter des sections HTML à divers endroits du site tel que par exemple le footer évoqué ici :https://github.com/GeotrekCE/Geotrek-rando-v3/issues/549
 
Il serait intéressant de pouvoir lister les différents besoins possibles: 
- `headerTop`, `headerBottom`, `footerTop`, `footerBottom` afin de couvrir le maximum la personnalisation dans la structure de page.
- `detailsTop`, `detailsBottom` ?
- J'ajouterai `scriptsHeader`, `scriptsFooter` afin de pouvoir insérer des scripts de mesure d'audience (autre que Google Analytics) et éventuellement d'autres scripts tiers (marketing ou autre).
- Autre ?

**Comment by camillemonchicourt** [comment]
Oui intéressant, mais il faudrait préciser pour quoi faire.
Par exemple pour le header, ce serait pour mettre des éléments au-dessus ou en dessous du Header existant ?

Pour les scripts, pourquoi pas, mais pour les outils de mesure d'audience, je pense qu'on aurait surtout intérêt à intégrer le script Matomo avec un paramètre associé.
Si le paramètre Matomo est renseigné, alors on charge son script, si c'est celui de Google Analytics alors on charge celui de GA.

**Comment by dtrucs** [comment]
Apparté concernant Matomo ⬇️ : 
J'ai regardé l'intégration via un paramètre de config. L'identifiant attendu par Matomo est une URL donc la clé serait `matomoURL` à fournir afin d'injecter le script dans l'application.

Je constate aussi qu'aujourd'hui Matomo permet de granulariser les informations avec 4 options ⬇️ 
![image](https://user-images.githubusercontent.com/1926041/160665890-baef65ca-12ff-45e7-ace7-88847fc12e1d.png)
Et selon ce qui est coché, le code à injecter est altéré.
Donc, pour aller jusqu'au bout il conviendrait de créer le schéma suivant (noms des options à optimiser)
```json
{  
  "matomo": {
     "url": "<matomo_url>",
     "options": {
       "allDomains": false,
       "groupByDomain": false,
       "allAliases": false,
       "noscript": false
    }
  }
}
```

Au delà du poids que prend cette configuration, je resence les limitations suivantes : 
- La compréhension des options n'est pas intuitive comparée à la page d'intégration/explication de Matomo
- Si des options sont ajoutés/supprimés/modifiés par Matomo, il faudra modifier le code de l'app en conséquence
- Idem si le script d'intégration change

Pour toute la complexité que cela mène je pense que ça serait plus simple de laisser des templates scripts comme suggéré initialement et laisser les utilisateurs intégrer leurs propres scripts comme ils l'entendent. Cela apporte d'autres avantages :

- Geotrek Rando n'a plus aucune responsabilité pour les scripts tiers. Ce sont les utilisateurs les intégrant qui en prendront la charge.
- Si un utilisateur souhaite intégrer un autre script de tracking (comme https://umami.is/ par ex), on ne se posera pas la question de créer une énième config.

Et pour les mêmes raisons, j'irai jusqu'à rendre la config `googleAnalyticsId` en `deprecated`.

**Comment by babastienne** [comment]
Pour compléter, c'est assez commun de détacher le produit des scripts tiers utilisés. De cette manière plusieurs avantages :
- On influence pas l'utilisateur sur le choix du l'outil qu'il veut utiliser (GA, Matomo, Umami ou autre)
- On évite de devoir maintenir à jour une configuration qui va devoir évoluer au fil du temps du fait des évolutions des scripts tiers
- On laisse à la communauté la possibilité de personnaliser beaucoup plus loin le comportement de Geotrek-Rando en sortant de la configuration de base

Pour ce qui est de "perdre" l'utilisateur avec une configuration complexe, je pense qu'il va surtout falloir effectuer un travail sur la documentation. Si on intègre une zone permettant d'importer n'importe quel script il faudra documenter plusieurs exemples possibles (avec GA, Matomo ou autre) pour que l'utilisateur qui lit la documentation sache toujours comment faire.

**Comment by camillemonchicourt** [comment]
En plus des 2 existants, plusieurs templates HTML ont été ajoutés dans la version 3.8.1 : 

- ``customization/html/headerTop.html``: before the header section
- ``customization/html/headerBottom.html``: after the header section and before the content page
- ``customization/html/footerTop.html``: before the footer section and after the content page
- ``customization/html/footerBottom.html``: after the footer section
- ``customization/html/scriptsHeader.html``: in the <head> of the document
- ``customization/html/scriptsFooter.html``: just before the </body> end tag

Indiqués dans la documentation de customisation : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization.md#html--scripts

**Comment by dtrucs** [comment]
"Affiché avant" en terme de position ou de rendu ?

En position ça ne devrait pas être possible car le `footerTop` est littéralement avant le footer https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/components/Footer/Footer.tsx#L13

Le `homeBottom` dans la page home https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/components/pages/home/Home.tsx#L69 où on remarque quelques lignes + bas l'appel de `<Footer />`.

Si c'est en rendu, je ferai des vérifications.

Effectivement, ça serait fortement intéressant de pouvoir multiplier les injections dans les pages de contenus. Faudrait spécifier ça pour que soit générique et pertinent pour chaque type de contenu (et que ça soit en cohérence avec la future refacto des pages "détails", cf [#510](https://github.com/GeotrekCE/Geotrek-rando-v3/issues/510))

**Comment by camillemonchicourt** [comment]
Oui de mémoire dans mes tests, il se positionnant avant, mais peut-être que je m'embrouille.

**Comment by dtrucs** [comment]
Il est désormais possible de créer des custom html pour les pages details depuis la version [v3.16.0 ](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.16.0).
