### ISSUE TITLE
Page statique - Attribut "Target" non pris en compte

### ISSUE THREAD

**Issue by jcanto05000** [GeotrekCE/Geotrek-rando-v3#590]
Bonjour,

Je travaille actuellement sur ce site : http://51.77.204.23:8080/
Version 3.6.0

L'attribut target="_blank" n'est pas pris en compte pour les pages statiques qui ne sont pas dans le menu "En savoir plus".

Ici, la page "Serre-Ponçon" ne s'ouvre pas dans un nouvel onglet.
![image](https://user-images.githubusercontent.com/12727510/157452206-50e2341a-7142-4c2a-9bdc-0bcb15c0754b.png)
 
Quand on passe en version mobile, l'attribut est bien présent.

**Comment by camillemonchicourt** [comment]
Ah bizarre, car ça avait été testé et mis en place.
Et sur https://gtr3demo.ecrins-parcnational.fr/ ça fonctionne bien avec le lien "un lien sympa" qui s'ouvre bien dans un nouvel onglet.
Je ne vois pas pourquoi.

**Comment by jcanto05000** [comment]
De ce que je vois "Un lien sympa" se trouve dans le menu "En savoir plus".
Ce qui n'est pas le cas de "Serre-Ponçon".

D'où le fait que ça fonctionne chez toi et pas chez moi !

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 3.19 (nécessitant Geotrek-admin 2.104+) basée sur le nouveau système d'éléments de menu, complétant les pages statiques.
Documenté côté Geotrek-admin sur https://geotrek.readthedocs.io/en/latest/usage/static-pages.html
