### ISSUE TITLE
Liste des langues en version mobile

### ISSUE THREAD

**Issue by MNourrisson** [GeotrekCE/Geotrek-rando-v3#591]
Bonjour, 
je pense que cela doit être la même chose pour les langues. 
Je n'ai pas d'icône dans ma barre header car le site est uniquement en français : 
![image](https://user-images.githubusercontent.com/34370970/157075941-6dde018b-df74-400b-acde-828799ef5e75.png)

Par contre sur la version mobile, l'item apparaît : 
![image](https://user-images.githubusercontent.com/34370970/157076061-b8b072fe-8e83-4d8f-b932-8a63b9e84268.png)

_Originally posted by @MNourrisson in https://github.com/GeotrekCE/Geotrek-rando-v3/issues/586#issuecomment-1060882276_

**Comment by camillemonchicourt** [comment]
Exact, problème similaire à https://github.com/GeotrekCE/Geotrek-rando-v3/issues/586 où un fonctionnement Desktop (https://github.com/GeotrekCE/Geotrek-rando-v3/commit/63c15777d4d080571c3d573521d21bb46da39a29) n'a pas été reporté en mobile.
Le test de longueur du nombre de langue doit certainement être reporté sur la version mobile sur https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/components/Header/BurgerMenu/BurgerMenu.tsx#L53 ou https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/components/Header/BurgerMenuSection/BurgerMenuSection.tsx#L68
