### ISSUE TITLE
Filtre par categorie sur la home

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#594]
Bonjour,
J'essaie de ne faire remonter que certaines catégories sur la page d'accueil en modifiant le fichier global.json et en ajoutant la ligne "portalIds": ,
Dans l'exemple https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/customization/config/global.json où trouve-t-on le 1 (ID) de "portalIds": [1], ? 
J'ai essayé en remplaçant avec les prefixed id (exemple T4 pour la rando pédestre chez nous) que je trouve via l'Administration de Django de Geotrek-Admin mais sans succès.
Merci d'avance pour votre aide.
Bonne journée.

**Comment by camillemonchicourt** [comment]
Les pratiques ("rando pédestre" par exemple) ne sont pas des portails et on ne peut filtrer les contenus publiés que par portail au niveau de Geotrek-rando.

Les portails sont définis dans l'Adminsite de Geotrek-admin. Exemple sur le serveur de DEMO : https://geotrekdemo.ecrins-parcnational.fr/admin/common/targetportal/

On trouve leur ID dans leur URL, c'est pas évident, on pourrait les afficher plus clairement : 

![Capture d’écran de 2022-03-11 14-24-38](https://user-images.githubusercontent.com/4418840/157876692-5b67e187-0378-404a-a5dd-5ac61d21b029.png)

Rando Ecrins est ainsi le portail avec ID=1 sur le Geotrek-admin de DEMO : https://geotrekdemo.ecrins-parcnational.fr/admin/common/targetportal/1/change/

**Comment by AudreyRemy** [comment]
Merci Camille.
Je n'ai pas de compte sur le serveur de DEMO donc je ne peux pas ouvrir les liens. 
Je crois que je me suis mal exprimée.
Si je prends l'exemple du site de Rando Aubrac https://www.rando-aubrac.fr/ seuls sont proposés le VTT et le cyclo via 2 picto en page d' accueille.
Il faudrait que je créé un portail cible pour chaque catégorie d'activité ou POI que je veux faire remonter en page d'accueil via les pictos ?

**Comment by camillemonchicourt** [comment]
Sur la démo : 
- Login : admin
- Mot de passe : admin

Les catégories affichées sur Geotrek-rando-v3 dépendent du contenu qui est publié dans le Geotrek-admin.

Les portails ne sont pas associés aux catégories ni aux POI.
On peut associer des randos ou des sites outdoor ou des contenus touristiques ou des événements touristiques à des portails pour faire en sorte que certains contenus aillent sur un portail Geotrek-rando et pas d'autres.

**Comment by Audrey64260** [comment]
Merci Camille et bon week-end
