### ISSUE TITLE
Catalan - Code langue et drapeau différents

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando-v3#601]
version : 3.7.0 

l'activation de la langue catalane dans le header.json affiche le drapeau canadien, voir ici : https://rando-ccavi.openig.org/ca

**Comment by camillemonchicourt** [comment]
OK ouais, c'est pas clair pour le catalan. On peut utiliser des langues ou des pays, qui sont 2 choses différentes.
Voir http://www.lingoes.net/en/translator/langcode.htm

La langue peut être : 

code | language
-- | --
ca | Catalan
ca-ES | Catalan (Spain)
en-CA | English (Canada)
fr-CA | French (Canada)

Pour la catalan, la langue a été associée à ``ca`` mais le drapeau renvoyée pour cette valeur est logiquement celui du canada : https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.3/flags/4x3/ca.svg

Le sujet est identifié ici : https://github.com/lipis/flag-icons/issues/600

A voir si on peut mettre ``es-ct`` ui renvoie le bon drapeau : https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.3/flags/4x3/es-ct.svg.

Mais je ne sais pas si cela collerait avec les éventuels code iso, comme discuté ici : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/571#issuecomment-1036422133

A priori le code iso dans les navigateurs pour le catalan est ``ca``... Donc si on met ``es-ct`` pour avoir le bon drapeau, alors si un utilisateur a son navigateur paramétré en catalan, cela ne lui mettra pas la bonne langue par défaut...

**Comment by camillemonchicourt** [comment]
Après discussion avec @dtrucs, on confirme que dans certains cas il faut dissocier le code ISO de la langue et le code du drapeau.

On pourrait le faire directement dans la configuration, en définissant les 2 potentiellement différents, par exemple @dtrucs propose : 

```
supportedLanguages : [{
  "lng": "fr",
  "countryCode: "fr"
},
{
  "lng": "en",
  "countryCode: "gb"
}]
```

Mais cela nécessite à chacun de bien faire sa configuration.
Sinon gérer ça directement dans le code avec cette autre proposition de @dtrucs : 

En modifiant ici https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/components/InlineMenu/InlineMenu.tsx#L91 en appelant ``getCountryCodeByLanguage()``

```
const getCountryCodeByLanguage = (language) => {
  const [lng, region] = language.split('-');
  if (lng = 'EN') {
    // Canada / USA / etc
    if (region) {
      return region;
    }
    return 'GB';
  }
  // Catalan does not have a country code
  if (lng = 'CA') {
    return 'ES-CT';
  }
  return lgn.uppercase()
}
```

**Comment by camillemonchicourt** [comment]
Drapeau catalan intégré dans la version 3.10.8

**Comment by mviadere-openig** [comment]
Actuellement nous sommes à la version 3.14.2 de Geotrek-Rando V3 et il n'y a toujours pas de changement concernant le drapeau catalan. Est-ce qu'il y a une autre manipulation à faire que dans le header.json pour paramétrer la langue (et son drapeau ?)

**Comment by dtrucs** [comment]
La seule configuration à faire est de définir la langue `"ca"` dans les  `supportedLanguages` de `header.json`.
En testant je ne note pas de regression à ce sujet.

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/1926041/e07e1dee-691c-44e9-a604-6639e70b4f38)


Si avec cette configuration ce n'est toujours pas ok, peux-tu indiquer quel drapeau est affiché de ton côté ?

**Comment by mviadere-openig** [comment]
header.json 

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/45095227/abb5ff4b-dc09-445b-845c-e3459464248a)

Geotrek-Rando concerné : https://rando.tourisme-pyrenees-mediterranee.fr/ca

**Comment by dtrucs** [comment]
Je constate qu'il y a un petit liseré gris au dessus de la carte dans la page de recherche or ça a été fixé avec https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.10.7

Je suppose donc que ton Geotrek Rando n'est pas à jour et date d'avant la version 3.10.8 qui apporte le correctif des drapeaux.

**Comment by mviadere-openig** [comment]
Je viens de vérifier le fichier .env, effectivement pour les maj il était dans une version fixe et non en latest, ça fait donc des mois que je lance une commande de mise à jour qui ne prends pas effet... Désolé encore pour le dérangement et merci, c'est réglé :)
