### ISSUE TITLE
Suggestions page home

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#605]
Bonjour,
Je souhaiterais faire remonter sur la page Home des suggestions de randonnée de types différents (pédestre, VTT, équestre).
Actuellement j'utilise le code suivant sur le fichier home.json : 
```
  "suggestions": [
    {
      "titleTranslationId": "home.territoryTreks",
      "iconUrl": "/icons/practice-pedestrian.svg",
      "ids": ["4614", "92", "127"],
      "type": "trek"
    }
  ]
```
Les éléments remontent bien mais le pédestre et le VTT sont "mélangés" puisque tous issus du type "trek", le titre est "Randonnées à découvrir" avec le picto d'une emprunte de chaussure de rando. Où trouve-t-on les pictos du dossier icons ? S'agit-il des icônes intégrées dans notre Geotrek-Admin ?
Est-il possible de différencier les types de pratique (faire 2 paragraphes différents de suggestions comme on peut différencier trek, évènement, outdoor, service, sachant que ces pratiques sont toutes saisies dans les itinéraires (trek) ou devons-nous les présenter dans la même catégories et dans ce cas utiliser un autre picto plus représentatif des différents types d'activité ?
Si la seule solutions est de changer le picto, pouvez-vous m'expliquer la marche à suivre car pour le moment je n'ai qu'un dossier media dans lequel je dépose les logos et vidéo mais je n'ai pas de dossier icons dans mon dossier Geotrek-rando-v3-installer-2.0.1.
Merci d'avance pour votre retour.
Bonne journée

**Comment by camillemonchicourt** [comment]
Oui tu peux faire tout ça. Depuis la 3.7.0, tu peux faire les suggestions de contenu que tu veux, les découper, les organiser et les ordonner comme tu veux : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/372

Pour les pictos et les noms des blocs, ils sont justement customisables dans le home.json avec les propriétés ``titleTranslationId`` et ``iconUrl``.

- La propriété ``titleTranslationId`` permet d'avoir un titre qui s'adapte en fonction de la langue souhaitée. Tu peux te créer les clés de traduction que tu veux pour en ajouter des nouvelles ou surcoucher une clé de traduction existante. Voir https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization.md#translations
- La propriété ``iconUrl`` permet de renseigner le chemin de l'icone SVG à utiliser. Cela peut être une URL absolue (par exemple vers une icône existante dans ton Geotrek-admin - https://geotrekdemo.ecrins-parcnational.fr/media/upload/picto-canoe.svg) ou une URL relative vers un picto que tu aurais mis dans le dossier de customisation de Geotrek-rando-v3 (``/medias/icons/mon-icone.svg``)

**Comment by AudreyRemy** [comment]
Tout fonctionne à merveille !
Merci Camille.
