### ISSUE TITLE
Page statique cible cachée

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#607]
Bonjour
J'ai ajouté une page statique avec les mentions légales de notre site.
Je souhaite que la page soit publiée pour que je puisse créer un lien depuis le footer (j'ai donc coché publié) mais je ne souhaite pas qu'elle apparaisse dans le menu du bandeau. J'ai donc précisé Cible cachée.
La page apparait quand même dans le bandeau.
Est-ce un bug ou n'ai-je pas compris le sens de l'option "cachée".
Merci et bonne journée.

**Comment by camillemonchicourt** [comment]
Actuellement on ne prend pas en compte le champs "cible" dans Geotrek-rando-v3.
Il faudrait exclure du menu du header les pages statiques dont la cible est égale à "cachée" (``"target": "hidden"``).

Exemple de ce que renvoie la route des pages statiques : https://geotrekdemo.ecrins-parcnational.fr/api/v2/flatpage/?fields=id%2Ctitle%2Ctarget

Pour les pages affichées statiques affichées dans le menu, il faudrait ajouter le filtre ``targets=all,web,mobile``.

Exemple : https://geotrekdemo.ecrins-parcnational.fr/api/v2/flatpage/?fields=id%2Ctitle%2Ctarget&targets=all,web,mobile

Mais récupérer par ailleurs toutes les pages statiques pour pouvoir faire un lien vers une page statique "cachée" depuis le footer ou autre.

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 3.19 (nécessitant Geotrek-admin 2.104+) basée sur le nouveau système d'éléments de menu, complétant les pages statiques.
Documenté côté Geotrek-admin sur https://geotrek.readthedocs.io/en/latest/usage/static-pages.html

Il est désormais possible de créer des pages statiques sans les associer à un élément de menu. 
Cela remplace la fonctionnalité de cacher une page statique.
