### ISSUE TITLE
[Customisation] Multilangue dans les pages homeTop.html homeBottom.html

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-rando-v3#617]
Pour les éléments de customisation en json (footer, ...) le mutililingue est pris en compte par les fichiers de taductions.  Est il possible dans les pages `homeTop.html` et  `homeBottom.html` d'utiliser le même mécanisme. Si oui qu'elle est la syntaxe pour que ces messages soient interprétés?

**Comment by dtrucs** [comment]
Non le mécanisme n'est pas mis en place pour les pages template. Cela dit la demande est très pertinente.

**Comment by dtrucs** [comment]
En réfléchissant à l'implémentation de la fonctionnalité, je pense que le mieux reste encore de créer un template par langue car :
- Parser le contenu pour faire des remplacements risque d'apporter des faux-positif
- Et ce n'est pas dit qu'un contenu même traduit soit désirable dans toutes les langues.

Avec un suffixe de la langue :
`homeTop-fr.html` ; `homeTop-en.html` ; etc

**Comment by camillemonchicourt** [comment]
Ouais on faisait comme ça dans Geotrek-rando v2.
C'est un peu lourd à maintenir mais on change pas tous les jours donc ça peut être une bonne solution.

**Comment by camillemonchicourt** [comment]
Mis en place dans la 3.8.0 et documenté : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization.md#html
