### ISSUE TITLE
Desactiver les widgets Météo/Réservation en mode Hors Connexion

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#622]
Lorsqu'on accède à un élément en mode hors connexion sur GTR3 mobile, le widget Météo est affiché même si la requête n'aboutit pas.

![Screenshot_20220406-121039_Firefox](https://user-images.githubusercontent.com/16348048/161953000-3df8813c-c058-41be-a0d1-3f3cce2e2e37.png)

L'idéal serait de pouvoir désactiver automatiquement l'affichage du widget dès qu'on affiche un objet hors connexion pour éviter d'avoir une zone d'affichage comportant une erreur.

**Comment by camillemonchicourt** [comment]
Bien vu, en mode Hors connexion il ne faudrait pas l'afficher.

**Comment by JordaneNS** [comment]
@camillemonchicourt Ok cette fonctionnalité peut être testée sur la demo (en mode mobile)
[https://demo.geotrekrando.natural-solutions.eu/](url)

**Comment by JordaneNS** [comment]
Oui de partout où le widget était présent ;) @camillemonchicourt

**Comment by camillemonchicourt** [comment]
Fait avec https://github.com/GeotrekCE/Geotrek-rando-v3/pull/691

**Comment by camillemonchicourt** [comment]
Fait dans la 3.9.0
