### ISSUE TITLE
Ajout d'une couche optionnelle sur la carte en vue recherche

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#637]
De multiples territoires utilisent le paramètre [OPTIONAL_TILELAYERS](https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/settings-custom-json-all-options.md#main-options-1) dans Geotrek-Rando V2, généralement pour pouvoir afficher les limite du territoire et mettre en avant une zone géographique précise.

Il serait intéressant de pouvoir proposer un comportement similaire dans Geotrek-Rando-V3 pour qu'il n'y ai pas de régressions fonctionnelles pour les territoires qui migrent vers la nouvelle version de GTR.

**Comment by camillemonchicourt** [comment]
Oui, c'est le sujet de ce ticket : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/385

**Comment by dtrucs** [comment]
Fonctionnalité présente depuis la 3.10.5.
