### ISSUE TITLE
Page de recherche anglais  icone "Little forest" internationalisé

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-rando-v3#639]
L'image devant le nombre de résultats de la recherche ne s'affiche pas sur les pages en anglais.

![image](https://user-images.githubusercontent.com/3088650/164755378-7d8f1351-d16f-45ec-942e-1d6a051b4514.png)

**Comment by camillemonchicourt** [comment]
Oui j'avais vu ça, mais pas creusé.
Je viens de comprendre.
C'est car le chemin de l'image est appelé avec une URL relative : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/v3.8.0/frontend/src/components/pages/search/components/SearchResultsMeta/SearchResultsMeta.tsx#L14

Or dans la langue par défaut, la page est sur https://domaine/search, mais dans les autres langues sur https://domaine/en/search, donc il ne trouve logiquement plus l'image ! 

Corrigé ici : https://github.com/GeotrekCE/Geotrek-rando-v3/commit/2166782daa3966323e7312be03a31390e20a3353

**Comment by camillemonchicourt** [comment]
Corrigé dans la 3.8.1
