### ISSUE TITLE
Encarts remontant des fiches de la page d'accueil ne s'affichent pas entièrement sur IOS15+ 

### ISSUE THREAD

**Issue by dtrucs** [GeotrekCE/Geotrek-rando-v3#645]
Les encarts ont une image illustrative puis les informations relative à la fiche

![image](https://user-images.githubusercontent.com/1926041/166458465-471b9dc7-0124-45de-83a6-1b75aa6a6a78.png)

Or sur IOS l'image vignette de l'encart prend toute la place disponible :
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1926041/166458164-832ae009-a4b7-4747-8f04-665b952ccbc3.png">

Il s'agit d'un problème CSS, le contenu est bien présent dans le DOM du navigateur.

**Comment by babastienne** [comment]
On m'a remonté aujourd'hui l'impossibilité d'afficher le widget météo sur GTR3 sous IOS15+ également.

Je n'ai pas pu reproduire, à confirmer donc.

**Comment by camillemonchicourt** [comment]
C'est vrai que je n'ai jamais fait de tests sous iOS, ni eu de retour d'utilisateurs qui se raréfient.
Mais en effet ça vaudrait le coup de faire une série de tests sur iOS et corriger les ajustements à y faire.

**Comment by camillemonchicourt** [comment]
Le problème d'affichage des cartes sur iOS a été corrigé dans la version 3.8.4.
Pour l'autre soucis, à préciser, confirmer dans un ticket dédié.

**Comment by dtrucs** [comment]
Effectivement, je viens de constater que le bugfix n'est pas ok. Je vérifie ça.
Je ne comprends pas le défilement des cartes ? Aurais-tu un exemple ?

**Comment by xavyeah39** [comment]
> Effectivement, je viens de constater que le bugfix n'est pas ok. Je vérifie ça. Je ne comprends pas le défilement des cartes ? Aurais-tu un exemple ?

Oui je voulais parler du défilement latéral des encarts (cards) mais le mot "carte" et trompeur ;)
Merci !

![image](https://user-images.githubusercontent.com/16793813/172581452-e235602f-b57a-4293-bb39-b783ea7a329c.png)
