### ISSUE TITLE
Problématique liaison API ADMIN<->RANDO

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#649]
Bonjour,

Nous venons de réaliser une MAJ majeure sur nos environnements GEOTREK (OS, APPLICATIF et infra [DOCKER]) avant de passer en PRODUCTION ces prochains jours.
En ce sens, nous avons réinstaller les GEOTREK ADMIN & RANDO sur nos environnements PREPROD & PROD.

Mais nous connaissons une problématique de liaison entre RANDO <-> ADMIN au niveau de la recherche comme indiqué en dessous :
 
![image](https://user-images.githubusercontent.com/78603108/168032843-ec2c43ca-2434-48ba-8083-1b25da9e0494.png)

Nous remarquons que sur le module ADMIN, nous avons renseigné que l’API public est là.
 
![image](https://user-images.githubusercontent.com/78603108/168032933-43e3bf82-c28d-46f5-b171-6645dc4b4579.png)

Concernant le module RANDO, nous remarquons que nous avons l’API qui dirige vers l’API correspondante :
 
![image](https://user-images.githubusercontent.com/78603108/168032967-2dcf31cf-c9df-4230-9099-b2f35a6904cb.png)

![image](https://user-images.githubusercontent.com/78603108/168032996-c89b8c0a-b2e6-48bf-90f5-fccc85758171.png)

 

Pouvez-vous nous dire s’il manque des configurations pour rétablir la liaison entre ADMIN <-> RANDO ? 

Merci d’avance.
Bonne journée.

**Comment by mviadere-openig** [comment]
Bonjour, juste pour savoir, que retourne le mode console de votre navigateur quand vous rafraichissez la page de votre randov3 ?  ( il faut appuyer sur F12 lorsque vous êtes sur votre navigateur et cliquer sur l'onglet Console)

**Comment by mviadere-openig** [comment]
Ok, c'est exactement ce que j'imaginais, il s'agit d'un problème de CORS  (plus d'infos ici : https://developer.mozilla.org/fr/docs/web/http/cors/errors/corsmissingalloworigin)

Il faut que tu regardes la configuration nginx de ton geotrek-admin ( /etc/nginx/sites-enabled/geotrek.conf par exemple)

Peux-tu poster ton fichier de configuration nginx de ton Geotrek-admin s'il te plait ?  Je pense que ce post pourras sûrement t'aider (à partir du message de Camille Monchicourt : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/460#issuecomment-982695112

sinon le lien de la doc pour nginx : https://geotrek.readthedocs.io/en/latest/install/configuration.html#nginx-configuration

**Comment by camillemonchicourt** [comment]
Oui, il y a un problème de CORS, il faut que le serveur Geotrek-admin autorise l'URL du serveur Geotrek-admin à l'interroger en direct.

Attention, il faut bien se baser sur la conf par défaut présente dans Geotrek-admin, qu'on a encore revu et amélioré récemment : https://github.com/GeotrekCE/Geotrek-admin/blob/master/conf/nginx.conf.in

C'est celle-ci qui est utilisée par défaut, et se baser sur la documentation indiquée par @mviadere-openig.
Les anciens tickets peuvent apporter des éclairages, mais attention à leur contenu et exemples, qui peuvent avoir évolué dans les versions plus récentes de Geotrek-admin.

Ensuite l'autre point important est que la configuration de Geotrek-admin autorise bien l'URL du Geotrek-rando. 
C'est défini par le paramètre ``RANDO_SERVER_NAME`` modifiable lors de la configuration de Geotrek-admin lancée avec la commande ``sudo dpkg-reconfigure geotrek-admin``. Soit il faut y renseigner l'URL du Geotrek-rando, soit mettre ``*`` pour autoriser toutes les URL.

**Comment by mviadere-openig** [comment]
Merci @camillemonchicourt, c'est l'exemple que je voulais lui montrer mais je ne savais pas où il était situé :)

**Comment by AudreyRemy** [comment]
Merci @mviadere-openig et @camillemonchicourt 
Je transmets vos retours à mes collègues car je ne gère pas l'installation.

**Comment by AudreyRemy** [comment]
ça y est ça fonctionne, merci à vous deux.
Pour info, voilà la réponse de mes collègues : 
nous avons modifié le fichier /opt/geotrek-admin/var/conf/ngninx.conf en rajoutant https ci-dessous :
![image](https://user-images.githubusercontent.com/78603108/168101823-494c8635-62e9-4681-bd62-99993cff3c41.png)

**Comment by camillemonchicourt** [comment]
Attention, comme évoqué en entête de ce fichier, mais aussi dans la doc, il ne faut pas modifier ce fichier, car il est écrasé à chaque mise à jour.

Pour renseigner l'URL souhaitée (avec le https donc dans ton cas), il faut le faire en relançant la configuration de Geotrek-admin avec la commande ``sudo dpkg-reconfigure geotrek-admin``.

Par contre, si besoin, vous pouvez modifier son template utilisé à chaque mise à jour (``/opt/geotrek-admin/var/conf/nginx.conf.in``).

Rappel de la conf qui précise cela : https://geotrek.readthedocs.io/en/latest/install/configuration.html#nginx-configuration
