### ISSUE TITLE
Les multi geométries des zones sensibles ne s'affichént pas sur la carte

### ISSUE THREAD

**Issue by xavyeah39** [GeotrekCE/Geotrek-rando-v3#655]
Avec @thomaspnrhj, on remarque dans la v3.8.2 que les géométries multiples (multi-polygones) de nos zones sensibles (issues de BiodivSport via synchro côté admin) ne s'affichent pas sur la carte des fiches rando.

Toutes les ZS intersectées sont bien listées mais seules celles qui ont des geom simples remontent sur la carte : 

![image](https://user-images.githubusercontent.com/16793813/170039335-e42d37c1-8f5b-4229-ba46-c87be676a25f.png)

Après une petite recherche sur le dépôt on se disait que cela était peut-être lié à #616 et #629 mais comme cela a été traité en 3.8.2...

C'est peut-être un autre sujet mais ce qui nous a permis d'identifié ce soucis c'est que certaines fiches rando ne s'ouvraient pas du tout sur la v3 (ces mêmes fiches rando dont le tracé intersecte des ZS en multi-polygone...). 
Nous avions cette erreur 500 :  

![image](https://user-images.githubusercontent.com/16793813/170043230-dbd31e91-f7d4-4081-82d9-8f9f5059dd58.png)

En creusant un peu, nous avons essayé de modifié la valeur du paramètre de conf SENSITIVE_AREA_INTERSECTION_MARGIN dans geotrek-admin car sa valeur était de 0. Nous l'avons passé à 5. De là, l'erreur de chargement disparait et les pages de ces fiches rando s'affichent correctement. Mais sans les ZS en multigeom sur la carte :(

Merci d'avance pour votre aide :)

**Comment by camillemonchicourt** [comment]
OK le deuxième sujet est un autre sujet à creuser en effet.

**Comment by camillemonchicourt** [comment]
Dans la version 3.8.4 les zones sensibles dont la géométrie est de type multi-polygone sont affichés sur la carte.
Pour le second sujet, il faudra préciser et voir ça au niveau de Geotrek-admin ou Geotrek-rando selon l'origine du soucis.
