### ISSUE TITLE
Geotrek-Rando 3.8.3 - Problème accès randos (Error 404)

### ISSUE THREAD

**Issue by Chrispnv** [GeotrekCE/Geotrek-rando-v3#660]
Bonjour,

J'ai mis à jour Geotrek-Rando (3.5.3 -> 3.8.3, en regardant s'il y avait des maj intermédiaires à faire, a priori non) en suivant la documentation, donc en créant un répertoire correspondant à la dernière version de Geotrek-Rando, la 3.8.3 dans lequel j'ai mis l'installeur 2.0.1 et en lançant les commandes docker docker-compose pull && docker-compose down && docker-compose up -d. J'ai récupéré les répertoires customisation et medias.
Tout se passe bien. J'ai bien la page d'accueil contenant entre autre les randos mises en avant. Quand on clique sur le bouton pour aller sur les randos et quitter la page d'accueil, tout se passe bien, on arrive sur la carte globale avec toutes les randos.
Par contre quand on clique sur une rando depuis les randos mises en avant dans la page d'accueil ou depuis la carte générale, on arrive sur une erreur 404 (not found). 
Je n'ai rien trouvé dans les logs, l'url des randos est la même que dans la version 3.5.3.
Avez vous une idée du problème ?

Merci.

**Comment by camillemonchicourt** [comment]
OK donc ta mise à jour en version 3.8.3 semble s'être bien passée.
Par contre, je n'ai jamais eu moi-même ni eu écho de soucis d'URL.
Peux-tu donner des précisions ?

De quelle forme est l'URL des randos qui sont en 404 ?
Comment est ta configuration de Geotrek-rando-v3 ?

Et éventuellement si tu as d'autres erreurs dans la console du navigateur quand tu accèdes à la fiche d'une rando ?

Si tu as l'URL de ce serveur, c'est encore mieux ?

**Comment by Chrispnv** [comment]
Salut Camille,

Je n'ai pas de message dans la console du débuggueur Chrome, je n'ai pas d'erreurs dans les logs de NGINX sur mon serveur Geotrek-Rando.
Est ce que cela pourrait venir d'images docker qui pourraient faire le bazar avec le docker courant pour la 3.8.3 ?

Je n'ai pas testé toutes les randos, mais celles testées sont en erreur 404.
Exemple : Rando Autour de Polset -> url = https://randov3.vanoise.com/trek/2559-Autour-de-Polset

Url de Geotrek Rando v3 du PNV = https://randov3.vanoise.com

Tu me demandes comment est ma configuration de Geotrek-rando-v3, quels éléments tu veux que je te donne ?

Merci.

**Comment by camillemonchicourt** [comment]
OK à première vue je ne vois pas d'où peut venir le soucis en effet.

Mais si tu peux indiquer le contenu de tes fichiers : 
- customization/config/global.json
- customization/config/redirects.json (si tu en as un)

**Comment by camillemonchicourt** [comment]
Fixé dans la version 3.8.4 qui permet d'afficher les pages détail des randos, même si ton Geotrek-admin est dans une version ancienne qui n'a pas la route des signalétiques (/signages/) disponible.
Et qui gère aussi mieux le cas où une rando n'a pas de lien web associé.

**Comment by camillemonchicourt** [comment]
Nickel
