### ISSUE TITLE
Sites outdoor et communes / Les afficher toutes

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#669]
Actuellement dans les cards de résultats (home et search) on affiche une commune au-dessus du titre de l'objet.

Pour les randos on affiche la commune du point de départ donc c'est cohérent, pour les services et événements, ce sont quasiment tout le temps des points donc on n'a qu'une commune et ça fonctionne bien.

Mais les sites outdoor sont souvent des polygones. Dans ce cas, on n'affiche qu'une seule commune, la première renvoyée par l'API et là ce n'est pas pertinent voire problématique.

La proposition est donc d'afficher toutes les communes du site Outdoor séparées par une virgule, au-dessus de son nom. Il y en aura souvent qu'une, parfois 2, je pense pas ou rarement 3.
C'est le cas sur la HOME dans les suggestion, sur la page recherche dans la liste de résultats et dans les tooltips (survol et clic) de la carte, sur la page détail au-dessus du nom du site, ainsi que dans la liste des sous-sites ("Lieux de pratiques") que l'on peut voir ici : https://gtr3demo.ecrins-parcnational.fr/outdoor-site/84-Test-d-un-site

**Comment by JordaneNS** [comment]
Ok c'est fait et testable sur la demo ([https://demo.geotrekrando.natural-solutions.eu/search?outdoorPractice=2](url))

**Comment by camillemonchicourt** [comment]
Fait avec https://github.com/GeotrekCE/Geotrek-rando-v3/pull/690

Dans la plupart du temps, on n'aura qu'une ou 2 communes.

![image](https://user-images.githubusercontent.com/99249234/173102193-fc2b23e9-1647-4439-8a44-b4e51a748927.png)

![image](https://user-images.githubusercontent.com/99249234/173102265-ce2466d7-7c60-402b-834b-74d87ef5dd57.png)

![image](https://user-images.githubusercontent.com/99249234/173102363-d13b36da-b7a2-481a-8504-ce9af9046d3c.png)

![image](https://user-images.githubusercontent.com/99249234/173102438-3471f166-af1e-4508-aa0c-3a98a2c4ca2b.png)

**Comment by camillemonchicourt** [comment]
Fait dans la 3.9.0.
