### ISSUE TITLE
Dysfonctionnement du widget météo sur iOS

### ISSUE THREAD

**Issue by xavyeah39** [GeotrekCE/Geotrek-rando-v3#685]
Déjà évoqué dans une autre issue (#645 ), le wisget méto ne fonctionne pas comme il devrait sur iOS.
Testé et reproduit sur différents modèles d'iphone, ipad et versions d'iOS (v15+)

![IMG_0552](https://user-images.githubusercontent.com/16793813/172579108-a3a6d9e4-e91c-4788-8cae-4d8472e3af1a.jpg)

**Comment by noelmartinon** [comment]
Ce n'est pas seulement sur IOS car je constate la même chose sur une installation effectuée sur serveur linux.
Comme mentionné sur la page https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/presentation-fr.md c'est "basé sur la commune de départ de la randonnée" mais je n'ai pas investigué pour savoir par quel biais.
Ayant regardé sur https://meteofrance.com/widgets, en tout cas le paramètre passé à l'URL https://meteofrance.com/widget/prevision/XXXXXXX ne correspond pas au code postal de la commune. Peut-être une piste ?

**Comment by camillemonchicourt** [comment]
iOS n'est pas par rapport au serveur, mais le téléphone sur lequel le site est consulté.
@noelmartinon, tu constates le soucis sur un téléphone qui n'est pas sur iOS ?

De mon côté, pas de soucis avec l'affichage du widget météo sur un téléphone Android ou sur PC.

Si vous avez des URL pour préciser le soucis, je suis preneur.

**Comment by noelmartinon** [comment]
Désolé pour le pb de compréhension.
En fait, je n'ai pas testé sur IOS mais j'ai le souci sur tous les navigateurs des clients Windows, Linux et Android et ça vient du serveur uniquement.

Dans le code, j'ai vu que l'URL était https://meteofrance.com/widget/prevision/${code}0 et c'est ce suffixe 'zero' qui induit l'erreur. Suite à quelques recherches et vérifié après reboot, j'ai appliqué une solution ponctuelle et partielle :
Dans mon fichier docker ./app/src/.next/static/chunks/412-56563f62d5e9a77e.js, en modifiant src:"https://meteofrance.com/widget/prevision/".concat(t,"0") par src:"https://meteofrance.com/widget/prevision/".concat(t,"") alors j'ai la météo en grande partie des sentiers mais pas partout.

Notre site V3 n'étant pas encore validé pour être public, je ne peux pas donner de liens dans ce post. Je ferai un envoi en msg privé.

**Comment by camillemonchicourt** [comment]
L'ajout du 0 est nécessaire, du moins dans certains cas.
En fait, on prend la commune de départ, et on utilise son code INSEE pour la passer dynamiquement au widget Météo France : https://meteofrance.com/widgets

En testant différentes communes, on voit que cela ne colle pas forcément bien dans tous les cas.
Je ne vois pas bien comment on peut construire correctement et dynamiquement le code du widget à partir des codes INSEE.

Sur Rando Ecrins, cela fonctionne bien sur toutes les randos : https://rando.ecrins-parcnational.fr/

Dans tous les cas, il est possible de désactiver le widget METEO si celui-ci pose trop de soucis : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/config/global.json#L23

**Comment by babastienne** [comment]
En effet le widget peut poser problème avec le code, en particulier pour les dom-tom car dans ce cas le suffixe '0' ne doit pas être ajouté. Comme ce widget n'est de toute manière pas généralisable à grande échelle (international), je pense qu'il faudrait à terme le retirer du périmètre "par défaut" de Geotrek pour que seuls les territoires qui souhaitent l'utiliser puisse l'ajouter en surcharge (comme pour les [widgets qualité de l'air](https://github.com/GeotrekCE/Geotrek-rando-v3/issues/914)).

En attendant, dans Geotrek-Rando-V3, il est possible de désactiver le widget Météo mais également d'ajouter des scripts en surcharge si une autre intégration de widget météo est souhaitée.
