### ISSUE TITLE
Geotre-Rando 3.8.5 - Filtre sur communes ne fonctionne pas

### ISSUE THREAD

**Issue by Chrispnv** [GeotrekCE/Geotrek-rando-v3#686]
Bonjour,

J'ai installé la 3.8.5 pour le fix sur le filtre sur les localisations.
Donc maintenant les filtres de localisation s'affiche dans le filtre 'Localisation'. il fonctionne pour Structure. Il ne fonctionne pas pour les communes. J'ai bien la liste des communes, mais il y a une erreur qui ne renvoie aucune rando sur la commune sélectionnée.
Voici ce que j'ai dans le débuggueur Chrome.

Access to fetch at 'https://adminrando.vanoise.com/api/v2/trek/?fields=id&language=fr&page_size=1&page=1&practices=4&cities=73157&in_bbox=5.940856933593751,45.15008475740563,7.259216308593751,45.6082735094011' (redirected from 'https://adminrando.vanoise.com/api/v2/trek?fields=id&language=fr&page_size=1&page=1&practices=4&cities=73157&in_bbox=5.940856933593751,45.15008475740563,7.259216308593751,45.6082735094011') from origin 'https://randov3.vanoise.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
5The FetchEvent for "<URL>" resulted in a network error response: the promise was resolved with an error response object.
connector.ts:309 Error in connector / results TypeError: Cannot read properties of undefined (reading 'data')
    at api.ts:25:12
    at async Promise.all (/index 0)
(anonymous) @ connector.ts:309
s @ runtime.js:45
(anonymous) @ runtime.js:274
S.forEach.e.<computed> @ runtime.js:97
w @ 331-a28b5b81abbc60fe.js:1
u @ 331-a28b5b81abbc60fe.js:1
Promise.then (async)
w @ 331-a28b5b81abbc60fe.js:1
a @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ useTrekResults.ts:76
S @ infiniteQueryBehavior.js:41
t.fetchFn @ infiniteQueryBehavior.js:57
c @ retryer.js:90
l @ retryer.js:150
e.fetch @ query.js:295
n.executeFetch @ queryObserver.js:191
n.setOptions @ queryObserver.js:85
n.setOptions @ infiniteQueryObserver.js:26
(anonymous) @ useBaseQuery.js:72
Ii @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gt @ react-dom.production.min.js:73
query.js:320 TypeError: Cannot read properties of undefined (reading 'data')
    at api.ts:25:12
    at async Promise.all (/index 0)
onError @ query.js:320
d @ retryer.js:62
(anonymous) @ retryer.js:126
Promise.catch (async)
c @ retryer.js:110
l @ retryer.js:150
e.fetch @ query.js:295
n.executeFetch @ queryObserver.js:191
n.setOptions @ queryObserver.js:85
n.setOptions @ infiniteQueryObserver.js:26
(anonymous) @ useBaseQuery.js:72
Ii @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gt @ react-dom.production.min.js:73
xhr.js:210          GET https://adminrando.vanoise.com/api/v2/trek?fields=id&language=fr&page_size=1&page=1&practices=4&cities=73157&in_bbox=5.940856933593751,45.15008475740563,7.259216308593751,45.6082735094011 net::ERR_FAILED
(anonymous) @ xhr.js:210
e.exports @ xhr.js:15
e.exports @ dispatchRequest.js:56
l.request @ Axios.js:112
r.forEach.l.<computed> @ Axios.js:136
(anonymous) @ bind.js:9
s @ api.ts:24
(anonymous) @ connector.ts:103
s @ runtime.js:45
(anonymous) @ runtime.js:274
S.forEach.e.<computed> @ runtime.js:97
w @ 331-a28b5b81abbc60fe.js:1
a @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ useTrekResults.ts:76
S @ infiniteQueryBehavior.js:41
t.fetchFn @ infiniteQueryBehavior.js:57
c @ retryer.js:90
l @ retryer.js:150
e.fetch @ query.js:295
n.executeFetch @ queryObserver.js:191
n.setOptions @ queryObserver.js:85
n.setOptions @ infiniteQueryObserver.js:26
(anonymous) @ useBaseQuery.js:72
Ii @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gt @ react-dom.production.min.js:73
Show 12 more frames
Access to fetch at 'https://adminrando.vanoise.com/api/v2/trek/?language=fr&page_size=250&practices=4&cities=73157&fields=id,departure_geom,practice' (redirected from 'https://adminrando.vanoise.com/api/v2/trek?language=fr&page_size=250&practices=4&cities=73157&fields=id,departure_geom,practice') from origin 'https://randov3.vanoise.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
connector.ts:180 Error in connector / mapResults TypeError: Cannot read properties of undefined (reading 'data')
    at api.ts:12:12
(anonymous) @ connector.ts:180
s @ runtime.js:45
(anonymous) @ runtime.js:274
S.forEach.e.<computed> @ runtime.js:97
yn @ 331-a28b5b81abbc60fe.js:1
u @ 331-a28b5b81abbc60fe.js:1
Promise.then (async)
yn @ 331-a28b5b81abbc60fe.js:1
a @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ useMapResults.ts:30
fetchFn @ query.js:264
c @ retryer.js:90
l @ retryer.js:150
e.fetch @ query.js:295
n.executeFetch @ queryObserver.js:191
n.setOptions @ queryObserver.js:85
(anonymous) @ useBaseQuery.js:72
Ii @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gt @ react-dom.production.min.js:73
xhr.js:210          GET https://adminrando.vanoise.com/api/v2/trek?language=fr&page_size=250&practices=4&cities=73157&fields=id,departure_geom,practice net::ERR_FAILED
(anonymous) @ xhr.js:210
e.exports @ xhr.js:15
e.exports @ dispatchRequest.js:56
l.request @ Axios.js:112
r.forEach.l.<computed> @ Axios.js:136
(anonymous) @ bind.js:9
mn @ api.ts:11
(anonymous) @ connector.ts:74
s @ runtime.js:45
(anonymous) @ runtime.js:274
S.forEach.e.<computed> @ runtime.js:97
yn @ 331-a28b5b81abbc60fe.js:1
a @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ useMapResults.ts:30
fetchFn @ query.js:264
c @ retryer.js:90
l @ retryer.js:150
e.fetch @ query.js:295
n.executeFetch @ queryObserver.js:191
n.setOptions @ queryObserver.js:85
(anonymous) @ useBaseQuery.js:72
Ii @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gt @ react-dom.production.min.js:73
Show 10 more frames
Access to fetch at 'https://adminrando.vanoise.com/api/v2/trek/?language=fr&page_size=250&practices=4&cities=73157&fields=id,departure_geom,practice' (redirected from 'https://adminrando.vanoise.com/api/v2/trek?language=fr&page_size=250&practices=4&cities=73157&fields=id,departure_geom,practice') from origin 'https://randov3.vanoise.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
connector.ts:180 Error in connector / mapResults TypeError: Cannot read properties of undefined (reading 'data')
    at api.ts:12:12
(anonymous) @ connector.ts:180
s @ runtime.js:45
(anonymous) @ runtime.js:274
S.forEach.e.<computed> @ runtime.js:97
yn @ 331-a28b5b81abbc60fe.js:1
u @ 331-a28b5b81abbc60fe.js:1
Promise.then (async)
yn @ 331-a28b5b81abbc60fe.js:1
a @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ useMapResults.ts:30
fetchFn @ query.js:264
c @ retryer.js:90
(anonymous) @ retryer.js:143
Promise.then (async)
(anonymous) @ retryer.js:139
Promise.catch (async)
c @ retryer.js:110
l @ retryer.js:150
e.fetch @ query.js:295
n.executeFetch @ queryObserver.js:191
n.setOptions @ queryObserver.js:85
(anonymous) @ useBaseQuery.js:72
Ii @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gt @ react-dom.production.min.js:73
xhr.js:210          GET https://adminrando.vanoise.com/api/v2/trek?language=fr&page_size=250&practices=4&cities=73157&fields=id,departure_geom,practice net::ERR_FAILED
(anonymous) @ xhr.js:210
e.exports @ xhr.js:15
e.exports @ dispatchRequest.js:56
l.request @ Axios.js:112
r.forEach.l.<computed> @ Axios.js:136
(anonymous) @ bind.js:9
mn @ api.ts:11
(anonymous) @ connector.ts:74
s @ runtime.js:45
(anonymous) @ runtime.js:274
S.forEach.e.<computed> @ runtime.js:97
yn @ 331-a28b5b81abbc60fe.js:1
a @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ useMapResults.ts:30
fetchFn @ query.js:264
c @ retryer.js:90
(anonymous) @ retryer.js:143
Promise.then (async)
(anonymous) @ retryer.js:139
Promise.catch (async)
c @ retryer.js:110
l @ retryer.js:150
e.fetch @ query.js:295
n.executeFetch @ queryObserver.js:191
n.setOptions @ queryObserver.js:85
(anonymous) @ useBaseQuery.js:72
Ii @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gt @ react-dom.production.min.js:73
Access to fetch at 'https://adminrando.vanoise.com/api/v2/trek/?language=fr&page_size=250&practices=4&cities=73157&fields=id,departure_geom,practice' (redirected from 'https://adminrando.vanoise.com/api/v2/trek?language=fr&page_size=250&practices=4&cities=73157&fields=id,departure_geom,practice') from origin 'https://randov3.vanoise.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
connector.ts:180 Error in connector / mapResults TypeError: Cannot read properties of undefined (reading 'data')
    at api.ts:12:12
(anonymous) @ connector.ts:180
s @ runtime.js:45
(anonymous) @ runtime.js:274
S.forEach.e.<computed> @ runtime.js:97
yn @ 331-a28b5b81abbc60fe.js:1
u @ 331-a28b5b81abbc60fe.js:1
Promise.then (async)
yn @ 331-a28b5b81abbc60fe.js:1
a @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ useMapResults.ts:30
fetchFn @ query.js:264
c @ retryer.js:90
(anonymous) @ retryer.js:143
Promise.then (async)
(anonymous) @ retryer.js:139
Promise.catch (async)
c @ retryer.js:110
(anonymous) @ retryer.js:143
Promise.then (async)
(anonymous) @ retryer.js:139
Promise.catch (async)
c @ retryer.js:110
l @ retryer.js:150
e.fetch @ query.js:295
n.executeFetch @ queryObserver.js:191
n.setOptions @ queryObserver.js:85
(anonymous) @ useBaseQuery.js:72
Ii @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gt @ react-dom.production.min.js:73
xhr.js:210          GET https://adminrando.vanoise.com/api/v2/trek?language=fr&page_size=250&practices=4&cities=73157&fields=id,departure_geom,practice net::ERR_FAILED
(anonymous) @ xhr.js:210
e.exports @ xhr.js:15
e.exports @ dispatchRequest.js:56
l.request @ Axios.js:112
r.forEach.l.<computed> @ Axios.js:136
(anonymous) @ bind.js:9
mn @ api.ts:11
(anonymous) @ connector.ts:74
s @ runtime.js:45
(anonymous) @ runtime.js:274
S.forEach.e.<computed> @ runtime.js:97
yn @ 331-a28b5b81abbc60fe.js:1
a @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ useMapResults.ts:30
fetchFn @ query.js:264
c @ retryer.js:90
(anonymous) @ retryer.js:143
Promise.then (async)
(anonymous) @ retryer.js:139
Promise.catch (async)
c @ retryer.js:110
(anonymous) @ retryer.js:143
Promise.then (async)
(anonymous) @ retryer.js:139
Promise.catch (async)
c @ retryer.js:110
l @ retryer.js:150
e.fetch @ query.js:295
n.executeFetch @ queryObserver.js:191
n.setOptions @ queryObserver.js:85
(anonymous) @ useBaseQuery.js:72
Ii @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gt @ react-dom.production.min.js:73
Access to fetch at 'https://adminrando.vanoise.com/api/v2/trek/?language=fr&page_size=250&practices=4&cities=73157&fields=id,departure_geom,practice' (redirected from 'https://adminrando.vanoise.com/api/v2/trek?language=fr&page_size=250&practices=4&cities=73157&fields=id,departure_geom,practice') from origin 'https://randov3.vanoise.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
connector.ts:180 Error in connector / mapResults TypeError: Cannot read properties of undefined (reading 'data')
    at api.ts:12:12
(anonymous) @ connector.ts:180
s @ runtime.js:45
(anonymous) @ runtime.js:274
S.forEach.e.<computed> @ runtime.js:97
yn @ 331-a28b5b81abbc60fe.js:1
u @ 331-a28b5b81abbc60fe.js:1
Promise.then (async)
yn @ 331-a28b5b81abbc60fe.js:1
a @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ 331-a28b5b81abbc60fe.js:1
(anonymous) @ useMapResults.ts:30
fetchFn @ query.js:264
c @ retryer.js:90
(anonymous) @ retryer.js:143
Promise.then (async)
(anonymous) @ retryer.js:139
Promise.catch (async)
c @ retryer.js:110
(anonymous) @ retryer.js:143
Promise.then (async)
(anonymous) @ retryer.js:139
Promise.catch (async)
c @ retryer.js:110
(anonymous) @ retryer.js:143
Promise.then (async)
(anonymous) @ retryer.js:139
Promise.catch (async)
c @ retryer.js:110
l @ retryer.js:150
e.fetch @ query.js:295
n.executeFetch @ queryObserver.js:191
n.setOptions @ queryObserver.js:85
(anonymous) @ useBaseQuery.js:72
Ii @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gt @ react-dom.production.min.js:73
query.js:320 TypeError: Cannot read properties of undefined (reading 'data')
    at api.ts:12:12
onError @ query.js:320
d @ retryer.js:62
(anonymous) @ retryer.js:126
Promise.catch (async)
c @ retryer.js:110
(anonymous) @ retryer.js:143
Promise.then (async)
(anonymous) @ retryer.js:139
Promise.catch (async)
c @ retryer.js:110
(anonymous) @ retryer.js:143
Promise.then (async)
(anonymous) @ retryer.js:139
Promise.catch (async)
c @ retryer.js:110
(anonymous) @ retryer.js:143
Promise.then (async)
(anonymous) @ retryer.js:139
Promise.catch (async)
c @ retryer.js:110
l @ retryer.js:150
e.fetch @ query.js:295
n.executeFetch @ queryObserver.js:191
n.setOptions @ queryObserver.js:85
(anonymous) @ useBaseQuery.js:72
Ii @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$l @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Or @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gt @ react-dom.production.min.js:73
xhr.js:210          GET https://adminrando.vanoise.com/api/v2/trek?language=fr&page_size=250&practices=4&cities=73157&fields=id,departure_geom,practice net::ERR_FAILED

Est ce un soucis avec ma "vieille" version de Geotrek Admin ? A un moment on avait des problème avec CORS, mais c'était quand on cliquait sur une rando.

Merci.

**Comment by camillemonchicourt** [comment]
Salut, pas de soucis sur Rando Ecrins : https://rando.ecrins-parcnational.fr/search?practices=4&cities=05029,05046

Vous avez en effet un problème au niveau de Geotrek-admin.
On voit que l'appel qui est fait à l'API renvoie une erreur 500 : https://adminrando.vanoise.com/api/v2/trek/?language=fr&page_size=250&practices=4&cities=73157&fields=id,departure_geom,practice
Dans votre Geotrek-admin n'arrive pas à faire un filtre par commune.
Il faudrait voir l'erreur qui est renvoyée au niveau de Geotrek-admin ou de PostgreSQL quand on appelle cette route.
Je vois pas d'évolution récente de ce volet dans Geotrek-admin, mais peut-être que j’ai zappé quelque chose. Ou sinon un soucis au niveau de vos communes, au niveau de leur géométrie ou autre.

**Comment by Chrispnv** [comment]
Est ce que c'est pas plutôt un problème avec CORS "...has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."
Blaise avait eu ce genre de problème quand on cliquait sur une rando.
Est ce qu'il y aurait une manip à lancer ? une config à mettre en place ?
Merci.

**Comment by camillemonchicourt** [comment]
Je ne pense pas, car comme je disais la route appelée avec le filtre par commune renvoie une erreur 500. Donc c'est le filtre par commune des itinéraires qui a un soucis chez vous.
Et c'est pour ça que ça renvoie une erreur de CORS. Car la route renvoie une erreur 500...

**Comment by Chrispnv** [comment]
Ok.
J'ai testé cet url "https://adminrando.vanoise.com/api/v2/trek/?language=fr&page_size=250&practices=4&cities=73071" prise de l'url qui ressort en erreur "https://adminrando.vanoise.com/api/v2/trek/?language=fr&page_size=250&practices=4&cities=73071&fields=id,departure_geom,practice" en otant la fin.

Si je comprends bien et en toute logique, je devrais obtenir un json avec la liste des rando filtrées avec les critères passés dans l'url, donc est ce que "https://adminrando.vanoise.com/api/v2/trek/?language=fr&page_size=250&practices=4&cities=73071" devrait me renvoyer quelque chose. J'obtiens une erreur 500.

**Comment by camillemonchicourt** [comment]
Oui c'est bien ce que j'ai indiqué.
Ton Geotrek-admin n'arrive pas à filtrer par commune, je ne sais pas pourquoi.
Il faut regarder dans les logs de Geotrek-admin (https://geotrek.readthedocs.io/en/2.82.2/install/troubleshooting.html) et/ou dans les logs PostgreSQL, pas dans les logs NGINX.
L'intersection entre tes itinéraires et tes communes a un soucis, je ne sais pas pourquoi.
Même soucis quand on cherche à filtrer les services par commune : https://randov3.vanoise.com/search?categories=1&cities=73157

Je pense à un soucis au niveau de ta BDD ou des géométries des communes, mais il faut voir les logs.
Peut-être que la MAJ de ton Geotrek-admin aiderait ou solutionnerait ça, mais je ne vois pas en quoi.

**Comment by Chrispnv** [comment]
J'ai fait des test d'url avec l'api geotrek v2
Exemple
https://adminrando.vanoise.com/api/v2/trek/?cities=73023 => Error 500
J'ai regardé la doc de l'API, j'ai vu city
https://adminrando.vanoise.com/api/v2/trek/?city=73023 => j'obtiens un json contenant les rando sur la commune avec cet id

J'ai testé avec l'url qui était en erreur en changeant cities par city => https://adminrando.vanoise.com/api/v2/trek/?language=fr&page_size=250&practices=4&city=73071&fields=id,departure_geom,practice => J'obtiens un json

Je pense qu'il y a un discordance entre l'api et ma BDD. Je n'ai pas trouvé  de champ city ou cities dans ma bdd.

Est ce que c'est une piste ? Est ce que je suis dans le faux ?
Est ce que cela milite pour que je mettre à jour rapidement mon Geotrek-Admin ?

**Comment by camillemonchicourt** [comment]
Oui très bonne piste.
Il est possible que le filtre ``cities`` se nommait au préalable ``city`` et ne permettait de filtrer qu'une seule commune à la fois.
Je n'ai pas souvenir de ça, mais c'est une bonne piste.
Si c'est le cas, en effet c'est la mise à jour de Geotrek-admin qui sera l'unique solution.

Si tu activais la documentation de votre API, cela aiderait à voir son fonctionnement, le nom de ses filtres, etc : https://geotrek.readthedocs.io/en/master/install/advanced-configuration.html#swagger

Ça permet d'avoir cette interface de test et documentation de l'API : https://geotrekdemo.ecrins-parcnational.fr/api/v2/

**Comment by camillemonchicourt** [comment]
En regardant ce que tu as indiqué, je pense qu'il y a une incompréhension.
La route https://adminrando.vanoise.com/api/v2/trek/?city=73023 ne renvoie pas les randos de cette commune, mais bien toutes les randos (``"count":207``).
Quand on filtre l'API avec un paramètre qui n'existe pas, il est ignoré.
Donc c'est seulement que le filtre ``city`` n'existe pas qui t'a induit en erreur.

**Comment by Chrispnv** [comment]
Salut,
OK je vois.
La mise à jour de Geotrek-Admin en 2.83.0 a résolu le problème.
Cela confirme bien le fait d'avoir une version de Geotrek-Admin en adéquation avec Geotrek-Rando.
Maintenant je ne peux ouvrir aucune rando. Les routes ne fonctionne pas.
Je vais regarder. J'espère que je vais pouvoir me passer d'un ticket sur Github.
A+

**Comment by camillemonchicourt** [comment]
Geotrek-admin ne doit pas forcément être à jour dans sa dernière version pour que la dernière version de Geotrek-rando fonctionne.
On fait attention à gérer au mieux possible la rétrocompatibilité.
Et à faire en sorte que si des nouveaux champs de l'API sont utilisées, ils soient ignorés si ils ne sont pas dispos dans l'API.

Donc toute nouvelle version de Geotrek-rando n'impose pas la dernière version de Geotrek-admin.

On indique cela dans les notes de version, soit en indiquant globalement la version minimale nécessaire de Geotrek-admin pour que Geotrek-rando, soit la version nécessaire pour certaines fonctionnalités : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/changelog.md

Actuellement on indique dans la 3.0.0 : 

- Requires Geotrek-admin 2.57.0 minimun, reachable in https

Et dans la 3.5.0 : 

- To enable Outdoor module, Geotrek-admin version 2.70.0 or higher is required
- To display images in Event module, Geotrek-admin version 2.72.0 or higher is required

Je ne comprends pas pourquoi il y a un soucis avec la version 2.59.0 de Geotrek-admin. Quelque chose qui date a du m'échapper.

Dans tous les cas, c'est bien d'avoir son Geotrek-admin et son Geotrek-rando à jour, et on a fait en sorte de simplifier le processus de mise à jour au maximum.

A noter aussi qu'en cas de soucis, il est très simple de revenir à une ancienne version de Geotrek-rando-v3.

**Comment by Chrispnv** [comment]
Ta dernière phrase "A noter aussi qu'en cas de soucis, il est très simple de revenir à une ancienne version de Geotrek-rando-v3." m'amène à une petite question.

J'ai fait fait comme ceci pour switcher d'une version à une autre.
- Dans /home/[user]/[vGTR_courante]/Geotrek-rando-v3-installer-main => ~/.docker/cli-plugins/docker-compose stop
- Dans /home/[user]/[vGTR_ancienne]/Geotrek-rando-v3-installer-main => ~/.docker/cli-plugins/docker-compose start

Est ce la bonne manière d'opérer ?

**Comment by camillemonchicourt** [comment]
OK alors là, je vois pas trop. Là ce que tu fais c'est seulement de stopper et démarrer le Docker. Ça ne va pas revenir à une ancienne version, ni même mettre à jour vers une version plus récente.
Je ne sais pas d'où sortent ces commandes, mais ce ne sont pas celles de la documentation (à privilégier selon moi), que l'on utilise et qui sont plus simples.

Pour redémarrer le Docker, on a une commande dans la documentation (https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/installation.md), qui permet notamment de répercuter les modifications de la configuration : 

> After updating customization, you just have to run ``docker-compose restart`` to apply changes.

Pour mettre à jour Geotrek-rando-v3 vers la dernière version disponible, la documentation (https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/installation.md#upgrade-geotrek-rando-version) indique cette commande : ``docker-compose pull && docker-compose down && docker-compose up -d``

Par contre si tu es en version 3.8.4 par exemple et que tu veux revenir en version 3.7.0 (ou autre), la documentation indique : 

> It will download and install the latest version of Geotrek-rando. If you want to install a specific version of Geotrek-rando, you can specify it in your ``.env`` file, instead of latest.

Par défaut ce fichier ``.env`` indique d'installer à chaque fois la dernière version disponible (``latest``), mais il est donc possible d'y préciser une version spécifique.

Pour créer ce fichier ``.env``, la documentation indique : 

> You can also create the optional ``.env`` file based on the example (``cp .env.example .env``), if you want to change the Docker image URL (or run a specific version different from the latest one), the running port, or the customization and medias folders path. Run ``docker-compose down && docker-compose up -d`` to apply changes to ``.env`` file.
