### ISSUE TITLE
Geotre-Rando 3.8.5 - Non relation entre liste rando et rando sur la carte

### ISSUE THREAD

**Issue by Chrispnv** [GeotrekCE/Geotrek-rando-v3#687]
Bonjour,

Ce problème n'est pas spécifique à la 3.8.5. on l'avait déjà sur le 3.5.3.
Quand on restreint le nombre de rando sur la carte, le filtre ne s'applique pas sur la liste des randos sur la gauche, le nombre de randos total reste inchangé. Il y a bien un appel à la base de données (picto de chargement apparait), mais le nombre de randos affichées ne change pas.
Je ne trouve pas d'erreur pour étayer le problème.

Merci.

**Comment by camillemonchicourt** [comment]
Tu n'aurais pas ce paramètre à ``false`` : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/customization/config/global.json#L20 ?

Sinon à voir si ce n'est pas un soucis au niveau de Geotrek-admin qui n'arrive pas à filtrer les contenus en fonction de la zone affichée, comme sur https://github.com/GeotrekCE/Geotrek-rando-v3/issues/686, mais j'en doute.

**Comment by Chrispnv** [comment]
enableSearchByMap est bien à true.
Il est possible que le problème soit le même que pour le #686 mais sans message d'erreur. Je n'ai rien trouvé dans les logs coté GT Rando et GT Admin sur Nginx

**Comment by camillemonchicourt** [comment]
Corrigé avec la MAJ de Geotrek-admin.
