### ISSUE TITLE
Nouveau Geotrek rando v3 dans les Pyrénées-Atltantiques

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#688]
Bonjour,
Je ne sais pas où poster cette information mais je voulais vous annoncer que le site [nature64.fr](https://nature64.fr) est officiellement en ligne.
Pour le moment seules les données rando départementales sont en ligne. 
Par la suite nous allons ajouter les différentes pratiques outdoor ainsi que les données des collectivités qui souhaiteront se joindre à nous.
J'en profite pour remercier toute la communauté qui a toujours été très réactive notamment @camillemonchicourt  que je ne cesse de solliciter ainsi que Makina Corpus et plus particulièrement Bastien Potiron et Timothée de Montety qui ont toujours su régler nos problèmes et répondre à nos attentes notamment avec la création du parser permettant l'import des données depuis Tourinsoft.
Bonne journée à tous.

**Comment by babastienne** [comment]
Bonjour Audrey.
Merci beaucoup, très content que votre site soit en ligne et fonctionnel, c'est l'aboutissement d'un joli projet. :tada: 

Si vous souhaitez faire la promotion de vote site auprès des autres territoires utilisant Geotrek je vous invite à envoyer un mail sur la mailing liste Geotrek qui est généralement utilisée pour ce genre d'annonces : https://groups.google.com/g/geotrek-fr

Github étant plus utilisé pour l'aspect technique il y a assez peu de membres de la communauté actifs ici.

Bonne journée et à bientôt,

**Comment by camillemonchicourt** [comment]
Super pour la mise en ligne.
Oui n'hésite pas à faire cette même info sur la liste de diffusion qui est adaptée à cela et touchera plus de monde.
Merci.

**Comment by AudreyRemy** [comment]
@camillemonchicourt c'est fait
