### ISSUE TITLE
Geotrek-Rando 3.8.3 - Problème accès randos (suite #660, #686 et #687)

### ISSUE THREAD

**Issue by Chrispnv** [GeotrekCE/Geotrek-rando-v3#692]
Bonjour,
Après avoir installé Geotrek-Rando 3.8.5 et Geotrek-Admin 2.83.0 pour que les 2 systèmes soient raccord et corrigent les filtres sur Geotrek-Rando, je retrouve des erreurs d'accès aux randos quelle que soit la manière d'y arriver.
A priori comme pour les problèmes avec les filtres, les routes n'aboutissent pas.

Access to fetch at 'https://adminrando.vanoise.com/api/v2/informationdesk/?language=fr&fields=id,name,street,postal_code,municipality,website,email,phone,description,photo_url,type,accessibility,latitude,longitude' (redirected from 'https://adminrando.vanoise.com/api/v2/informationdesk?language=fr&fields=id,name,street,postal_code,municipality,website,email,phone,description,photo_url,type,accessibility,latitude,longitude') from origin 'https://randov3.vanoise.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

J'ai regardé les troubleshooting coté Geotrek-Admin, notamment sur la colonne Language.
J'ai relancé le migrate qui m'a dit que l'environnement était à jour. J'ai essayé de lancer les commandes geotrek sync_translation_fields, geotrek update_translation_fields, geotrek update_geotrek_permissions, geotrek update_post_migration_languages mais je ne les ai pas.

Donc je suis de nouveau bloqué. Dur dur !

Merci de votre aide.

**Comment by camillemonchicourt** [comment]
Ça ressemble au même soucis qu'Amandine : https://github.com/GeotrekCE/Geotrek-admin/issues/3135.
C'est bien au niveau de Geotrek-admin.

Je pense que c'est en lien avec cette évolution faite dans la version 2.83.0 : https://github.com/GeotrekCE/Geotrek-admin/issues/3095
Et que le cas où le module Outdoor n'est pas installé au niveau de Geotrek-admin n'a pas été prévu.

Car j'ai pas le soucis sur mon serveur de DEMO ni de production.

**Comment by Chrispnv** [comment]
Tu as une idée de poste de résolution ? Une idée de ce que je pourrais faire ? La mise en prod est sensée être imminente.

**Comment by noelmartinon** [comment]
Bonjour,
Même pb de mon côté constaté avec rando 2.8.2 et 2.8.5 et ça vient bien de geotrek-admin 2.83.0

**Comment by Chrispnv** [comment]
Bonjour,

J'ai appliqué la correction n°1, c'est à dire sur le fichier filters.py avec redémarrage Geotrek-Admin (sudo service geotrek restart)

Cela nous permet à priori d'avoir une environnement fonctionnel global (Geotrek-Admin et Geotrek-Rando). En tout cas la partie Geotrek-Rando fonctionne. Il faut que je regarde encore la partie APIDAE pour les informations sur nos refuges et points d'information.

Merci pour l'aide sur l'ensemble du parcours que je n'aurais pas pu faire tout seul !
