### ISSUE TITLE
Le texte des patrimoines est parfois illisible

### ISSUE THREAD

**Issue by IdrissaD** [GeotrekCE/Geotrek-rando-v3#693]
Sur certains patrimoines dont le texte dépasse la taille de la fenêtre de visualisation, les lignes de celui-ci se retrouvent compressées et en surimpression :
![image](https://user-images.githubusercontent.com/73114156/173553671-a963f498-01ff-40fa-bf35-37608109cbfc.png)

Voir ici : https://rando48-dev.openig.org/trek/802-Canilhac-(variante-courte-par-la-route-)

**Comment by noelmartinon** [comment]
J'avais un pb identique au niveau du texte des "Lieux de renseignement" d'un sentier. Le problème de CSS personnalisé #705 corrigé dans la 3.10.1 me permet maintenant d'appliquer le style suivant et corrige le problème d'affichage :
```
/* Style sur page détails pour éviter superposition textes */
#details_sectionContent div:first-child > div:nth-child(2) > div:nth-of-type(2) > div:first-child {
  display: block;
}
```
Ça peut être une piste en appliquant un style similaire.

**Comment by camillemonchicourt** [comment]
OK, merci pour ce retour.
On va voir pour l'intégrer d'office dans le code de Geotrek-rando-v3 sur les blocs concernés (https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/components/pages/details/components/DetailsSection/DetailsSection.tsx#L35) pour ne pas que chacun ait à se le corriger dans sa surcouche CSS.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 3.10.7.
