### ISSUE TITLE
Trier les événements par date

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-rando-v3#699]
Les événements apparaissent dans la liste triée par ordre alphabétique. Ce serait plus pertinent pour l'utilisateur que l'ordre soit par date de début.

**Comment by camillemonchicourt** [comment]
En effet

**Comment by dtrucs** [comment]
C'est désormais ok pour les Geotrek-Rando connectés à des Geotrek Admin > 2.101.0 https://github.com/GeotrekCE/Geotrek-admin/issues/3597
