### ISSUE TITLE
Absence de catégories sur page d'accueil multilingue

### ISSUE THREAD

**Issue by noelmartinon** [GeotrekCE/Geotrek-rando-v3#704]
Bien que les catégories de contenu touristique soient toutes renseignées en multilingues sur geotrek (2.82.2), lorsqu'on change de langue sur rando3 (3.8.5), elles ne s'affichent pas dans la barre de la page d'accueil 'home_activitiesBar' dans les langues autres que FR.
Une idée ?

**Comment by camillemonchicourt** [comment]
Oui c'est car tu ne dois avoir aucun contenu publié dans la langue concernée.
Les catégories ne s'affichent que si elles ont au moins un contenu publié dans la langue utilisée.

**Comment by noelmartinon** [comment]
OK, logique. Merci.
