### ISSUE TITLE
Blocage d’une requête multiorigine (Cross-Origin Request) depuis la mise à jour de Gtk-admin et gtk-rando

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando-v3#715]
Geotrek-admin : 2.84.1
Geotrek-Rando : latest

Depuis la mise à jour de Geotrek admin vers la 2.84.1 ( avec mise à jour de postgresql et de postgis) et la maj de Geotrek rando, j'ai énormément d'erreur de CORS ici : https://rando.tourisme-pyrenees-mediterranee.fr/

J'ai tenté d'installer le module Outdoor(https://github.com/GeotrekCE/Geotrek-rando-v3/issues/692) , de l'activer, le désactiver, j'ai désinstallé et réinstallé Geotrek-Rando, rien n'y fait. Le plus bizarre c'est qu'en regardant les message d'erreurs dans la console, on peut quand même retrouver l'information de l'API. Exemple : 

Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://geotrek.tourisme-pyrenees-mediterranee.fr/media/upload/difficulty-4.svg. Raison : échec de la requête CORS. Code d’état : (null).

Mais en cliquant sur le lien, on obtient bien l'image.

Je soupçonne des problèmes dans la configuration nginx, je peux la partager si besoin.

**Comment by camillemonchicourt** [comment]
Je ne vois pas d'erreurs de CORS en navigant sur le site.
Si tu as un des soucis de CORS, c'est donc plutôt au niveau de Geotrek-admin.
Si c'est sur certains médias, alors aucun rapport avec la version de PostGIS ni l'installation du module Outdoor.

Par contre, dans la mises de Geotrek-admin en version 2.84.0, le template de configuration Nginx de GTA a évolué pour optimiser le chargement des geojson et json.
Lors de la mise à jour, je ne sais pas si tu as gardé ton fichier d'origine, ou si tu as écrasé ton template de configuration Nginx (nginx.conf.in) de GTA pour le remplacer par celui fourni par défaut ?
Je recommande fortement de ne pas écraser son template de conf, mais de garder le sien et de répercuter les optimisations.
Dans ce cas, si tu as écrasé ton template de configuration Nginx, alors il faut que tu le reprennes pour remettre ton HTTPS et éventuellement tes ajustements de CORS, etc...

**Comment by mviadere-openig** [comment]
On a regardé ensemble avec Camille, il semblerait qu'il y ait des différence de comportements selon si l'on renseigne le nom exact du portail rando ou que l'on met seulement * pendant le dpkg-reconfigure geotrek-admin. Tout semble fonctionner pour le moment, je clos l'issue.
