### ISSUE TITLE
[Question] Error 500 sur certaines randos avec un nom trop long

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando-v3#717]
Gtk-Rando : latest
Gtk-Admin 2.84.1

Certaines randos sur le randov3 (comme celle-ci : https://rando.tourisme-pyrenees-mediterranee.fr/trek/14539-(E-12-Sentier-Littoralguide-2022)-Reserve-Naturelle-du-Mas-Larrieu---Le-Racou) retourne une error 500 lorsque l'on veut voir la fiche. 

Pourtant la rando remontent bien avec l'api : https://geotrek.tourisme-pyrenees-mediterranee.fr/api/v2/trek/14539/

J'ai proposé à l'OT qui m'a fait remonter le problème de changer le nom de la rando, mais ils l'ont déjà utilisé cet url (et d'autres) pour faire des QRCode pour un guide papier. Est-ce qu'une redirection s'impose dans ce genre de situation ?

**Comment by camillemonchicourt** [comment]
Je ne vois pas de raison qu'un de rando long fasse planter Geotrek-rando-v3.
Je viens de tester sur notre serveur de DEMO en mettant le même nom à une rando, et pas de soucis : https://gtr3demo.ecrins-parcnational.fr/trek/582-(E-12-Sentier-Littoralguide-2022)-Reserve-Naturelle-du-Mas-Larrieu---Le-Racou

Mais en effet, si tu veux changer le nom, pas de soucis. Il suffit de faire une redirection. Tu peux le faire au niveau de Nginx, ou alors du fichier ``redirects.json`` existant dans la configuration de Geotrek-rando-v3 (https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/customization/config/redirects.json)

**Comment by camillemonchicourt** [comment]
En tout cas, ton erreur doit venir d'ailleurs.
Il faudrait voir le log de Geotrek-rando-v3 associé à l'erreur 500.

**Comment by mviadere-openig** [comment]
Voici les logs avec la commande `docker-compose logs -t` :
[error_randov3_270622.log](https://github.com/GeotrekCE/Geotrek-rando-v3/files/8989275/error_randov3_270622.log)

La seule erreur que je comprends est : `TypeError: Cannot read properties of undefined (reading 'pictogram')`. 

Cela voudrait dire qu'il y a un pictogramme utilisé sur la rando qui n'est pas au bon format ? 

Je suis allé voir la rando sur le Geotrek-Admin, effectivement il y a plusieurs soucis (voir image-dessous) : 

 - le profil altimétrique est complètement erroné,
 - les pictogrammes affichés sont en .png et non .svg (ce qui n'est pas bon je suppose)
 
<img width="592" alt="image" src="https://user-images.githubusercontent.com/45095227/175877113-b1d1eebd-add4-47f3-9553-e7d2876f1f03.png">

Je pense que le mieux pour le moment est de demander au référent de retracer l'itinéraire et aussi de changer ses pictogrammes pour les mettre en .svg. D'ailleurs il m'ont fait remarquer que l'url fonctionnait très bien jusqu'à jeudi (jusqu'à ce que je fasse les maj du gtk-admin et gtk-rando donc).

**Comment by camillemonchicourt** [comment]
Le soucis vient du fait qu'il cherche un pictogramme d'un objet et qu'il ne le trouve pas dans l'API.
C'est potentiellement du fait de l'ajout des signalétiques, aménagements publiés et services dans la version 2.84.
Pour ces 3 objets, il utilise un picto par défaut si les catégories n'ont pas de picto dédié.
Si elles ont un picto dédié à la catégorie, alors elles affichent celui-ci.
De mémoire, si le picto est en PNG cela fonctionne quand même.
Mais je vais creuser un peu au niveau de ton API si il manque quelque chose, ou si il y a un cas qu'on n'a pas géré.

**Comment by mviadere-openig** [comment]
Merci Camille pour ton investigation, j'ai fait la mienne de mon côté : 
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/45095227/175946151-ac0820eb-3051-45ad-852a-224dc8c6d732.png">

le type de service avec l'id =4 existe bien dans Geotrek-Admin, et il est  aussi bien présent en BDD : 
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/45095227/175946414-73a153c7-23f7-4679-a2d2-48a56f7fe26b.png">


Ce qui veut dire pour moi qu'il ne remonte plus dans l'API depuis la mise à jour.

**Comment by camillemonchicourt** [comment]
OK donc un soucis d'API.
Mais non, ça ne veut pas dire qu'il remontait avant et ne remonte plus.
C'est juste car on interroge et affiche les services dans GTR que depuis sa version 3.9.0.
Avant on les interrogeait pas et les affichait pas donc le soucis de l'API ne se voyait pas...

A corriger côté GTA donc.

**Comment by camillemonchicourt** [comment]
Oui c'est le plus simple.
En fixant la version à la place de "latest" dans le fichier .env

**Comment by mviadere-openig** [comment]
Très bien, j'ai passé en version 3.8.5, ça fonctionne. 

Je note ici les détails de la manip pour ceux/celles qui en aurait besoin : 

 - Dans le fichier /home/votreutilisateur/Geotrek-rando/.env , changer la ligne  `IMAGE=ghcr.io/geotrekce/geotrek-rando-v3/geotrek-rando:latest` par `IMAGE=ghcr.io/geotrekce/geotrek-rando-v3/geotrek-rando:v3.8.5`
 - puis dans le fichier Geotrek-Rando : entrez cette commande : `docker-compose pull && docker-compose down && docker-compose up -d`

**Comment by IdrissaD** [comment]
> J'ai proposé à l'OT qui m'a fait remonter le problème de changer le nom de la rando, mais ils l'ont déjà utilisé cet url (et d'autres) pour faire des QRCode pour un guide papier. Est-ce qu'une redirection s'impose dans ce genre de situation ?

Je rebondis sur ça vu que ça peut servir à d'autres : dans GTRv3 la seule partie indispensable de l'URL c'est l'id, tout ce que tu peux mettre après est cosmétique. Du coup aucun problème pour changer le nom des itinéraires : tant que l'id ne change pas, les anciennes URL renverront bien vers l'itinéraire actuel.

Exemple : 
https://rando.tourisme-pyrenees-mediterranee.fr/trek/14539-(E-12-Sentier-Littoralguide-2022)-Reserve-Naturelle-du-Mas-Larrieu---Le-Racou
https://rando.tourisme-pyrenees-mediterranee.fr/trek/14539
https://rando.tourisme-pyrenees-mediterranee.fr/trek/14539-(E-12-Sentier-Li
https://rando.tourisme-pyrenees-mediterranee.fr/trek/14539-blabla---fezfzefcezbn'"t"'r'"cfeéc

**Comment by camillemonchicourt** [comment]
Bon OK, on vient de capter.

Les services ont un fonctionnement un peu particulier.
On ne publie pas les services un par un, mais on publie les types de services.

Dans ton cas @mviadere-openig, mais aussi @noelmartinon, vous avez des services associés à des types de service non publiés.

Donc la route /service/ renvoie tous les services saisis, mais pas leurs types de services, car ceux-ci ne sont pas publiés.
Donc ce n'est pas vraiment un bug, mais simplement le fait qu'il faut que vous publiez les types de services pour qu'ils remontent dans la route /service_type/.
Il est possible que la modification ne soit pas prise en compte directement par Geotrek-rando-v3, car celui-ci garde en cache le contenu de certaines routes de l'API pour pas les interroger en permanence.
Pour vider le cache serveur de Geotrek-rando-v3 et que la publication des types de services dans Geotrek-admin soit pris en compte, il faut certainement que vous redémarriez le Docker de Geotrek-rando-v3 avec "docker-compose restart".

Cependant, pour éviter aux autres de passer à côté de cette nuance et être plus cohérent, une évolution va être faite dans la prochaine version de Geotrek-admin pour que la route des services ne renvoie que les services dont le type est publié.
Le soucis sera ainsi évité.

**Comment by noelmartinon** [comment]
Bien vu et merci @camillemonchicourt, ça patch nickel pour moi sur la 3.10.2 ! Plus d'erreur 500 comme j'avais indiqué sur le #718.

**Comment by mviadere-openig** [comment]
Super Camille, merci pour ces retours, je peux donc mettre à jour mes gtk-rando. Je clos l'issue.

**Comment by camillemonchicourt** [comment]
Oui et la version 2.85.0 de Geotrek-admin fait désormais en sorte de ne diffuser que les services dont le type est publié, donc ce soucis ne pourra plus se produire.
