### ISSUE TITLE
Erreur lorsque le nom de l'itinéraire contient une virgule

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-rando-v3#723]
Bonjour,

Problème sur une installation de geotrek-rando v3 (v3.9.0) lorsque le nom de l'itinéraire contient une virgule, au clic sur le lien cela dirige vers une url de type : http://127.0.0.1:3000/trek/12551-Autour-de-Nieigles,-Pont-de-Labeaume et donc plante. Cela fonctionne lorsqu'on ouvre le lien dans une nouvelle fenêtre par contre car cela dirige bien vers [http://v3asv.destination-parc-monts-ardeche.fr/trek/6672-A-la-decouverte-de-Montpezat-sous-Bauzon,-Chalias](http://v3asv.destination-parc-monts-ardeche.fr/trek/6672-A-la-decouverte-de-Montpezat-sous-Bauzon,-Chalias)

Je vois que cela fonctionne pour d'autres portails, par exemple [https://destination.cevennes-parcnational.fr/trek/43909-Voyage-entre-Gorges-et-Causse,-au-pays-des-vautours](https://destination.cevennes-parcnational.fr/trek/43909-Voyage-entre-Gorges-et-Causse,-au-pays-des-vautours) donc je penche pour un problème de configuration de notre côté.

Une idée d'où cela peut venir?

Merci

**Comment by camillemonchicourt** [comment]
Si la page fonctionne avec une virgule, je pense que le soucis n'a rien à voir.

Ce que je comprends c'est depuis où et comment tu accèdes à une page sur l'URL 127.0.0.1:3000 ?

Et sinon il faudrait des logs lors de l'ouverture de la page qui pose soucis.

**Comment by AudreyRemy** [comment]
On se retrouve dans le même cas donc merci pour le partage :-)
