### ISSUE TITLE
Allow HTML in `mapCredits` parameter

### ISSUE THREAD

**Issue by IdrissaD** [GeotrekCE/Geotrek-rando-v3#725]
It would be useful especially for setting up links in the attribution text. For instance OpenStreetMap and OpenTopoMap strongly recommand to use links to their respective websites in the attribution text:

https://wiki.osmfoundation.org/wiki/Licence/Attribution_Guidelines#Attribution_text
https://opentopomap.org/about#verwendung

**Comment by IdrissaD** [comment]
Just saw the #719 PR which fixes it!

**Comment by camillemonchicourt** [comment]
Indeed, HTML was escaped but we are changing it with #719, also allowing to have a credit for each layer, and not only a global one.
It also allows to have different layers depending on zoom level.
And also to set an area (with a geojson) with a different basemap.
