### ISSUE TITLE
Widget reservation : mettre un loading pendant le chargement des scripts

### ISSUE THREAD

**Issue by dtrucs** [GeotrekCE/Geotrek-rando-v3#732]
L'injection des 3 scripts nécessaires pour lancer le widget peut être un peu long.
Pendant ce temps, l'encart reste vide et peut sembler "buggué", il conviendrait d'ajouter une phrase demandant de patienter ou une image animé indiquant qu'un chargement a lieu.

**Comment by camillemonchicourt** [comment]
Fait dans la 3.12.0
