### ISSUE TITLE
Pouvoir agrandir la carte (plein écran)

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#733]
Dans Geotrek-Rando V2 il était possible d'agrandir la carte pour la passer en mode "plein écran" (voir capture ci-dessous).

![image](https://user-images.githubusercontent.com/16348048/177176049-8c0bc3f2-46b3-41b7-8c97-427c8d0c521c.png)

Il semblerait qu'au moins un territoire souhaite pouvoir conserver cette fonctionnalité sur Geotrek pour permettre aux utilisateur de voir un tracé, notamment utile dans les cas de longues randonnées itinérantes.

**Comment by camillemonchicourt** [comment]
Oui c'est identifié dans https://github.com/GeotrekCE/Geotrek-rando-v3/issues/402
Mais on a priorisé les 2 autres outils, mais pas eu le temps de faire le PLEIN ECRAN.
Et à vrai dire, on s'est demandé si ça avait vraiment une utilité et si c'était vraiment utilisé par les visiteurs. 
Est-ce que ça vaut la fonctionnalité, au regard de la complication de l'interface, en multipliant les boutons ?

Pourquoi pas. OK pour moi.

**Comment by dtrucs** [comment]
Dispo depuis la version [v3.15.3](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.15.3)
