### ISSUE TITLE
Event : Filtre par date ne filtre pas la carte

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-rando-v3#741]
Lorsque l'on filtre les événéments par date, la liste est bien filtré mais la carte affiche l'ensemble des items 

![image](https://user-images.githubusercontent.com/3088650/178213397-52b9b7da-fa39-4d81-bcf8-4259e2a52347.png)

**Comment by camillemonchicourt** [comment]
En effet, petit oubli de la 3.10.1, corrigé ici : https://github.com/GeotrekCE/Geotrek-rando-v3/pull/743
