### ISSUE TITLE
Object : emails et url ne sont pas mis en forme 

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#742]
Sur une fiche d'évènement les propriétés "email" et "site web" ne sont pas cliquables.

![image](https://user-images.githubusercontent.com/16348048/178223608-c070613c-3b77-4313-8622-b21b2409d5ce.png)

Il faudrait pouvoir cliquer sur ces éléments comme c'est le cas dans GTA où les données sont formatées : 

![image](https://user-images.githubusercontent.com/16348048/178223741-40355644-d94c-4d32-82f3-75721c19fc3e.png)

Pour cela il faudrait (je pense) modifier les deux lignes (67 & 68) suivantes dans le fichier `DetailsDescription.tsx` : 

```(javascript)
{email && <div>{email}</div>}
{website && <div>{website}</div>}
```

Pour qu'elles deviennent quelque chose comme ça : 

```(js)
{email && <a href={{ 'mailto:' + email }}>{email}</a>}
{website && <a href={website}>{website}</a>}
```

**Comment by camillemonchicourt** [comment]
OK, à cette occasion, il pourrait être utile de mettre en place un mécanisme de masquage des emails dans le code pour limiter leur enregistrement par les robots.

**Comment by ESCAPADE62** [comment]
Je confirme, il est important que ces fonctionnalités intéressantes deviennent opérationnelles au plus vite, afin d'honorer nos engagements auprès des utilisateurs
