### ISSUE TITLE
Dates des événements décalés

### ISSUE THREAD

**Issue by noelmartinon** [GeotrekCE/Geotrek-rando-v3#751]
Bonjour,

Nous constatons un décalage d'1 jour entre les dates des événements saisies dans geotrek et celles qui s'affichent dans rando :
![image](https://user-images.githubusercontent.com/24294841/182891065-67a15b5a-e93f-488a-953c-976505b5d18c.png)
![image](https://user-images.githubusercontent.com/24294841/182891033-0b96d400-ee6c-47b9-91ff-e3aec5e391bb.png)

Je pensais que le problème venait du fait que nos serveurs sont sur un timezone 'America/Guadeloupe' alors que le docker est en 'UTC'. Les dates devant être stockées avec l'heure '00:00' alors, avec le décalage horaire GMT-4, le docker change par ex. le 14/08(00:00) en 13/08(20:00) !
Pour tester, j'ai donc rapidement changé le TZ du docker :
```
apk add tzdata
cp /usr/share/zoneinfo/America/Guadeloupe /etc/localtime
echo "America/Guadeloupe" >  /etc/timezone
date
Thu Aug  4 12:52:20 AST 2022
```

Hélas, bien que l'heure soit en GMT-4 (AST) et qu'elle persiste après un 'docker-compose restart', j'ai toujours le même problème de décalage !

A noter que dans postgresql.conf j'ai bien timezone = 'America/Guadeloupe' et que l'API remonte bien les bonnes dates.

Merci pour votre aide.

**Comment by dtrucs** [comment]
Bonjour @noelmartinon je viens de tester sur une instance locale et je ne reproduis pas ce décalage.
Pouvez-vous communiquer l'url API afin de tester avec vos données ?

**Comment by noelmartinon** [comment]
Bonjour,
Je vous ai envoyé les liens de nos sites geotrek et rando en privé.
Cdlt

**Comment by camillemonchicourt** [comment]
Fait dans la 3.10.3.
Le décalage venait de la prise en compte des timezone du navigateur.

**Comment by noelmartinon** [comment]
C'est corrigé, plus de décalage. Merci.
