### ISSUE TITLE
Utilisation d'un widget Meteo international

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#752]
Le widget actuellement utilisé est celui de Météo France. Or le lien pour l'adresse du widget est contenu en dur dans le code et ne peux pas être paramétré.

C'est un problème car certains territoires (Mercantour par exemple) sont sur deux pays et le widget n'affiche pas la météo sur les communes étrangères.

Le widget ne fonctionne pas non plus pour les communes or France métropolitaines (ça ne fonctionne pas avec les communes de la réunion).

Peut-être faudrait-il utiliser un widget d'une application météo qui permet d'obtenir des prévisions pour toute localisation ? 
MeteoBlue propose un widget par exemple : https://content.meteoblue.com/en/access-options/widget

Ou alors il faudrait permettre à l'utilisateur de paramétrer lui-même son widget pour pouvoir offrir cette fonctionnalités aux territoires or France métropolitaine.

**Comment by camillemonchicourt** [comment]
Oui le widget Météo France actuel est pas très bien fait.
On dirait qu'il n'est pas pensé pour être généré dynamiquement à partir des codes INSEE.

Il fonctionne hors métropole mais avec une utilisation du CODE INSEE où un zéro n'est pas ajouté à la fin.

Ce cas pourrait être géré en ajoutant un zéro à la fin du CODE INSEE que si celui fait 5 caractères.
A creuser, voir l'autre ticket sur le sujet.

Pour d'autres pays, à voir si on peut proposer un autre widget, mais il faut que ça reste simple à mettre en place et que les données soient fiables.

**Comment by camillemonchicourt** [comment]
Depuis la version 3.16.0 le widget Meteo France n'est plus intégré en dur dans le code source de GTR : https://github.com/GeotrekCE/Geotrek-rando-v3/pull/988/commits/032d03e622df216d1ffe0b248c103b4fe58fe50a

Le widget Meteo France est désormais un exemple de widget modifiable dans la custo des pages détails : https://github.com/GeotrekCE/Geotrek-rando-v3/pull/988/commits/53a97501c40b7d6a9a3eb401584838ef700e0d8f

**Comment by babastienne** [comment]
Tout à fait, c'est possible maintenant d'avoir n'importe quel widget dans la customisation.
