### ISSUE TITLE
Pop-up avertissement

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#756]
Bonjour,
Est-il possible d'ajouter une fenêtre à l'ouverture d'une étape d'un itinéraire ?
Nous avons une information temporaire à communiquer et nous aurions préféré ne pas la saisir dans le descriptif pensant que la fenêtre serait plus adaptée.
Merci d'avance pour vos retours.
Bonne journée.

**Comment by dtrucs** [comment]
Bonjour,
Aujourd'hui, aucune configuration ne permet une telle fonctionnalité.

Cependant vous pouvez peut-être injecter un script via `scriptsHeader.html` ou `scriptsFooter.html` https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization.md#html--scripts

Et surveiller l'url si elle contient le paramètre `parentId` pour faire votre injection 
```html
<script>
 function openPopup (id) {
   // Code to generate popup and content
 }

 function closePopup () {
   // Code to close popup if it exists
 }


  var routeChange = setInterval(function() {
   if (window.next && window.next.router) {
      window.next.router.events.on('routeChangeStart', function(url) {
        var params = url.split('?')[1];
        var searchParams = new URLSearchParams(params);
        var parentId = searchParams.get('parentId');
        if (parentId) {
	   openPopup(parentId)
        } else {
           closePopup()
        }
      });
      clearInterval(routeChange)
    }
  }, 100)
</script>
```

**Comment by AudreyRemy** [comment]
Bonjour @dtrucs 
Merci pour ce retour.
Bonne journée
