### ISSUE TITLE
Icône événement persistant sur homepage avec 0 résultats associés

### ISSUE THREAD

**Issue by noelmartinon** [GeotrekCE/Geotrek-rando-v3#763]
Si au moins un évenement est en état "publié" alors l'icône lié au type qui lui est associé s'affiche dans la barre d'activités même si la date actuelle ne correspond pas à la période de cet évenement.

**Comment by camillemonchicourt** [comment]
Tu veux dire que l'événement en question est passé, donc que sa date de fin est inférieure à la date du jour ?

**Comment by noelmartinon** [comment]
Oui c'est ça : L'évenement est passé et il n'y a d'ailleurs plus de filtres "Evenement" mais l'icône reste présent sur la page d'accueil.

**Comment by camillemonchicourt** [comment]
Ah OK. 
Je pense que la liste des activités sur la page d'accueil reste en cache au niveau du serveur Node.js de Geotrek-rando.

Si tu restart le Docker, la catégorie Événements disparaît de la page d'accueil, non ?

Sinon c'est que l'appel de la route pour vérifier si il y a des évènements ne passe pas le paramètre de la date du jour.

**Comment by camillemonchicourt** [comment]
En fouillant dans les tickets, le soucis est bien celui que j'ai indiqué.

Voir https://github.com/GeotrekCE/Geotrek-rando-v3/issues/560#issuecomment-1091318677 où j'ai indiqué : 

> La route ``/touristicevent_type/`` est bien filtrée pour ne renvoyer que les types d'événement qui ont un au moins un contenu associé publié.
> 
> Par contre, ce fonctionnement est comme sur les autres routes. Il regarde tous les événements publiés, sans interroger aussi la date.
> 
> Du coup si on a des événements terminés mais publiés, alors ils n'apparaissent plus dans Geotrek-rando mais leurs types sont bien remontés et affichés.
> On peut ainsi avoir des types d'événements qui remontent mais sans aucun contenu renvoyé, si les événements de ce type sont tous terminés.

Il faudrait donc faire une évolution, pour bien passer la date du jour à chaque fois qu'on interroge la route des événements.

**Comment by camillemonchicourt** [comment]
PR sur le sujet initiée ici - https://github.com/GeotrekCE/Geotrek-admin/pull/3263
