### ISSUE TITLE
Interpréter les fichier geojson (et json) pour les couches de carte

### ISSUE THREAD

**Issue by dtrucs** [GeotrekCE/Geotrek-rando-v3#764]
Afin d'afficher d'autre couches que des fonds de cartes, tel par exemple délimiter des territoires par un tracé, il serait intéressant que Geotrek Rando puisse intérpréter les GeoJson.

La fonctionnalité existait dans v2 => https://github.com/GeotrekCE/Geotrek-rando/blob/master/src/app/map/services.js#L1740, il serait intéressant de la reprendre pour la v3.

**Comment by camillemonchicourt** [comment]
Voir https://github.com/GeotrekCE/Geotrek-rando-v3/issues/385

**Comment by dtrucs** [comment]
Duplicate of #385
