### ISSUE TITLE
Ponctuation titre evenements touristiques

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#769]
Bonjour,
Nous avions 3 erreurs sur 3 fiches différentes d'évènements touristiques.
L'une avait un titre avec une virgule, une autre un point-virgule et la dernière deux points.
En supprimant la ponctuation des titres, nous n'avons plus d'erreur et les évènements remontent bien dans Geotrek rando v3.
Je ne sais pas si d'autres structures ont rencontré ce problème, je partage l'information si ça peut aider.
Bonne journée.

**Comment by camillemonchicourt** [comment]
Pour pouvoir comprendre et reproduire, pourrais-tu donner plus de précisions ?
- Quelle erreur ?
- Quels titres et ponctuations ?
- Des URL ?

**Comment by AudreyRemy** [comment]
J'ai remis une virgule dans un titre pour retrouver l'url qui bug :

Evenement : "Arres, grottes et sommets de calcaires" sur la page https://nature64.fr/search?event=7

http://127.0.0.1:3000/event/71-Arres,-grottes-et-sommets-de-calcaires

Le bug est remonté avec une virgule pour ce cas mais aussi avec un point-virgule et avec deux points pour deux autres cas.

**Comment by camillemonchicourt** [comment]
C'est bizarre ça redirige la page sur la mauvaise URL : http://127.0.0.1:3000/ au lieu de https://nature64.fr

Pas de soucis sur notre Geotrek de test/démo où je viens d'ajouter une virgule dans un titre d'événement : https://gtr3demo.ecrins-parcnational.fr/event/3-Le-chant-des-crapauds,-au-clair-de-lune

**Comment by AudreyRemy** [comment]
Merci @camillemonchicourt

**Comment by camillemonchicourt** [comment]
Ne serait-ce pas le même soucis que https://github.com/GeotrekCE/Geotrek-rando-v3/issues/723 ?
Votre paramètre ``baseUrl`` st-il bien renseigné ?

**Comment by AudreyRemy** [comment]
Tu avais raison @camillemonchicourt merci encore.
