### ISSUE TITLE
Problème de navigation sur regroupements d'icônes

### ISSUE THREAD

**Issue by noelmartinon** [GeotrekCE/Geotrek-rando-v3#774]
Bonjour,
Nous avons constaté un problème lorsqu'on clique sur un groupement d'icônes. Il est parfois très compliqué d'accéder aux éléments individuels car ils en reviennent en position "groupée" lorsqu'on approche le pointeur pour cliquer dessus.
Nous l'avons sur notre site randoguadeloupe mais également vu sur celui des Ecrins.
Je mets une vidéo car c'est plus simple à constater de visu :
[rando3_bug_group_icons.webm](https://user-images.githubusercontent.com/24294841/188934061-8d7f5f6d-3e0a-4290-aefe-5485c17b95f4.webm)

Au passage, je me rends compte que le nombre de résultats ne varie pas selon le contenu de la carte pour nous. Une idée ?

**Comment by dtrucs** [comment]
Bonjour,

Le problème des regroupements d'icones "cassés" a été corrigé avec la version [v3.10.5](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.10.5) (La release ne l'explicite pas, mais une optimisation du rafraichissement de la carte a été faite).

Celui avec la mise à jour du résultats de recherche selon les déplacement de la carte avec la version [v3.10.6](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.10.6).

Je viens de jeter un oeil sur votre Geotrek-Rando et je constate que vous avez mis à jour et ça me parait ok. 
Pouvez-vous confirmer que c'est bon de votre coté ?

**Comment by noelmartinon** [comment]
Bonjour,

Je n'avais pas mis à jour, nous étions en 3.10.4. Là, je viens de passer en 3.10.6. Le problème reste présent : 
[rando3_bug_group_icons_3.10.6.webm](https://user-images.githubusercontent.com/24294841/191348059-02b752be-459d-4949-b3b3-05b9a05e0b5c.webm)

Pour la recherche "bbox", c'est corrigé, merci.

**Comment by dtrucs** [comment]
Exact, je vais regarder ça, merci

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 3.10.8

**Comment by noelmartinon** [comment]
Confirmé
