### ISSUE TITLE
Version spécifique de Geotrek-rando v3

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-rando-v3#775]
Bonjour,
Pour tenter de contourner notre problème de latence sur notre Geotrek-rando v3, j’aimerais essayer de revenir à une image docker antérieure de Geotrek-rando. Nous n’avons quasiment que des itinéraires et lors du lancement de notre site, le site fonctionnait bien donc peut-être que cela nous permettrait d’avoir un site fonctionnel même si les évolutions sont intéressantes (il s’agit bien d’une solution temporaire).
J’ai lu que pour installer une version de Geotrek-rando spécifique je devais modifier le fichier .env et préciser la version souhaitée à la place de latest.
Actuellement mon fichier .env s’intitule .env.example. Dois-je renommer ce fichier en .env ou le garder en .env.exemple ?
Je souhaiterais revenir à la version 3.8.5 dois-je donc modifier le fichier en précisant 3.8.5:
IMAGE=ghcr.io/geotrekce/geotrek-rando-v3/geotrek-rando:3.8.5
Ou dois-je préciser la référence « edfda38 » (voir capture d’écran ci-dessous) ?
![image](https://user-images.githubusercontent.com/78603108/189320767-e924a1ac-7e6c-4667-9ce2-a504b0a3c50d.png)

Une fois le fichier mis à jour dois-je passer la commande suivante ou est-ce que cette commande installe forcément la dernière version ?
docker-compose pull && docker-compose down && docker-compose up -d
Actuellement lorsque je regarde les images sur ma VM j’obtiens
![image](https://user-images.githubusercontent.com/78603108/189320821-1c2acf6e-6f21-46f3-ade3-59e40b30bd24.png)

Image ID est-elle une référence propre à mon environnement docker ? 
Devrais-je préciser dans « TAG » la version installée pour pouvoir m’y retrouver par la suite ? Si oui comment dois-je faire ?
Si mes questions ne sont pas pertinentes n’hésitez pas à me le signaler et je ferais appel à Makina-Corpus, je ne maîtrise pas encore docker mais comprendrais que ce n’est pas à la communauté de me « former ».
Merci d’avance.
Bonne journée.

**Comment by camillemonchicourt** [comment]
Oui ces éléments sont indiqués dans la documentation (https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/installation.md#install-geotrek-rando) : 

![image](https://user-images.githubusercontent.com/4418840/189327945-15c657ce-803b-460e-9d11-8ebe68df550b.png)

- Il faut bien copier le fichier ``.env.example`` en ``.env`` avec la commande ``cp .env.example .env``
- Il faut bien lancer la commande ``docker-compose pull && docker-compose down && docker-compose up -d`` pour appliquer les modifications
- Il faut bien faire référence à un numéro de version précis et pas à un identifiant de commit, donc par exemple : ``IMAGE=ghcr.io/geotrekce/geotrek-rando-v3/geotrek-rando:v3.8.5`` (avec le v devant le numéro)
- Les IMAGE ID sur ton serveur sont en effet des identifiants locaux, liés à ton Docker. Pour les TAG c'est géré par l'installation, je pense pas que tu peux changer ça.
- **Je ne vois pas de raison qui expliquerait que les performances soient meilleures en version 3.8.5. Mais si c'est le cas, merci de nous l'indiquer dès que possible, pour voir ce qui aurait pu poser soucis depuis cette version.**
- Vous n'avez quasiment que des "itinérances" je pense que tu voulais dire ?

**Comment by AudreyRemy** [comment]
Merci @camillemonchicourt pour toutes ces précisons.
Je ne vois pas de raison non plus mais comme ça fonctionnait au lancement le 8 juin je me dis que ça vaut le coup d'essayer.
Je ne manquerai pas de vous tenir informés.
Et oui tu as raison, va falloir que j'arrive à intégrer le terme itinérances :-)

**Comment by AudreyRemy** [comment]
Bonjour,
Les tentatives de revenir à une image antérieure de Geotrek-rando v3 n’ont pas été concluantes (pourtant cela fonctionnait lors du lancement de notre site)
Parallèlement à ces essais, j’ai informé mon collègue de l’erreur ci-dessous :
 
![image](https://user-images.githubusercontent.com/78603108/190099601-5fffb74f-d816-46f4-9727-5d813cb1bf7e.png)

Je ne sais pas si ça peut intéresser la communauté mais voilà son retour :
« J'ai configuré le timeout du reverse proxy à 5 minutes. Il y a bien sûr toujours les lenteurs mais la page s’affiche bien après un long temps d’attente. 
Lors du temps d’attente du chargement de la page, on voit que la base de données postgres de geotrek-admin est à 100%. C’est donc, comme tu l'as dit, vraiment geotrek-admin qui a un souci.
![image](https://user-images.githubusercontent.com/78603108/190099694-2e9ea606-ee4b-4e28-8708-41b37f328707.png)

 
Une fois la page chargée, le processeur de geotrek-admin redescend à 0
 
![image](https://user-images.githubusercontent.com/78603108/190099732-d8e685ad-10f4-4f75-b801-cb3d53fa740c.png)

C’est la base postgres de geotrek-admin qui sature le processeur quand il y a trop de requêtes sur les pages problématiques. Donc même si geotrek-admin est saturé par plusieurs requetés problématiques (3) en même temps, les 5 minutes de timeout ne suffiraient même pas. »

**Comment by camillemonchicourt** [comment]
Salut, je ne comprends pas pourquoi le retour à une version antérieure n'a pas fonctionné ?
Quand tu as mis ce ticket, je l'ai fait en test sur un Geotrek-rando et ça a fonctionné nickel.

Concernant l'autre sujet que tu indiques, c'est plutôt lié à ce sujet : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/753#issuecomment-1228447693

Et en effet, on a bien identifié que c'est l'API de Geotrek-admin qui met du temps à calculer les infos et à les renvoyer.
Un travail est en cours sur le sujet, pour optimiser les requêtes côté Geotrek-admin, puis mettre du cache sur l'API de Geotrek-admin pour ne pas refaire les calculs à chaque fois.

**Comment by AudreyRemy** [comment]
Le retour a fonctionné. Nous avons bien pu tester différentes versions mais les "bugs" ou latence ne sont pas revenus comme au mois de juin. Les latences étaient présentes mais moindre par rapport à aujourd'hui. 
Merci @camillemonchicourt pour le travail en cours.

**Comment by camillemonchicourt** [comment]
OK donc cela confirme ce que je pensais ?
Que les soucis de performances sont exactement les mêmes sur la 3.8 et la 3.10 ?

**Comment by AudreyRemy** [comment]
C'est exactement ça... enfin sur notre environnement la version ne change rien.
