### ISSUE TITLE
Bug d'affichage des encarts remontées de patrimoines

### ISSUE THREAD

**Issue by dtrucs** [GeotrekCE/Geotrek-rando-v3#778]
Lors de résumés "trop long" le text se juxtapose. CF screenshot

![image](https://user-images.githubusercontent.com/1926041/191063280-0711eeda-db52-43ce-b2a3-7e6809a9e3c1.png)

**Comment by camillemonchicourt** [comment]
Duplicate https://github.com/GeotrekCE/Geotrek-rando-v3/issues/693
