### ISSUE TITLE
Mobile - Le filtre localisation en web app génère une erreur 

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando-v3#779]
Version rando v3 : 3.10.6

Le filtre localisation du site https://rando.valleesdegavarnie.com/ fonctionne, mais lorsque que l'on consulte le site sur un smartphone on a automatiquement le message d'erreur "Sorry, this is not working properly...". (J'ai voulu faire un imprim. ecran du smartphone mais je viens d'apprendre que cette application n'autorise pas les screenshot..).

Je sais qu'avec des logs mon ticket aurait plus d'informations, mais selon la documentation  pour récupérer les logs il faut couper le docker. Est-ce qu'il y aurait une solution pour récupérer les logs tout en laissant le site en ligne ? Sinon j'attendrai en fin de journée pour récupérer les logs.

**Comment by camillemonchicourt** [comment]
OK vu, sur un PC desktop, il est facile de reproduire en simulant une consultation sur mobile au niveau du navigateur.

![image](https://user-images.githubusercontent.com/4418840/191260768-88d5f121-40c4-483f-b46c-092a4e772947.png)

On voit alors les erreurs de la console : 

```
TypeError: Cannot read properties of undefined (reading 'selectedOptions')
    at MobileFilterSubMenu.tsx:113:51
    at Array.map (<anonymous>)
    at MobileFilterSubMenu.tsx:107:39
    at Array.map (<anonymous>)
    at Nt (MobileFilterSubMenu.tsx:103:30)
    at ro (react-dom.production.min.js:157:137)
    at Hu (react-dom.production.min.js:267:460)
    at Pi (react-dom.production.min.js:250:347)
    at _i (react-dom.production.min.js:250:278)
    at xi (react-dom.production.min.js:250:138)
```

Problème reproduit sur https://rando.ecrins-parcnational.fr.
C'est l'appel du filtre par localisation lui-même qui entraîne un plantage, en version mobile.

PS : Je ne vois pas pourquoi la commande ``docker-compose logs -t`` stopperai le docker, ce n'est pas le cas, et pas dit dans la documentation.
PS : J'ai pas compris non plus l'histoire des captures, pas de soucis pour faire une capture écran sur https://rando.valleesdegavarnie.com

**Comment by mviadere-openig** [comment]
Oui je viens de me rendre compte de mon erreur en relisant la documentation, je me disais que c'était vraiment pas pratique. Au temps pour moi. 

Concernant la capture je parle d'une capture d'écran de l'application sur smartphone. Mais peut être que ce n'est qu'un cas isolé avec mon smartphone personnel. 

merci pour l'astuce de simulation d'un mobile sur navigateur, je l'utiliserai la prochaine fois.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 3.10.7.
