### ISSUE TITLE
Impression des pdfs dans une autre langue retourne automatiquement un pdf en Fr

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando-v3#782]
geotrek-randov3 version : latest

le site https://rando.tourisme-pyrenees-mediterranee.fr propose des itinéraires en plusieurs langues, mais l'impression des itinéraires retourne automatiquement un pdf en français. 

Voir les logs ci-dessous : 

[error_randov3.log](https://github.com/GeotrekCE/Geotrek-rando-v3/files/9608904/error_randov3.log)

**Comment by camillemonchicourt** [comment]
Je ne reproduis pas le soucis.
Quand je suis en anglais par exemple sur ce portail, je vais sur une rando en anglais : https://rando.tourisme-pyrenees-mediterranee.fr/en/trek/4019-(E-12---GR-92)-Colera---Portbou

Et ça me charge le PDF en anglais : https://geotrek.tourisme-pyrenees-mediterranee.fr/api/en/treks/4019/e-12-gr-92-colera-portbou.pdf

PS : Attention, tu as des randos publiées en anglais mais sans titre en anglais, ça peut être l'origine de ton soucis ? 
En tout cas, c'est pas souhaitable et à ne pas faire. On ne publie pas dans une langue sans avoir mis au moins un nom à l'objet dans cette langue.

Peux-tu donner un exemple plus précis d'une URL d'une rando où tu as le soucis ?

**Comment by mviadere-openig** [comment]
Bonjour, oui je pensais l'avoir mis : https://rando.tourisme-pyrenees-mediterranee.fr/de/trek/2-Auf-der-Anhohe-von-Collioure. D'ailleurs plusieurs itinéraires en allemand retournent automatiquement du français.

Merci pour ton retour Camille, je vais tenir les OT informés de tes recommandations.

**Comment by mviadere-openig** [comment]
Voici les logs du geotrek-Admin : 
[systemd-geotrek-api.log](https://github.com/GeotrekCE/Geotrek-rando-v3/files/9617278/systemd-geotrek-api.log)
[systemd-geotrek-celery.log](https://github.com/GeotrekCE/Geotrek-rando-v3/files/9617279/systemd-geotrek-celery.log)
[systemd-geotrek-ui.log](https://github.com/GeotrekCE/Geotrek-rando-v3/files/9617280/systemd-geotrek-ui.log)

Ayant regardé rapidement je n'ai rien vu en rapport avec un problème de génération de pdf.
De ce que j'ai pu voir sur le Geotrek-Admin les champs en allemands sont bien remplies (j'ai vérifié que pour la rando posté en exemple). 
Je  pense donc qu'il s'agit d'un problème dans le fichier locale allemand. Je vais demander aux OT de vérifier leur données intégrées. 

Dans le fichier situé ici : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/trekking/locale/de/LC_MESSAGES/django.po, je ne vois que des traductions manquantes.

**Comment by camillemonchicourt** [comment]
Il faut en causer au niveau du Github de Geotrek-admin, en faisant référence à ce ticket, car le sujet n'est pas lié à Geotrek-rando et ce ne sont pas les mêmes personnes qui suivent ces 2 dépôts.
Ça peut être intéressant que tu mettes à jour ton Geotrek-admin en version 2.87 avant de renvoyer les logs, car les logs de Geotrek-admin ont été bien corrigés et complétés dans cette nouvelle version.

**Comment by mviadere-openig** [comment]
C'est noté, je met à jour et je repost sur Geotrek-admin
