### ISSUE TITLE
Masquer filtre quand display est à false dans filter.json

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-rando-v3#794]
Lorsqu'on tente de désactiver l'affichage d'un filtre (en l’occurrence, "Événements" dans mon cas), le fait de passer le paramètre display à false dans filter.json ne masque pas le filtre qui apparait toujours mais avec un contenu vide.

Version de Geotrek-rando-v3 : 3.10.7

```
{
    "id": "event",
    "type": "MULTIPLE",
    "display": false
}
```
<img width="606" alt="image" src="https://user-images.githubusercontent.com/44799642/193550339-6cf43b5a-ab45-4106-8d7d-6d17acb0d55e.png">

**Comment by pnrma** [comment]
Semble le même problème que rapporté dans #595 donc je ferme l'issue.

**Comment by camillemonchicourt** [comment]
Non c'est bien un autre sujet.
Le fonctionnement des filtres et de ce que l'on peut masquer ou non, n'est pas forcément très clair ni complet.

Mais si tu veux désactiver totalement les événements, il vaut mieux utiliser le paramètre dédié à ça : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/config/global.json#L8

**Comment by pnrma** [comment]
Ok, merci Camille.
