### ISSUE TITLE
Recherche sensible aux accents

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-rando-v3#812]
Lors d'une recherche, bien souvent les utilisateurs omettent les accents et la recherche de Geotrek-rando-v3 semble prendre en compte l'accentuation. Ne serait-il pas mieux de supprimer cette sensibilité de la recherche aux accents?

**Comment by camillemonchicourt** [comment]
Oui, en effet, si c'est le cas, c'est dommage.

A voir côté API v2 de Geotrek-admin.

**Comment by dtrucs** [comment]
Référencé ici https://github.com/GeotrekCE/Geotrek-admin/issues/2915
