### ISSUE TITLE
Question :  modifier le numéro présenté en accessibilité

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando-v3#813]
Version Geotrek-rando : latest

Sur le GEotrek-Rando v3, lorsque on coche une accessibilité sur un itinéraire, un numéro de secours apparaît : 

![image](https://user-images.githubusercontent.com/45095227/197164335-af00902b-c013-4021-ac34-a372c811d5f6.png)

Est-il possible de customiser cette partie pour modifier le numéro de téléphone ?  Je n'ai rien trouvé dans la doc ou dans les fichiers de traductions.

**Comment by dtrucs** [comment]
Bonjour,

Effectivement je constate ce n'est pas référencé dans la documentation.

Vous pouvez modifier ce numéro par la configuration avec la clé `accessibilityCodeNumber` dans `global.json`
https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/config/global.json#L26.

**Comment by mviadere-openig** [comment]
Merci pour la réactivité ! :)
