### ISSUE TITLE
Personnalisation page 404

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-rando-v3#816]
Je n'ai pas trouvé d'infos concernant la customisation de la page 404 qui s'affiche par défaut avec la charte du PN des Écrins.
Y a t-il quelque chose de prévu ?

**Comment by dtrucs** [comment]
Effectivement, nous avons constaté également ce problème, il s'agit d'une regression depuis à 3.10.7 suite à une refacto de la gestion des erreurs https://github.com/GeotrekCE/Geotrek-rando-v3/pull/777.

Je rappelle le fonctionnement de l'application et comment elle est installé chez un utilisateur :

## Utilisation actuelle côté Utilisateur

- Pull ce dépôt https://github.com/GeotrekCE/Geotrek-rando-v3-installer 
- Modifier les contenus des dossiers customizations + medias qui sont montés en volumes
- À chaque modifications desdits dossiers, il est nécessaire de `docker-compose` down/up l'instance pour que ça soit pris en charge dans l'application.

## Utilisation actuelle côté application Geotrek Rando

Le `Dockerfile` explique bien la démarche https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/Dockerfile: Il installe NodeJS et ses dépendances, il build et il lance l'application.

### Comment NextJS prend connaissance des modifications des dossiers `customizations` et `medias` ?

L'application est buildé avec un dossier [`config`](https://github.com/GeotrekCE/Geotrek-rando-v3/tree/main/frontend/config) qui est la configuration par défaut.
Au lancement de l'application, lors de son `runtime`, une directive est donnée par nextjs de récupérer le dossier `customization` et de faire une fusion du contenu de `config` afin d'intégrer les éléments de personnalisation.  
NB: Le dossier `config` est exposé par docker pour faire cette manip https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/Dockerfile#L28.

C'est plutôt malin, et très rapide à down/up lors de modifications car le travail est executé au `runtime` et il n'est pas nécessaire de rebuild l'application.

### Problématiques :

Les pages erreurs de routing (404, 500, etc) sont buildés une fois pour toutes avec les éléments de configuration qu'il a connaissance au moment du build.  
Ces pages ne vont pas être re-actualisés au `runtime` de l'application. Et impossible d'ejecter cette optimisation NextJS => https://nextjs.org/docs/advanced-features/custom-error-page

Il est à noter que par cette utilisation nous avons également un problème de purge CSS qui cause des frustrations pour la personnalisation des templates (ce commentaire explique bien la problématique https://github.com/GeotrekCE/Geotrek-rando-v3/issues/548#issuecomment-1050075631)
 
Pour résoudre ces problématiques, l'idéal serait donc de build l'application **avec** la customization.
Or si l'étape build a été séparée de la `customization`, c'était pour éviter des down/up long.

Nous sommes en cours d'investigation pour améliorer cela.

**Comment by dtrucs** [comment]
Pour préciser les modifications apportées récemment dans le dépot et problablement utilisable pour la prochaine version.
Un script a été écrit pour s'executer juste avant le lancement le l'application (`yarn start` ; `docker-compose up`).

## Que fait ce script :
- Il reconstruit la configuration des customization au moment de son éxécution.
- Il va chercher les fichiers préconstruits du build de l'application.
- Il remplace la configuration générée lors du build par la plus récente.

## Limitations :
- Cette re-écriture se fera que sur les langues définies dans la [configuration par défaut](https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/customization/config/header.json#L5), à savoir EN, FR, et IT. Les autres langues qui peuvent être ajoutées via la customisation ne peuvent pas être re-écrite car elles n'ont pas été buildées.
- L'actualisation des templates HTML/Script n'apparaitront pas dans ces pages.

## Conclusion
En définitif, il s'agit d'un fix que l'on souhaite temporaire le temps qu'on parvienne à optimiser les builds docker avec la custo (cf message précédent). 
Re-écrire des fichiers build n'est pas très fiable et peut causer des souçis lors de montée en version de certains package, ça sera donc à surveiller.

**Comment by camillemonchicourt** [comment]
Le nouveau système de déploiement de Geotrek-rando-v3 a été mis en place dans la version 3.2.0 pour ne plus avoir à builder localement sur chaque serveur une image - https://github.com/GeotrekCE/Geotrek-rando-v3/issues/458
Accompagné de la version 2 de l'installer de Geotrek-rando-v3 (https://github.com/GeotrekCE/Geotrek-rando-v3-installer/releases).

Cela fonctionnait bien jusqu'à la version 3.10.7 d Gotrek-rando, même pour les pages 404 et offline.

Ça serait dommage de devoir repasser à un système où chacun doit builder une image pour avoir sa custo présente sur les pages 404 et offline.

**Comment by camillemonchicourt** [comment]
La correction partielle a été intégrée dans la version 3.12.0.

Par ailleurs, dans la 3.11.0, il a été remis en place la possibilité de se builder soi-même localement sur son serveur sa propre image Docker avec toute la customisation intégrée, à partir d'une image spécifique : https://github.com/GeotrekCE/Geotrek-rando-v3/pkgs/container/geotrek-rando-v3%2Fgeotrek-rando-builder
