### ISSUE TITLE
Rayon d'intersection des zones sensibles avec les itinéraires

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-rando-v3#827]
Le rayon d'intersection des zones sensibles avec les itinéraires ne semble pas paramétrable dans Geotrek-rando-v3.
Est-ce prévu dans les prochaines mises à jour?

**Comment by camillemonchicourt** [comment]
C'est normal, toutes les intersections se font au niveau de Geotrek-admin quand Geotrek-rando-v3 interroge son API pour demander la liste des zones sensibles d'un itinéraire.

Liste des noms zones sensibles du serveur Geotrek-admin de démo en interrogeant son API : https://geotrekdemo.ecrins-parcnational.fr/api/v2/sensitivearea/?fields=name

Le réglage de la largeur de la zone tampon d'intersection autour des objets pour remonter ou non les zones sensibles est donc définie au niveau de Geotrek-admin : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/base.py#L678
