### ISSUE TITLE
Amélioration du référencement des pages de recherches

### ISSUE THREAD

**Issue by dtrucs** [GeotrekCE/Geotrek-rando-v3#833]
## Problématique

Les pages de recherche constituent le point d'entrée de l'accès à toutes les fiches (rando/outdoor/contenu touristiques/etc). C'est le maillage indispensable afin que les moteurs de recherches puissent accéder à ces contenus.

Actuellement ces pages ne sont alimentées que par une surcouche JavaScript. Le SSR (Server Side Rendering) n'est actuellement qu'une coquille vide.

![image](https://user-images.githubusercontent.com/1926041/204246824-eb740665-56fc-4568-8877-e3f4bbba6557.png)
Exemple de rendu de la page de recherche sans JavaScript activé.

## Chargement des résultats et pagination

La page liste toutes les fiches présentes dans les filtres de recherches, or comme ce nombre peut être conséquent un système de scroll infini a été mis en place.
C'est-à-dire qu'une première liste de X éléments sont chargés, et dès que l'utilisateur scroll jusqu'en bas de cette liste, X nouveaux éléments sont chargés et ainsi de suite. X étant la valeur définie par la clé `searchResultsPageSize` dans `global.json` (valeur par défaut à `10`).

Également pour des raisons de performance, il ne sera pas possible d'afficher la totalité du contenu côté SSR. Et si on affiche qu'une liste de 10 éléments, les autres pages ne seront pas atteignables par les moteurs de recherche.

Une solution consiste de développer une pagination classique pour le SSR.
Et "transformer" l'interface en infinite scroll lorsque l'hydration JavaScript s'effectue. 

En résumé, ce développement n'aurai aucun impact UX sur l'utilisateur.

## Architecture de la page de recherche
- Une balise h1 est manquante, il serait pertinent d'en mettre un englobant la phrase "X résultats trouvés" et :
   - de compléter cette phrase des catégories sélectionnées. Par ex "39 résultats trouvés pour "Pédestre" et "Équestre"" 
   - de pouvoir personnaliser cette phrase lorsqu'une et une seule catégorie est sélectionnée. Par exemple "Randonnée en vélo en Normandie : 39 résultats trouvés". Auquel cas, chaque catégorie de chaque type devrait se voir attribuer un nouveau champ dans Geotrek Admin. Si non saisi, la phrase par défaut est affichée.
- Une description à afficher lorsqu'une et une seule catégorie est sélectionnée. Également, chaque catégorie de chaque type devrait se voir attribuer un nouveau champ dans Geotrek Admin. Si non saisi, aucune description n'apparait.

En résumé, ce développement nécessite un développement supplémentaire à Geotrek Admin et doit être soumis à une approbation de la communauté.

**Comment by camillemonchicourt** [comment]
OK merci.
OK pour moi.

Pour le contenu de la balise h1, à voir, car cela peut inclure des contenus de différentes catégories (randos, sites outdoor, services, événements... Ça peut être bizarre de ne pas mentionner le nom de la catégorie, mais uniquement leur sous-type.

Si on n'a qu'une seule catégorie, on pourrait plutôt mettre : "39 randonnées trouvées" ou "39 randonnées à vélo trouvées". La première proposition ne nécessiterait pas de nouveau champs dans Geotrek-admin et me semble suffisante.

Idem pour les description, on peut imaginer une description de base pour chacune des 4 catégories de contenus (Randos, Sites Outdoor, Services et Evenements) gérées dans les fichiers de traduction de Geotrek-rando

**Comment by camillemonchicourt** [comment]
En lien avec https://github.com/GeotrekCE/Geotrek-rando-v3/issues/666

**Comment by camillemonchicourt** [comment]
Globalement sur le SEO, voir https://freetools.seobility.net/en/seocheck/check?url=https%3A%2F%2Frando.ecrins-parcnational.fr%2Ftrek%2F980102-Le-lac-de-Vallonpierre&crawltype=1

**Comment by camillemonchicourt** [comment]
Une pagination des résultats a été mise en place dans la version 3.13.2 au niveau du SSR.
Elle est seulement visible par les moteurs de recherche pour leur permettre d'indexer toutes les pages détails et donc d'améliorer le référencement.
Visible en désactivant le javascript du navigateur : 

![image](https://user-images.githubusercontent.com/4418840/225390014-ff3bb2cd-b48d-400c-9c7e-f78546c8d345.png)

Pour les visiteurs, l'affichage des pages de résultat reste le même.
Pour ne pas indexer ces pages paginées de résultats de type `/search?page=2` ne sont pas indexables par les moteurs de recherche (https://github.com/GeotrekCE/Geotrek-rando-v3/pull/882)

Concernant l'autre point d'ajout d'une balise H1 et d'un title quand un seul type de contenu est filtré, cela avait été intégré dans la version 3.13.0 : 

![image](https://user-images.githubusercontent.com/4418840/225387799-9da294b6-5069-43a4-ab0a-362643ca2ba4.png)
