### ISSUE TITLE
Problème d'affichage du champs "matériel"

### ISSUE THREAD

**Issue by noelmartinon** [GeotrekCE/Geotrek-rando-v3#844]
Sur un sentier, nous avons renseigné le champs "matériel" mais le contenu n'est pas affiché complétement et se trouve doublé dans le détail de l'itinéraire : 

![bug_materiel](https://user-images.githubusercontent.com/24294841/210835281-db509769-1c93-44be-9c9d-3285de00c5ab.png)

**Comment by camillemonchicourt** [comment]
Oui le bloc MATÉRIEL a été déplacé (https://github.com/GeotrekCE/Geotrek-rando-v3/pull/698/files), mais il y a du y avoir un soucis de MERGE, car le bloc est bien en doublon : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/components/pages/details/Details.tsx#L294-L309

Confirmé sur https://gtr3demo.ecrins-parcnational.fr/trek/2-Col-de-Font-Froide

Pour le texte, on voit qu'il est bien récupéré et présent dans la page, mais est masqué (``display: none``), je ne sais pas pourquoi : 

![image](https://user-images.githubusercontent.com/4418840/212292525-9ac11cc8-bb49-4e2d-8a72-ed0d5f9a196f.png)

**Comment by noelmartinon** [comment]
Pour le texte, désolé, c'est de ma faute ! Pour corriger des superpositions de textes qu'il y avait avec une version précédente de rando (3.10.1 je crois), j'avais mis le css suivant : 
#details_sectionContent > div > div > div > span {
  display: none;
}
Je l'ai retiré et le texte est bien affiché maintenant.

**Comment by camillemonchicourt** [comment]
OK donc il ne reste plus qu'à supprimer le bloc MATERIEL en double dans le template, que je viens de faire une pull request.

**Comment by camillemonchicourt** [comment]
Fait dans la 3.12.0
