### ISSUE TITLE
Les site outdoor n'affichent parfois pas tous les autres sites liés 

### ISSUE THREAD

**Issue by dtrucs** [GeotrekCE/Geotrek-rando-v3#846]
À l'affichage d'une page détail d'un site outdoor, je constate qu'il peut y avoir des `children` ne s'affichant pas.

Par ex l'ID numéro 9 présent ici https://admin.sisteron-buech.fr/api/v2/outdoor_site/2/?fields=children, n'apparait pas dans le rando.
```json
{
  "children":[9,3,4,5]
}
```
En regardant l'implémentation coté GTR3 (=> https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/modules/outdoorSite/connector.ts#L70), il fait cette requête https://admin.sisteron-buech.fr/api/v2/outdoor_site/?near_outdoorsite=2&fields=id 

```json
{
  "count":3,
  "next":null,
  "previous":null,
  "results":[
    {
      "id":3
    },
    {
      "id":4
    },
    {
      "id":5
    }
  ]
}
```
Je pense qu'il est nécessaire d'appliquer un correctif et récupérer les site relatifs depuis le champ `children`, mais comme ça n'a pas été fait initialement, je me pose la question s'il n'y a pas une subtilité qui me dépasse ?

**Comment by camillemonchicourt** [comment]
En effet quand on récupère les enfants d'un site, ce n'est pas souhaitable de les récupérer en fonction de leur proximité, avec le paramètre ``near_outdoorsite``.

En plus c'est même carrément faux. Ça veut dire qu'on va remonter les sites à proximité qui n sont pas forcément les enfants du site, et potentiellement en oublier qui sont plus loin.

Donc pour moi c'est clairement une erreur.

**Comment by dtrucs** [comment]
Pour information, pour les trek c'est bien répercuté avec un fetch de chaque enfant.
À voir pour une homogénéisation de la fonctionnalité.

**Comment by camillemonchicourt** [comment]
Je confirme le soucis.
Aussi embêtant, à l'inverse, cela peut remonter des "sous-sites" qui n'en sont pas, si il y a d'autres sites Outdoor d'autres pratiques à proximité d'un site, comme on le voit ici - https://rando.paysdesecrins.com/outdoor-site/114-Domaine-nordique-de-La-Vallouise

Donc vraiment problématique que de se baser sur les sites à proximité et non pas sur les sites enfants.
C'est une erreur lors du développement initial du module Outdoor dans Geotrek-rando-v3.

**Comment by camillemonchicourt** [comment]
En regardant l'API, il faudrait en effet utiliser la propriété ``children`` de la route ``outdoor_site`` et non pas le filtre ``near_outdoorsite``.

Exemple sur https://geotrek-admin.ecrins-parcnational.fr/api/v2/outdoor_site/?page=5&page_size=10
```
"children": [
        30,
        29
      ],
```

Le soucis semble être le même sur les parcours qui sont remontés sur la fiche d'un site. On utilise certainement actuellement la route ``outdoor_course`` en lui passant le filtre ``near_outdoorsite``, alors qu'on devrait utiliser la propriété ``courses`` de la route ``outdoor_site`` : 

```
"courses": [
        21
      ],
```

**Comment by camillemonchicourt** [comment]
Fixé dans la version 3.14.0
