### ISSUE TITLE
Ne pas afficher les objets liés (Patrimoines, contenus touristiques...) sur les itinérances

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#847]
Les fiches mères des itinérances peuvent être très longues et intersecter de nombreux Patrimoines (POIs), Contenus touristiques...
Par exemple une itinérance de 13 jours sur le Grand tour des Écrins intersecte 137 patrimoines et 190 contenus touristiques.

Cela rend le chargement de cette itinérance très long, et n'est pas du tout lisible car cela trop d'objets liés.
Les objets liés (patrimoines et contenus touristiques) sont intéressants et lisibles au niveau de chaque étape où ils sont en moyenne de l'ordre d'une dizaine, comme sur une rando classique.

Pour palier le fait que le nombre de Patrimoines et de Contenus touristiques liés à une fiche mère d'une itinérance étaient potentiellement trop nombreux et trop lourds à charger, on a ajouté un paramètre permettant de définir le nombre maximum d'objets remontés, à 50 par défaut : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/config/global.json#L4-L5

Mais cela n'a encore moins de sens que d'afficher 50 patrimoines sur 137 et 50 contenus touristiques sur 190. Car c'est une info partielle, donc fausse et pas plus lisible.

Je propose une solution plus tranchée et radicale, mais plus lisible et fonctionnelle à mon avis : 
Ajouter un paramètre pour ne pas afficher les patrimoines et contenus touristiques liés aux fiches mères des itinérances.

Elles seront ainsi bien plus rapides à charger et plus lisibles, et on retrouvera bien les patrimoines et contenus touristiques de l'itinérance sur les fiches de chaque étape.

**Comment by AudreyRemy** [comment]
Merci @camillemonchicourt pour cette proposition qui correspondrait également à nos besoins.

**Comment by babastienne** [comment]
Oui ok avec l'idée qui parait tout à fait cohérente en effet. Comme ut le propose il faudrait conserver cet aspect paramétrable car certains territoires avec moins de contenus pourraient souhaiter afficher les objets associés aux itinérances malgré tout.

**Comment by dtrucs** [comment]
Pour compléter techniquement ce ticket en plus des POIs et les contenus touristiques, il faudrait également ne plus afficher toutes les autres requêtes utilisant `near_trek`:
- Zones sensibles
- Services
- Infrastructures
- Signalétiques 

C'est bien cela ?

**Comment by camillemonchicourt** [comment]
Bonne question.

Si on assume que les fiches des itinérances soient très allégées pour être plus lisibles et plus rapides à charger.

Je ne sais pas si on est prêt à se passer de tous les objets liés sur les itinérances.

Sinon on fait un paramètre plus complexe, mais plus souple, où on liste les objets liés qu'on désactive sur les fiches itinérances [pois,services,sensitive_areas,infrastructures,signages] ?

Mais bon, peut-être trop complexe et pas utile. Et soit on affiche tout, soit rien... J'hésite...

**Comment by babastienne** [comment]
Personnellement je préfère l'option de choisir les objets à afficher ou non, avec une liste comme tu le propose Camille. On a remarqué que certaines requêtes étaient vraiment plus lentes que d'autres, donc ça permet d'affiner le choix tout en laissant une certaine souplesse de configuration aux utilisateurs.

**Comment by camillemonchicourt** [comment]
OK si ça complexifie pas trop les développements, on fait un paramètre avec une liste des objets liés.

**Comment by dtrucs** [comment]
Pour le paramétrage, je propose d'ajouter les clés suivantes dans `config/global.json`

```json
  "displayRelatedObjectsToItinerancyTreks": {
    "POIs": true,
    "touristicContents": true,
    "sensitiveAreas": true,
    "infrastructures": true,
    "signages": true,
    "services": true
  }
```
On les met tous en defaut à `true` par soucis de rétrocompatibilité.

Et dans le fichier de customization on peut surcharger les valeurs des objects qu'on ne souhaite pas afficher dans les randos itinérantes
Par ex:
```json
  "displayRelatedObjectsToItinerancyTreks": {
    "infrastructures": false,
    "signages": false,
    "services": false
  }
```

**Comment by camillemonchicourt** [comment]
OK, j'hésite juste à savoir si par défaut on désactive tout pour que ça dépote, ou alors si on affiche tout et les gens trouveront et comprendront qu'on peut les désactiver. 🤔

**Comment by camillemonchicourt** [comment]
OK si c'est bien explicité dans la doc.

**Comment by camillemonchicourt** [comment]
OK testé.

Sur une itinérance avec 13 étapes, 137 patrimoines, 17 zones sensibles, 190 services à proximité : 

3 secondes pour charger le contenu de la page, 10 secondes pour afficher complètement la page (souvent plus).

![image](https://user-images.githubusercontent.com/4418840/227369822-42a393cc-7c97-4bc2-b966-95329795495a.png)

Si je désactive tous les objets liés : 

925 ms pour charger le contenu de la page, 2.3 secondes pour afficher complètement la page.

![image](https://user-images.githubusercontent.com/4418840/227369855-e3a4be14-3e88-4f75-bc3e-8e4d697c83a1.png)

Si j'active seulement les POI (patrimoines) : 

3.6 secondes pour charger le contenu de la page, 7.8 secondes pour afficher complètement la page.

![image](https://user-images.githubusercontent.com/4418840/227371606-f981f332-fb51-4530-9f3f-fe99c6bf16c5.png)

Si j'active seulement les services (contenus touristiques) à proximité : 

2.5 secondes pour charger le contenu de la page, 7.7 secondes pour afficher complètement la page.

![image](https://user-images.githubusercontent.com/4418840/227371468-756a941c-26d6-4a5d-9b1f-77f04dd40f09.png)

Si j'active seulement les zones sensibles : 

1.7 secondes pour charger le contenu de la page, 3.2 secondes pour afficher complètement la page.

![image](https://user-images.githubusercontent.com/4418840/227372553-dca9a7b6-540c-4737-a809-a4c7a230db47.png)

---------------------

A noter cependant, que la récupération des POI, des signalétiques et aménagements seront plus rapides à calculer dans la prochaine version de Geotrek-admin en les récupérant en segmentation dynamique et non plus par un calcul géographique de proximité.

**Comment by camillemonchicourt** [comment]
Fait dans la 3.13.5.
