### ISSUE TITLE
Problème affichage sur téléphone Apple Version 3.12 de Geotrek

### ISSUE THREAD

**Issue by eloisemtPNFor** [GeotrekCE/Geotrek-rando-v3#855]
On rencontre des petits soucis d'affichage sur l'accueil de Geotrek rando sur les téléphones Apple (sur les tablettes pas de soucis). Ce n'est pas un soucis interne puisque le problème est le même pour d'autres qui sont sur la même version que nous (3.12).

![image](https://user-images.githubusercontent.com/124795085/217554724-abea0702-d013-4bfe-9133-2227cc9bafb0.png)

**Comment by dtrucs** [comment]
Merci,
Les tablettes sont également sous IOS/Safari ?
Pouvez-vous indiquer les numéros de version ?

**Comment by eloisemtPNFor** [comment]
Pour les téléphones on est sur du IOS 16.3. J'ai aussi testé sur les navigateurs safari et Google chrome et le problème est le même. 
Pour l'iPad (là où ça fonctionne) : IOS 14.7.1

**Comment by camillemonchicourt** [comment]
En effet il y avait bien un spécificité de iOS à gérer, lié au fait que cet OS bloque les affichages en plein écran.
Fait dans la 3.12.1.
