### ISSUE TITLE
Lieux de renseignement : bouton en savoir plus n'affiche pas d'information supplémentaire

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#859]
Lorsque je clique sur "En savoir plus" sur un lieu de renseignement sur une randonnée, aucune information supplémentaire n'est affichée. 
Il faudrait que ce bouton apparaisse uniquement si l'objet est suffisamment long.

Exemples : 
- https://randonnee-normandie.com/trek/40-La-boucle-du-Pin,-Haras-national-du-Pin---Randonnee-a-pied
- https://demo-rando-v3.geotrek.fr/trek/10443-De-Bethmale-au-col-de-la-Core

Démo du problème : 
![Peek 2023-02-14 10-17](https://user-images.githubusercontent.com/16348048/218691970-3c9dbc28-f175-4bd9-b58f-211ed78348e0.gif)

**Comment by AudreyRemy** [comment]
Cela me fait penser à certains POI : parfois il est proposé de "lire la suite" alors qu'il n'y a pas de renseignement supplémentaire.

![Capture](https://user-images.githubusercontent.com/78603108/218735141-31a7f1f1-645d-4de2-8db2-797715b2f25d.gif)

**Comment by babastienne** [comment]
@AudreyRemy oui absolument. C'est le même problème, de l'optimisation graphique à effectuer.

**Comment by dtrucs** [comment]
Les 2 problèmes évoqués ont été corrigés depuis quelques versions déjà

**Comment by dtrucs** [comment]
Les 2 problèmes évoqués me semble corrigés depuis quelques versions déjà
