### ISSUE TITLE
Permettre de modifier le temps de défilement des images sur le bandeau en page d'accueil

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#863]
Plusieurs retours ont étés remontés demandant de pouvoir configurer le temps de défilement des images sur le bandeau en page d'accueil de Geotrek-Rando.

Aujourd'hui cette fonctionnalité n'est pas disponible mais il pourrait être pertinent d'ajouter cette option, de manière paramétrable (en secondes), dans la configuration `home.json`, section `"welcomeBanner"`.

Emplacement de la valeur définie par défaut dans le code source : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/acebac2e21339f5d9c80059132f6d0279d59b520/frontend/src/components/pages/home/components/BannerCarousel/BannerCarousel.tsx#L21

**Comment by mougetann** [comment]
Bonjour,
Je suis également intéressée par cette issue. Lorsque l’on choisit l’option carousel avec des images, celles-ci défilent à un rythme très rapide, un peu trop même, qui fait qu’il n’est pas possible de laisser la page ouverte sans que ça rende le défilement désagréable. Ma demande ne serait pas tant de pouvoir paramétrer le temps de défilement des images, mais de changer la valeur actuelle pour plus long (5 sec peut être), directement dans le BannerCarousel.tsx. Je doute que les 2.5sec conviennent à grand monde, mais je me trompe peut être ?

**Comment by camillemonchicourt** [comment]
Oui on m'a remonté aussi que ça défilait trop vite par défaut.

**Comment by dtrucs** [comment]
Avec la PR liée, le temps passe à 5s par défaut.  
Pour personnaliser cette valeur, ça implique un breaking change de la config de `home.json`, je laisse le ticket ouvert pour ne pas oublier

**Comment by dtrucs** [comment]
Fontionnalité dispo depuis la [3.20.0](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.20.0)
