### ISSUE TITLE
Site et parcours outdoor : affichage d'un voisin si la géométrie est ponctuelle

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#896]
Lorsqu'on créé un site ou un parcours outdoor dont la géométrie est un point, sur la fiche détail le pin sur la carte va tenter d'afficher un encart (comme pour afficher une vue informative sur les cartes listes).

Ex : https://gtr3demo.ecrins-parcnational.fr/outdoor-course/27-Longue-voie
https://demo-rando-v3.geotrek.fr/outdoor-site/29-Falaise-du-Bosquet

![image](https://user-images.githubusercontent.com/16348048/228008824-d5b08bad-06e4-4413-8533-1542dbb8ae4c.png)

Plus problématique, il est arrivé un cas (que je n'ai pas réussi à reproduire), où lorsqu'on survol le point, on affiche l'info d'un objet touristique qui n'a rien à voir (pas rattaché au site outdoor) : 

![image](https://user-images.githubusercontent.com/16348048/228008755-19c7e3b4-6f68-47f6-8363-2174d757e4ef.png)

Regression due à la refacto sur les cards ?

**Comment by babastienne** [comment]
Reproduit aujourd'hui, bug toujours valable. Il faut investiguer pour voir l'origine du problème.

**Comment by bruhnild** [comment]
Exemple de site outdoor de type point qui affiche au survol la vignette d'un contenu touristique : https://destination.portcros-parcnational.fr/outdoor-site/26-Plongee-sur-l-epave-du-Galeasson.

**Comment by dtrucs** [comment]
Fontionnalité dispo depuis la [3.20.0](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.20.0)
