### ISSUE TITLE
Contenus en anglais non affichés

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-rando-v3#910]
Pour certains itinéraires, les contenus en anglais ne s'affichent pas sur le portail Geotrek-rando.
Les contenus sont bien renseignés dans l'interface Geotrek-admin et ressortent bien sur l'application mobile.
Les logs ne semblent pas donner plus d'information sur ce problème et je ne parviens pas à comprendre pourquoi ça ne touche que certains itinéraires...

Exemple : 

[https://rando.sourcesvolcans.com/en/search?practices=1,4,6,10](https://rando.sourcesvolcans.com/en/search?practices=1,4,6,10)

**Comment by camillemonchicourt** [comment]
Il faudrait des précisions sur quels contenus ne s'affichent pas et sur quels itinéraires ?

Mais en essayant de deviner, tu parles du nom de certaines randos qui ne s'affichent pas ?

C'est normal, plusieurs des randos n'ont pas de nom renseigné en anglais, comme on le voit en interrogeant l'API (rando du portail 3, publiées en anglais, seulement les champs ID et NAME) : https://admin.destination-parc-monts-ardeche.fr/api/v2/trek/?portals=3&language=en&fields=id,name

**Comment by camillemonchicourt** [comment]
PS : Autre soucis lié à la customisation de ce portail.
La couleur primaire 3 est définie en blanc (`--color-primary3`).
Du coup quand on survole un résultat dans la liste des résultats son nom passe en blanc et n'est plus visible.

**Comment by camillemonchicourt** [comment]
Non, pas prévu et pas souhaitable il me semble.
D'autant plus que le nom de chaque rando est utilisé pour l'URL de la fiche rando, donc qu'il faut éviter de changer plus tard. 
Et qu'il est pertinent de différencier en français et en anglais.

**Comment by pnrma** [comment]
Je n'avais pas pensé au référencement en effet.
Merci Camille pour tes réponses.
