### ISSUE TITLE
"Sorry, this is not working properly." lorsqu'on sélectionne deux sous types de services

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-rando-v3#911]
Lorsqu'on sélectionne deux sous types de contenus touristiques dans les filtres "Services", on obtient un message d'erreur `Sorry, this is not working properly.`

Version de Geotrek-rando-v3 : 3.13.6
Testé sur macos 12.6.4 avec firefox et chrome

Observé sur notre portail ainsi que sur celui des Ecrins.

https://github.com/GeotrekCE/Geotrek-rando-v3/assets/44799642/d59da38c-c4a7-4bab-b85e-8eb2df028187

**Comment by camillemonchicourt** [comment]
Fixé dans la 3.14.0
