### ISSUE TITLE
Pop-up "Installer l'app" n'apparait pas tout le temps

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#913]
Tout est dans le titre. Lors d'une navigation sur mobile la popup proposant l'installation de l'app n'apparait pas toujours, ce qui pose problèmes pour certains territoires.

Confirmer ce comportement (contexte ?) et voir pour le corriger si possible.

**Comment by camillemonchicourt** [comment]
Voir https://github.com/GeotrekCE/Geotrek-rando-v3/issues/550
