### ISSUE TITLE
Google Analytics 4

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#916]
Le 1er Juillet Google Analytics passe en version 4 et l'ancienne version cesse de fonctionner.

Faut-il effectuer des ajustement dans Geotrek-Rando pour assurer que cela puisse continuer de fonctionner ?

https://support.google.com/analytics/answer/10759417?hl=fr

**Comment by camillemonchicourt** [comment]
Non, GTR3 est basé sur GAv4.

**Comment by babastienne** [comment]
Très bonne nouvelle, j'avais un doute.

Merci Camille pour ta réponse.
