### ISSUE TITLE
Problèmes de traduction sur certains sentiers

### ISSUE THREAD

**Issue by noelmartinon** [GeotrekCE/Geotrek-rando-v3#918]
Bonjour,
Sur une partie de notre site, certaines traductions EN et ES aboutissent à l'erreur "Sorry, this is not working properly." Je ne trouve rien dans les logs mais peut-être pas assez verbeux et ne trouve pas comment mettre "debug". Et au niveau debogueur du navigateur, pas mieux que Object { name: "Internal Server Error.", message: "500"... Le json retourné par geotrek semble correct.

J'ai pensé à un contenu un peu long mais je ne vois vraiment pas. Si vous avez une piste de recherche, je suis preneur.

Deux exemples : 
- Sentiers : https://www.randoguadeloupe.gp/en/trek/11675-From-Anse-a-l-Eau-to-Anse-Montal, JSON : https://geotrek.guadeloupe-parcnational.fr/api/v2/trek/11675/
- Sentiers : https://www.randoguadeloupe.gp/en/trek/10972-From-Petit-Havre-to-Anse-a-Saint, JSON : https://geotrek.guadeloupe-parcnational.fr/api/v2/trek/10972/

**Comment by dtrucs** [comment]
Bonjour,
Oui Camille a vu juste.

Ici le soucis s'exprimait sur les "informations desk" liés à la rando. 
Pour reprendre votre exemple, votre rando appelle les id 40 et 22 => https://geotrek.guadeloupe-parcnational.fr/api/v2/trek/11675/?fields=information_desks

La limitation se trouvait qu'en anglais on avait un `null` (le texte vide passe) => https://geotrek.guadeloupe-parcnational.fr/api/v2/informationdesk/22/?fields=description

Dans l'investigation j'en ai profité pour faire le bugfix. 
En attendant que le correctif soit intégré pour une prochaine release, je vous conseille de remplir ces champs afin de rendre ces pages de nouveaux accessible.

**Comment by noelmartinon** [comment]
Effectivement, dans les logs du docker j'avais "TypeError: First argument must be a string...nodeserver_1...at DetailsInformationDesk" mais j'avais regardé côté serveur uniquement ;)

En faisant un simple [Enregistrer] sur les lieux de renseignements suivi de `docker-compose pull && docker-compose down && docker-compose up -d`, les champs null deviennent un texte vide `""` et tout est fonctionnel.

Merci pour vos réponses.

**Comment by camillemonchicourt** [comment]
Fixé dans la 3.14.0
