### ISSUE TITLE
Absence de lien sur certaines images dans les listes de résulats

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-rando-v3#919]
Dans les listes de résultats, le lien sur certaines images ne semble pas être présent (pas de balise `a`).
Cela semble être le cas pour les images qui n'ont pas d'attribut `alt` renseigné (donc pas texte affiché sur la photo).
Observé sur des listes d'objets touristiques, avec des photos et sans photo (mais avec image de substitution `touristicContentLabelImageUri`).
Exemple : 
- [https://carte.destination-parc-monts-ardeche.fr/search?categories=1,6,10](https://carte.destination-parc-monts-ardeche.fr/search?categories=1,6,10)

Observé également sur les sélections sur la Home.

Version de Geotrek-rando-v3 : 3.13.6

**Comment by camillemonchicourt** [comment]
En effet, je vois bien le soucis sur votre Geotrek-rando.
