### ISSUE TITLE
Visualiser des Images HD et des fichiers attachés qui ne sont pas des images

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#943]
Ticket en lien avec https://github.com/GeotrekCE/Geotrek-admin/issues/3378

> Dans ce ticket les questions à éclaircir sont notés sous la forme de citation

Il s'agit de valoriser dans Geotrek-Rando les contenus "HD Views" qui sont associés à des Itinéraires ou des POIs.

Une réflexion a été menée pour trouver la meilleure manière de représenter ces objets dans l'interface de Geotrek-Rando afin de conserver une navigation compréhensible facilement pour l'utilisateur. Etant donné que ce travail permettait d'ajoute run nouveau type de fichiers attachés, il a été étudié le fait de pouvoir valoriser les autres types de fichiers attachés (pdf, sons, vidéos, documents, etc.) qui pour le moment ne sont pas mis en avant dans Geotrek-Rando. Même si cette dernière étude n'est pas implémentée immédiatement cela nous permettra de savoir quelle interface mettre en oeuvre lorsqu'elle pourra être développée.

Rappel des contraintes : 
- Un itinéraire et/ou un POI peut avoir plusieurs HD Views rattachées
- Il faut imaginer qu'un POI peut avoir plusieurs HD Views alors qu'il est sur la fiche d'un itinéraire ayant lui aussi plusieurs HD Views (-> ne pas perdre l'utilisateur dans la navigation)
- L'utilisateur doit pouvoir zoomer / naviguer sur la vue HD

## Ajout des fichiers attachés sur la fiche détail d'un trek - Vue PC

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/c77cafac-d729-4225-8965-391670ce18d0)

1. On donne à l'utilisateur la possibilité d'identifier rapidement le fait que du contenu complémentaire est accessible.

> Doit-on pouvoir cliquer sur ces pictogrammes pour renvoyer directement vers l'ancre dépliée ?

> Est-ce que la vignette d'une randonnée dans la vue liste doit afficher ces pictogrammes ?

> Quel texte afficher au survol (alt text) ?

2. La fiche détail contient sous le chapeau un bloc permettant d'afficher le détail des fichiers attachés. Par défaut les contenus sons repliés, l'utilisateur peut choisir de déplier une ou plusieurs sections.

**Pour les contenus dépliés, voici une proposition d'interface :**
 
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/0ef01745-c002-4f4f-a259-49967b021de8)

1. Les vidéos seront listées avec les données associées mais seront jouées dans une pop-up (pour la vue PC), voir capture ci-après. L'idée est que l'utilisateur ai un focus sur la vidéo en cours et ne fasse pas d'autre action à ce moment sur la fiche de l'objet.

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/05062178-7e63-429e-85db-a85a09179260)

2. Les contenus audio pourront être joués directement depuis le navigateur, en utilisant le player natif du support. Cela permet à l'utilisateur de jouer un son par exemple et de lire la description en même temps.

3. Les fichiers attachés autres (documents, pdf, etc.), ne pourront être prévisualisés mais pourront être téléchargés sur l'appareil de l'utilisateur.

4. (section non visible sur la capture) Les images HD seront listées  un peu à la manière des vidéos, avec la descriptions et attributions détaillées. Un bouton permettra de cliquer sur "Afficher l'image HD"

> Comment doit-on appeler une Image HD dans l'interface ? Image HD ? Point de vue HD ? Topo ?

**Lorsque l'utilisateur clique sur "voir une Image HD"**

Alors l'image vient prendre la place de la carte, et conserve le même système de zoom/dezoom et de navigation que la carte pour proposer une interface homogène à l'utilisateur. Un bouton vient apparaître en bas de la zone pour permettre à l'utilisateur à tout moment de revenir à la vue carte.

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/00e2ab49-c9a6-4fcf-80fa-6ab7b1beb370)

## Ajout des fichiers attachés sur la fiche détail d'un trek - Vue Mobile

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/fa69aac4-6721-40b6-953b-b2fd17f00ccf)

Rien de vraiment différent par rapport à la vue PC. Lorsqu'on déplie les sections on obtient un résultat similaire.

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/3e2fe43f-c907-417c-90ab-8f4dc43fc85f)

Lorsqu'on joue une vidéo cette fois celle-ci vient en plein écran sur l'appareil. 

Lorsqu'on clique pour voir le détail d'une Image HD alors on obtient une interface similaire à la vue Carte. Il est possible uniquement pour l'utilisateur de revenir à l'écran précédent.

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/ce0ca7da-31ba-4b45-8702-084fa14ab3ec)

## Ajout des fichiers attachés sur un POI - Vue PC

Ici encore, similaire à la proposition pour les treks. Il convient d'ajouter visuellement une identification sur la vignette pour inciter l'utilisateur à déplier le POI car c'est seulement en dépliant le POI qu'il pourra accéder aux rubriques des fichiers attachés.

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/b8d34783-3b2e-4ad2-9924-2eaf9d34dc6d)

La lecture des sons, l'affichage des vidéos et des images HD sera identique à la proposition pour les itinéraires.

(ne pas tenir compte du bouton "voir les images HD" qui sera supprimé au profit d'une section dédiée avec les autres fichiers attachés et d'un picto d'identification sur la vignette)

## Ajout des fichiers attachés sur un POI - Vue Mobile

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/7bbf11f5-2141-4989-a532-e19ee72b5384)

**Comment by camillemonchicourt** [comment]
Merci pour ce récapitulatif complet.

En effet, comme il s'agit un autre type de média que les photos classiques sur les fiches détails, la réflexion a été élargie pour prendre en compte tous les autres médias, et permet ainsi d'alimenter en même temps https://github.com/GeotrekCE/Geotrek-rando-v3/issues/375

Mes retours : 

> Doit-on pouvoir cliquer sur ces pictogrammes pour renvoyer directement vers l'ancre dépliée ?

Oui, important il me semble.

> Est-ce que la vignette d'une randonnée dans la vue liste doit afficher ces pictogrammes ?

Non, c'est du contenu secondaire, seulement pertinent de mettre en avant sur les fiches détail.

> Quel texte afficher au survol (alt text) ?

Des boutons au niveau des photos de l'objet ? "Afficher les vidéos" ou "3 vidéos disponibles"

----------------

Pour les vidéos, en fait je mettrais directement le player (youtube, dailymotion, vimeo ou natif si fichier vidéo local) dans le bloc, sans l'ouvrir dans une modale. C'est plus simple, plus direct, on peut toujours passer facilement la vidéo en plein écran, et ça évite de devoir générer une vignette image cliquable dont on ne dispose pas...).

-----------------

> Comment doit-on appeler une Image HD dans l'interface ? Image HD ? Point de vue HD ? Topo ?

Je partirai sur "Photo HD". Un peu technique mais précis et quand même compréhensible.

-----------------

Pour les POI, je mettrai peut-être les blocs repliés sous les POI concernés toujours affichés, et non pas un truc caché à voir dans "Lire la suite".

**Comment by babastienne** [comment]
Nous sommes actuellement en train de chercher quel pictogramme utiliser pour illustrer le concept de photo HD. 

Nous avons évoqué plusieurs axes : 
- caméra / appareil photo
- image / landscape
- agrandissement / haute qualité / interactivité

Après quelques recherches voici ma shortliste : 

_________

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/68d3a1e7-3d0c-48ae-843e-6d4055249cc2)
https://thenounproject.com/icon/resize-image-6010941/

__________

(mon préféré)
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/10c00a58-29a3-493e-8aee-7fa12503565b)
https://thenounproject.com/icon/resize-photo-5876913/

____________

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/cba8dd58-2a78-4e63-8b6b-8e56683a1498)
https://thenounproject.com/icon/resize-image-4880013/

___________

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/ae46637e-6751-4a9b-a262-52ecd9638114)
https://thenounproject.com/icon/resize-3638259/

____________

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/188600f4-1655-445b-a1aa-39654025f940)
https://thenounproject.com/icon/hd-movie-2426700/
(j'ai peur qu'on interprète ce picto comme une vidéo)

___________

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/f8d88228-c84b-40bb-9f8d-db992a87a65b)
https://www.svgrepo.com/svg/311143/resize-image

__________

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/ab8013f5-2093-407b-be4c-560ac3b5ce4c)
https://www.svgrepo.com/svg/208287/resize-size
(je me dit que le `i` peut être interprété comme "interactif" [et dans ce cas on pourrait renommer le titre de section en "Image interactive de haute qualité" ou un truc du style], ou alors comme "information". Ca peut créer de la curiosité chez l’utilisateur et l'inciter à cliquer dessus)

________

Peut-être pour évoquer les annotations sur les images
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/a1e24b53-d5f3-47b8-80ab-9b2eb3ad4532)
https://iconmonstr.com/picture-11-svg/

______

Une idée @camillemonchicourt ?

**Comment by camillemonchicourt** [comment]
Oui le deuxième est le mieux selon moi.
Il est pas trop détaillé et on voit bien le principe de zoom dans une photo.
De plus il est cohérent avec les autres pictos de l'application, assez simples, fins et arrondis.
Les pictos angulaires ne collent pas avec ceux existants et sont moins claires selon moi.

A voir ce qu'il faut créditer et comment.

**Comment by babastienne** [comment]
Il faut qu'on détermine ce qu'il faut mettre pour les trois éléments suivants : 
![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/00935846-5bfe-4330-a4bf-c37318bce3b8)

- Quel picto utiliser
- Quel titre de section mettre
- Comment décrire la fonctionnalité en quelques mots

**Comment by camillemonchicourt** [comment]
Premier aperçu des développements : 

- Si une rando ou un site Outdoor a des images HD associées, alors elles sont affichées dans sa fiche détail et sur la carte : 

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/4418840/8c30e5c5-cead-4dd4-b4a3-d228c3918dcd)

- Si on clique sur une image HD, alors elle s'affiche à la place de la carte de l'objet et on peut naviguer dans celle-ci, ou revenir à la carte : 

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/4418840/4df6283e-a87a-465f-9652-eca48e0bfd76)

**Comment by babastienne** [comment]
J'aimerai bien tenter une modification du picto que je trouve pas terrible. Est-ce que tu es ok pour mettre celui-ci à la place @camillemonchicourt  ?

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/923305f4-cbdd-42d2-a6cf-64cf102a52b0)

**Comment by camillemonchicourt** [comment]
L'actuel n'est pas idéal mais celui-ci me plait moins pour 2 raisons : 
- Le crayon laisse surtout penser que c'est un éditeur d'image
- Toutes les icônes sont d'un style plus fin et surtout arrondi donc celle-ci est trop différente en terme de style

**Comment by babastienne** [comment]
Et une version intermédiaire comme ça ?

![noun-resize-photo-5876913](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/dff8054b-5868-4215-a532-37ad56ddfc21)

**Comment by camillemonchicourt** [comment]
Oui comme ça il sera surement un peu plus lisible/visible.

**Comment by babastienne** [comment]
Problème observé : 
- Dans la légende sur la carte on affiche toujours "Images HD" y compris quand l'objet en question ne possède pas d'imges HD. L'affichage devrait être conditionnel.

**Comment by dtrucs** [comment]
> Problème observé :
> 
>     * Dans la légende sur la carte on affiche toujours "Images HD" y compris quand l'objet en question ne possède pas d'imges HD. L'affichage devrait être conditionnel.

Corrigé dans cette PR https://github.com/GeotrekCE/Geotrek-rando-v3/pull/1048, ça sera pour la prochaine release

**Comment by dtrucs** [comment]
> Problème observé :
> 
>     * Dans la légende sur la carte on affiche toujours "Images HD" y compris quand l'objet en question ne possède pas d'imges HD. L'affichage devrait être conditionnel.

Fixé depuis la [v3.19.0](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.19.0)

**Comment by camillemonchicourt** [comment]
Ajout des photos HD dans la version 3.18.0, puis corrigée dans la 3.18.0.
