### ISSUE TITLE
Chip badge display problem

### ISSUE THREAD

**Issue by numahell** [GeotrekCE/Geotrek-rando-v3#959]
When there are more than 2 or 3 themes, they are displayed on a single line, and their width is reduced.

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/546686/27d2feb0-2e14-4262-b7c8-f0ff0d05dce9)

It could be fixed by adding `flex-wrap: wrap;` on chips container (thx @bastyen ), and removing height fixed on result list card.

**Comment by babastienne** [comment]
Ca ne semble pas se produire sur toutes les instances ... A creuser

**Comment by xavyeah39** [comment]
Je confirme que l'on rencontre le même problème sur nos instances depuis màj en 3.15
Quand les cards contiennent plusieurs tags d'une certaine longueur :  affichage des "chips" sur une ligne.
Sur les cards de la home mais aussi sur celles de la page recherche : 

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16793813/44667e48-3b3a-4ead-b870-4900aa889137)

Cela semble bien lié à la disparition de `flex-wrap: wrap` et `display: inline-flex;` de ces éléments suite aux évolutions de la 3.15.0 dans #951.

**Comment by dtrucs** [comment]
Fixed since [v3.15.2](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.15.2).
