### ISSUE TITLE
Fiches détails - Pouvoir afficher les couches secondaires par défaut sur les cartes (Infos, signalétique, aménagements)

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-v3#997]
Actuellement quand est sur une fiche détail d'une rando, les objets sur la carte s'affichent en fonction des infos de la partie de gauche sur laquelle on est positionné (j'affiche les patrimoines sur la carte quand je suis au niveau du bloc d'info "Patrimoines") : 

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/4418840/9013031c-b1e5-41fe-901e-9dc3bba7ff36)

Mais il est aussi possible d'afficher sur la carte des contenus complémentaires qui ne sont pas listés ni détaillés dans la partie de gauche : 
- Signalétique
- Aménagement
- Autres infos (aka Services)

Mais pour les afficher, il faut que l'utilisateur ouvre le gestionnaire des couches et affiche ces couches, ce que très peu d'utilisateurs doivent savoir et donc faire.

Il est donc souhaité pouvoir ajouter un paramètre permettant de définir que ces couches secondaires sont activées par défaut.

**Comment by dtrucs** [comment]
Fontionnalité dispo depuis la [3.20.0](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.20.0) en définissant la variable `displaySecondaryLayersByDefault` dans `global.json`
