### ISSUE TITLE
Bug : Tri des pratiques par ordre

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-v3#998]
Actuellement les pratiques d'itinéraires ne sont pas triées correctement dans le bandeau des filtres.

En effet les pratiques possèdent un champ "order" qui doit servir à les ordonner dans le bandeau mais ce champ n'est pas pris en compte.

**Démonstration :** 

Sur la page d'accueil, la barre d'activité prend bien en compte le champ `order` : 

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/795affca-35e1-4199-8b0b-0d1d5f3349a9)

Dans les filtres toutefois l'ordre des pratique n'est pas le même, le champ `order` n'est plus respecté : 

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/16348048/4d8392d0-e8ba-485b-9963-982a85fa9e2c)

En fait si on regarde on voit les filtres utilisent le champ `id` pour classer les pratiques mais cela n'est pas correct comme comportement.

Je n'ai pas regardé si le problème est le même pour l'outdoor / services / évènements. A vérifier.

**Comment by dtrucs** [comment]
Effectivement ce n'est pas trié explicitement par le champ `order`, mais par l'odre naturel du tableau envoyé par l'API.
D'ailleurs ça serait bien que l'API envoie également les éléments dans l'ordre qu'il indique.

**Comment by dtrucs** [comment]
Fixé depuis la  [v3.16.1](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.16.1)
